centrifuge/apps

tinlake-ui/containers/Investment/View/ManageMemberlist.tsx
This pull request adds a `Remove` button to the member list that updates a member's valid date to 8 days in the future.
[Staging Link](https://605cbd03bd0c9277013221c0--tinlake-kovan-staging.netlify.app)
Closes #167
=> feat: add a remove button for member list

docs/rfcs/tinlake-ui-release-rfc.md
This pull request contains an RFC (request for comments) regarding a proposal for a slight change to the `tinlake-ui` release process.
=> docs: tinlake-ui release rfc

.github/workflows/tinlake-ui-deploy-to-prod.yml, .github/workflows/tinlake-ui-deploy-to-staging.yml
This pull request removes the paths check for the `staging` and `prod` workflow.
=> ci: remove paths

.github/workflows/tinlake-ui-deploy-to-staging.yml
This pull request remove the step to deploy to IPFS.
=> ci: remove ipfs deploy step

.github/workflows/tinlake-ui-deploy-to-dev.yml, .github/workflows/tinlake-ui-deploy-to-prod.yml, .github/workflows/tinlake-ui-deploy-to-staging.yml, .github/workflows/tinlake-ui-pull-request.yml
This pull request caches yarn workspaces to improve build times.
=> ci: cache yarn workspaces

tinlake-ui/config.ts, tinlake-ui/containers/Investment/View/AdminActions.tsx, tinlake-ui/containers/Investment/View/TrancheOverview.tsx, tinlake-ui/containers/Loan/List/index.tsx, tinlake-ui/containers/Loan/Overview/MaxReserveForm.tsx, tinlake-ui/containers/Loan/Overview/index.tsx, tinlake-ui/containers/Overview/index.tsx, tinlake-ui/ducks/pool.ts
This pull request replaces the hard coded `RWA002-A` value with the `maker.ilk` value.
Also, the `check-format` CI job was failing because of formatting violations. I included those small fixes in this.
[mainnet preview](https://60bfce544512d846edce2dd6--staging-tinlake.netlify.app)
Closes #232
=> fix: replace hard coded value with ilk value

tinlake-ui/containers/DataQuery/queries.ts
- Pool list --> Debt per pool (current)
- Daily TVL --> TVL (daily)
- Asset list --> Asset details per pool (current)
- Daily token prices --> TIN/DROP token prices (daily)
Closes #258
=> Change button labels on Tinlake query page

tinlake-ui/components/PoolList/styles.ts, tinlake-ui/containers/Portfolio/index.tsx
Tweaks the empty portfolio view
Closes #288
=> Empty portfolio change

tinlake-ui/components/Loan/List/index.tsx, tinlake-ui/components/Overview/OverviewHeader.tsx, tinlake-ui/components/PoolsMetrics/index.tsx, tinlake-ui/containers/Dashboard/index.tsx, tinlake-ui/containers/Investment/View/InvestmentOverview.tsx, tinlake-ui/containers/Investment/View/TrancheOverview.tsx, tinlake-ui/containers/Investment/View/index.tsx, tinlake-ui/containers/Investment/View/styles.tsx, tinlake-ui/containers/Loan/Overview/index.tsx, tinlake-ui/containers/UserRewards/index.tsx
Makes some small changes to make things look a bit better on mobile. Mostly making cards stack vertically on small screens.
=> Mobile improvements

tinlake-ui/components/PoolsMetrics/index.tsx, tinlake-ui/containers/Loan/Overview/index.tsx
=> Fix chart cutoff

tinlake-ui/containers/Portfolio/index.tsx, tinlake-ui/ducks/portfolio.ts, tinlake-ui/services/apollo/index.ts
Takes the token price directly from the contract instead of calculating based on balance and total value
Closes #157
=> Fix token price on portfolio page

tinlake-bot/package.json, tinlake-bot/src/config.ts, tinlake-bot/src/index.ts, tinlake-bot/src/tasks/sendSupplyRedeemSummary.ts, tinlake-bot/src/util/ipfs.ts, tinlake-bot/src/util/slack.ts, yarn.lock
Adds a cron job to send open orders for each pool to Slack once a day.
Closes #307, #268
=> Display daily pool update in Slack

tinlake-bot/src/tasks/closePools.ts
=> Automatically close pools if DROP redemptions can be taken out of reserve

tinlake-ui/components/Header/index.tsx
Signed-off-by: Alessio Scalici <alessio@centrifuge.io>
=> chore: change header labels (#335)

tinlake-ui/pages/pool/[root]/[slug]/management/index.tsx, tinlake-ui/utils/hooks.ts, tinlake-ui/utils/useEpoch.ts, tinlake-ui/utils/usePool.ts
=> Fix management page breaking when pool address in URL is lowercase

tinlake-ui/components/LabeledValue/index.tsx, tinlake-ui/components/Layout/Stack.ts, tinlake-ui/components/Overview/OverviewHeader.tsx, tinlake-ui/utils/usePool.ts
Still needs the Invest button to be added to the PageTitle on desktop, but waiting with that until #374 is merged.
=> New Maker box and Pool Overview header

tinlake-ui/components/Overview/OverviewHeader.tsx, tinlake-ui/components/Overview/index.tsx
=> Add Invest button to page header on desktop

tinlake-ui/containers/Loan/Borrow/index.tsx, tinlake-ui/containers/Loan/UnlockNft/index.tsx, tinlake-ui/package.json, tinlake-ui/pages/pool/[root]/[slug]/assets/asset.tsx, yarn.lock
Contributes to [363](https://github.com/centrifuge/apps/issues/363)
=> Move unlock nft

tinlake-ui/components/PoolList/index.tsx, tinlake-ui/components/PoolList/styles.ts
Contributes to https://github.com/centrifuge/apps/issues/363
=> Align Investment Capacity column to the left

tinlake-ui/containers/Investment/View/EpochOverview.tsx, tinlake-ui/containers/Investment/View/EpochOverviewHeader.tsx
Contributes to https://github.com/centrifuge/apps/issues/363
=> Epoch overview header

tinlake-ui/containers/Loan/Borrow/index.tsx
Closes https://github.com/centrifuge/apps/issues/379
https://user-images.githubusercontent.com/8630331/134667349-58c4b39e-6eba-4cd8-98f5-e5bedac4d8da.mov
=> Make finance button visible at page load

tinlake-ui/components/PoolCapacityLabel/index.tsx
Closes https://github.com/centrifuge/apps/issues/378
=> Format capacity when >= 1M

tinlake-ui/containers/Investment/View/TrancheOverview.tsx, tinlake-ui/containers/Investment/View/styles.tsx
Closes https://github.com/centrifuge/apps/issues/398
=> Change style of Display token in your wallet

tinlake-ui/components/BackButtonHeader/index.tsx, tinlake-ui/components/Button/index.tsx, tinlake-ui/components/Checkbox/index.tsx, tinlake-ui/components/DebugFlags/DebugFlags.tsx, tinlake-ui/components/DebugFlags/config.ts, tinlake-ui/components/FunnelHeader/index.tsx, tinlake-ui/components/Onboarding/AgreementStep.tsx, tinlake-ui/components/Onboarding/AlertIcon.tsx, tinlake-ui/components/Onboarding/CheckIcon.tsx, tinlake-ui/components/Onboarding/ClockIcon.tsx, tinlake-ui/components/Onboarding/ConnectStep.tsx, tinlake-ui/components/Onboarding/Header.tsx, tinlake-ui/components/Onboarding/InfoBox.tsx, tinlake-ui/components/Onboarding/KycStep.tsx, tinlake-ui/components/Onboarding/LinkStep.tsx, tinlake-ui/components/Onboarding/Step.tsx, tinlake-ui/components/Onboarding/StepParagraph.tsx, tinlake-ui/components/Onboarding/index.tsx, tinlake-ui/components/Onboarding/styles.ts, tinlake-ui/components/PageContainer/index.tsx, tinlake-ui/components/Text/index.tsx, tinlake-ui/containers/Investment/View/index.tsx, tinlake-ui/containers/Onboarding/LinkStep.tsx, tinlake-ui/pages/pool/[root]/[slug]/onboarding/index.tsx, tinlake-ui/theme.ts
Most of the components are copied over from the old onboarding with only styling changes. Didn't make too much effort yet to refactor a lot. Might come when we need to adapt it to only investor onboarding.
The new onboarding is currently behind a debug flag.
Closes #394
=> Pool onboarding

tinlake-ui/components/ValuePairList/index.tsx, tinlake-ui/config.ts, tinlake-ui/containers/Investment/View/TrancheOverview.tsx
Closes https://github.com/centrifuge/apps/issues/375
=> Show contact issuer in TIN card

tinlake-ui/containers/Investment/View/TrancheOverview.tsx
Closes https://github.com/centrifuge/apps/issues/397
=> Add gray background to token properties

tinlake-ui/components/Layout/Grid.tsx, tinlake-ui/containers/Investment/View/EyeIcon.tsx, tinlake-ui/containers/Investment/View/TrancheOverview.tsx, tinlake-ui/containers/Investment/View/index.tsx
Closes https://github.com/centrifuge/apps/issues/416
https://user-images.githubusercontent.com/8630331/135281700-b8e751f1-f95d-4a87-9eae-4c51cc9507f0.mov
https://user-images.githubusercontent.com/8630331/135281673-3f7db4a8-0953-4d03-8435-6a0a63fb44c4.mov
=> Invest component amendments

tinlake-ui/containers/Investment/View/EpochOverview.tsx
Closes https://github.com/centrifuge/apps/issues/420
=> Fix wrong percentage in epoch overview

tinlake-ui/components/InvestAction/index.tsx
Old invest button wasn't redirecting to pool onboarding page when pool is not upcoming. Also fixes alignment of `Onboard as Investor` button
=> Fix invest button for old onboarding

PULL_REQUEST_TEMPLATE.md
This pull request adds a PR template that will auto-fill the description text area for future PR's.
[Related Github documentation](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository)
=> chore: add pr template

tinlake-ui/containers/Investment/View/TrancheOverview.tsx
Fixes showing the invest card when clicking on the `Invest` button after completing onboarding
Pool Investments, tranche cards
=> Fix deeplink to invest card

CHANGELOG.md, tinlake-ui/package.json
This pull request updates Jest and CRA (react-scripts) versions in order to be up to date and aligned through all the project workspaces
Testing of `tinlake-ui`, `gateway`
=> Align jest version throughout the project

tinlake-ui/containers/UserRewards/index.tsx
This pull request fixes the wrongly rounded rewards rate
Closes #502 
Rewards page
=> fix rounded rewards rate

tinlake-ui/components/Onboarding/InvestorOnboarding.tsx, tinlake-ui/components/Onboarding/KycStep.tsx, tinlake-ui/components/Onboarding/LinkStep.tsx, tinlake-ui/components/Onboarding/MultipleAddressesNotice.tsx, tinlake-ui/components/Onboarding/PoolOnboarding.tsx, tinlake-ui/containers/Investment/View/styles.tsx
Tweaks to the onboarding UI
* Update KYC step copy
* Show KYC step when pending and agreement is countersigned
* Update "multiple addresses linked" notification
Closes #444, closes #445, closes #446  
Pool Onboarding, Investor Onboarding
=> Onboarding tweaks

tinlake-ui/components/Onboarding/InfoBox.tsx, tinlake-ui/containers/Dashboard/index.tsx, tinlake-ui/containers/Investment/View/styles.tsx, tinlake-ui/pages/onboarding/index.tsx, tinlake-ui/pages/pool/[root]/[slug]/onboarding/index.tsx
=> Tinlake: Release 44 mergeback

nft-studio/src/components/CreateCollectionDialog.tsx, nft-studio/src/pages/Collections.tsx, nft-studio/src/utils/useBalance.ts, nft-studio/src/utils/useCollections.ts, nft-studio/src/utils/web3.ts
=> NFT Studio: Collections hooks

nft-studio/src/components/FileImageUpload.tsx, nft-studio/src/components/SplitView.tsx, nft-studio/src/pages/Collection.tsx, nft-studio/src/pages/MintNFT.tsx, nft-studio/src/utils/format/formatAddress.ts, nft-studio/src/utils/useCollections.ts
This pull request adds the file loader to the mint nft studio, and reads metadata for collections
Nft studio
=> feat(nft-studio): add image file loader

fabric/src/components/LayoutGrid/index.tsx, nft-studio/package.json, nft-studio/src/components/CollectionCard.tsx, nft-studio/src/components/CreateCollectionDialog.tsx, nft-studio/src/components/LoadBoundary.tsx, nft-studio/src/components/PageContainer.tsx, nft-studio/src/components/Spinner.tsx, nft-studio/src/pages/Collections.tsx, nft-studio/src/utils/useCollections.ts, nft-studio/src/utils/useMetadata.ts, yarn.lock
* Adds loading and error states
* Adds collection preview images
* Refetch collections and balance when creating collection
NFT Studio, Fabric
=> NFT Studio: Collection preview images

nft-studio/src/components/CreateCollectionDialog.tsx, nft-studio/src/components/TextArea.tsx, nft-studio/src/components/TextInput.tsx, nft-studio/src/pages/MintNFT.tsx, nft-studio/src/utils/format/formatAddress.ts
This pull request styles the create collection dialog as per design.
NFT studio
=> chore(nft-studio): style create collection dialog

nft-studio/.env.example, nft-studio/lambda/pinata/api.js, nft-studio/package.json, nft-studio/src/components/CollectionCard.tsx, nft-studio/src/components/CreateCollectionDialog.tsx, nft-studio/src/components/Footer.tsx, nft-studio/src/components/Identity.tsx, nft-studio/src/components/NFTCard.tsx, nft-studio/src/components/Root.tsx, nft-studio/src/components/TransactionToasts.tsx, nft-studio/src/components/TransactionsProvider.tsx, nft-studio/src/components/TransferDialog.tsx, nft-studio/src/pages/Collection.tsx, nft-studio/src/pages/Collections.tsx, nft-studio/src/pages/MintNFT.tsx, nft-studio/src/pages/NFT.tsx, nft-studio/src/utils/copyToClipboard.ts, nft-studio/src/utils/createNFTMetadata.ts, nft-studio/src/utils/getAvailableClassId.ts, nft-studio/src/utils/useBalance.ts, nft-studio/src/utils/useCollections.ts, nft-studio/src/utils/useCreateTransaction.ts, nft-studio/src/utils/useIdentity.ts, nft-studio/src/utils/useMetadata.ts, nft-studio/src/utils/useTransactionFeeEstimate.ts, nft-studio/src/utils/web3.ts, yarn.lock
* Adds transaction for minting
* Displays nickname instead of address if set
* Adds error messages if balance is too low when minting/creating collection/transferring
* Fix check if user is owner of collection and can mint
* Reset forms on success
NFT Studio
=> NFT Studio: Mint NFT transaction and error messages

nft-studio/.env.example, nft-studio/src/components/CollectionCard.tsx, nft-studio/src/components/CreateCollectionDialog.tsx, nft-studio/src/components/Root.tsx, nft-studio/src/components/TransactionToasts.tsx, nft-studio/src/components/TransferDialog.tsx, nft-studio/src/components/VisibilityChecker.tsx, nft-studio/src/pages/AccountNFTs.tsx, nft-studio/src/pages/Collection.tsx, nft-studio/src/pages/Collections.tsx, nft-studio/src/pages/MintNFT.tsx, nft-studio/src/utils/useCollections.ts, nft-studio/src/utils/useCreateTransaction.ts, nft-studio/src/utils/useNFTs.ts, nft-studio/src/utils/useVisibilityChecker.ts
* Adds link to view transaction on Subscan
* Lazy-loads collections and nfts
* Adds account page with owned nfts
NFT Studio
=> NFT Studio: Account page and lazy-loading NFTs

nft-studio/src/components/CollectionCard.tsx, nft-studio/src/components/CreateCollectionDialog.tsx, nft-studio/src/components/Identity.tsx, nft-studio/src/components/NFTCard.tsx, nft-studio/src/pages/Collection.tsx, nft-studio/src/pages/Collections.tsx, nft-studio/src/pages/MintNFT.tsx, nft-studio/src/pages/NFT.tsx, nft-studio/src/schemas.ts, nft-studio/src/utils/useCollections.ts, nft-studio/src/utils/useMetadata.ts, nft-studio/src/utils/useNFTs.ts
Adds some validation for the metadata, to make sure that invalid metadata doesn't break the app for everyone. Also adds some text wrapping, so long names/descriptions without spaces won't break the layout.
NFT Studio
=> NFT Studio: Metadata validation

tinlake-ui/components/PoolList/index.tsx
In the pool list, check if 30 day senior yield is zero and display expected APR if so.
Tinlake pool list
=> Tinlake UI: Check if yield is zero

fabric/src/components/Menu/index.tsx, fabric/src/theme/altairDark.ts, fabric/src/theme/centrifugeDark.ts, nft-studio/.env.example, nft-studio/src/components/CollectionCard.tsx, nft-studio/src/components/CreateCollectionDialog.tsx, nft-studio/src/components/NFTCard.tsx, nft-studio/src/components/Root.tsx, nft-studio/src/components/TextArea.tsx, nft-studio/src/components/TextInput.tsx, nft-studio/src/components/TransferDialog.tsx, nft-studio/src/pages/Collection.tsx, nft-studio/src/pages/Collections.tsx, nft-studio/src/pages/MintNFT.tsx, nft-studio/src/pages/NFT.tsx, nft-studio/src/utils/useCreateTransaction.ts, nft-studio/src/utils/web3.ts, nft-studio/styled.d.ts
Implements design feedback and adds the option to enable the list of collections shown to be only from whitelisted accounts.
Closes #537  
* 1px box shadow for overlay card in dark mode. removed dividers
* placeholders for images while loading
* NFT description 
* correct font for inputs 
NFT Studio, Fabric
=> NFT Studio: Design feedback

tinlake-ui/components/Overview/index.tsx, tinlake-ui/components/Scorecard/index.tsx, tinlake-ui/containers/Investment/View/InvestmentOverview.tsx, tinlake-ui/containers/PoolManagement/Liquidity.tsx, tinlake-ui/containers/PoolManagement/Risk.tsx, tinlake-ui/utils/addThousandsSeparators.ts, tinlake.js/src/utils/feeToInterestRate.ts, tinlake.js/src/utils/toPrecision.ts
* Show contact the issuer also when no address connected. Closes #541 
* Show interest rates with 2 decimals. Closes #530
* Change "Term Recovery Rate" to "Assumed Risk Adjustment"
* Weighted average financing fee and maturity. Closes kfactory-dev/tinlake-roadmap#45
Tinlake
=> Tinlake: small fixes

fabric/iconTemplate.js, fabric/package.json, fabric/src/theme/tokens/brandAltair.ts, nft-studio/src/components/CreateCollectionDialog.tsx, nft-studio/src/components/NFTCard.tsx, nft-studio/src/pages/MintNFT.tsx, nft-studio/src/pages/NFT.tsx, nft-studio/src/utils/useMetadata.ts, yarn.lock
* Downgrades Svgr again, because it was messing up the icons.
* Change Altair yellow
* Prefetch IPFS metadata, when creating collection / minting NFT, so the name and description are immediately visible in the cards on the collections / collection pages.
* Some styling tweaks
Fabric, NFT Studio
=> NFT Studio: small fixes

.github/workflows/fabric-publish.yml, fabric/.versionrc, fabric/README.md, fabric/package.json, yarn.lock
Adds Github Action to publish Fabric to NPM. Publishes a new version on merge to `main` and uses `standard-version` to bump the version and update the changelog.
Fabric
=> Publish Fabric

.github/workflows/fabric-publish.yml
Fix Github Action for Fabric publishing
=> Fix Github Action for Fabric publishing

tinlake-ui/components/Web3Wallet/Web3Wallet.tsx, tinlake-ui/utils/useENS.ts
Show ENS name if user owned one
Closes #560
=> feat: ens name support

tinlake-ui/components/Web3Wallet/Web3Wallet.tsx, tinlake-ui/utils/useENS.ts
Show ENS avatar if user has it
Closes #574
=> feat(tinlake-ui): display ENS avatar

.github/workflows/tinlake-ui-deploy-to-dev.yml, .github/workflows/tinlake-ui-deploy-to-prod.yml, .github/workflows/tinlake-ui-deploy-to-staging.yml, .github/workflows/tinlake-ui-pull-request.yml, tinlake-ui/.env.kovan-example, tinlake-ui/.env.mainnet-example
=> chore: swap subgraph

.github/workflows/fabric-storybook-deploy.yml, fabric/netlify.toml
This pull request adds a Github workflow to automatically build and deploy `fabric` storybook
No impact
=> Fabric storybook deploy

.github/workflows/nft-studio-deploy-dev.yml, .github/workflows/nft-studio-deploy-prod.yml, .github/workflows/nft-studio-deploy-pull-request.yml, .github/workflows/nft-studio-deploy-staging.yml
This pull request sets the environment variables in the NFT Studio Github action workflows.
=> chore(nft-studio): set env variables for the build

.github/workflows/nft-studio-build-and-deploy.yml, .github/workflows/nft-studio-deploy-dev.yml, .github/workflows/nft-studio-deploy-prod.yml, .github/workflows/nft-studio-deploy-pull-request.yml, .github/workflows/nft-studio-deploy-staging.yml, nft-studio/lambda/pinFile.js, nft-studio/lambda/pinFileWithMetadata.js, nft-studio/netlify.toml
This pull request passes build env variables to build workflow
=> Pass build env variables to build workflow

centrifuge-js/src/utils/index.ts, nft-studio/src/pages/Loan.tsx, nft-studio/src/pages/Pool.tsx, nft-studio/src/pages/Token.tsx
* Adds more decimals to certain displayed values
* Adds token price and invested amount to tranche card
Closes #622, #623, #624
POCC
=> POCC: Add decimals

fabric/src/components/FileUpload/FileUpload.stories.tsx, fabric/src/components/FileUpload/index.tsx
Adds a file upload component. Supports dragging and dropping a file onto it. Still uses outdated icon, those still need to be updated.
Fabric
=> Fabric: File upload

tinlake-ui/package.json, tinlake-ui/scripts/generateRedirects.ts, tinlake-ui/tsconfig.json, yarn.lock
This pull request redirects the user to the pool page when they use an URL with the following formats:
- `/[ID]` --> `/pool/[ID]/[slug]`
- `/pool/[ID]` --> `/pool/[ID]/[slug]`
- `/[slug]` --> `/pool/[ID]/[slug]`
Closes [#51](https://github.com/centrifuge/apps/issues/51)
Tinlake UI
=> Rewrite redirects

tinlake-ui/components/Scorecard/index.tsx, tinlake-ui/containers/Loan/Overview/index.tsx, tinlake-ui/pages/pool/[root]/[slug]/assets/index.tsx
This pull request adds average values to the header of portfolio distribution component, and applies few more design amendments
Closes #588
=> Add avg values portfolio distribution

nft-studio/src/pages/MintNFT.tsx
This pull request disables cancel button and fields while transaction is pending
Closes #653
=> Disable cancel button and fields while transaction is pending

nft-studio/src/pages/Collection.tsx
This pull request adds the collection description in collection detail page, as per latest discussions and figma spec
Closes #640
=> Add collection description in collection detail page

nft-studio/src/pages/NFT.tsx
This pull request display NFT owner in the NFT page and replace the source link with a "Source file" label
Closes #650
=> Display nft owner and replace link with label

nft-studio/src/pages/Collections.tsx
This pull request displays All my NFT collection as first item in collections page
=> Display All my NFT collection as first item in collections page

nft-studio/src/components/CreateCollectionDialog.tsx, nft-studio/src/pages/MintNFT.tsx
Trim leading and trailing whitespace in name and description when creating collection or minting NFT.
NFT Studio
=> NFT Studio: Trim whitespace in name and description

.github/workflows/nft-studio-deploy-dev.yml, .github/workflows/nft-studio-deploy-prod.yml, .github/workflows/nft-studio-deploy-pull-request.yml, .github/workflows/nft-studio-deploy-staging.yml, nft-studio/.env.example, nft-studio/src/components/TransactionToasts.tsx, nft-studio/src/pages/NFT.tsx
This pull request applies style changes to NFT page
See https://centrifugehq.slack.com/archives/C02FXJ9TTBR/p1646765474218879
=> Style changes to nft page

nft-studio/src/components/CollectionCard.tsx, nft-studio/src/components/PageHeader.tsx, nft-studio/src/pages/AccountNFTs.tsx, nft-studio/src/pages/Collection.tsx, nft-studio/src/pages/Collections.tsx, nft-studio/src/utils/useIdentity.ts
Updates the collection card and includes the NFT count.
Closes #660
NFT Studio
=> NFT Studio: Updated collection card

.github/workflows/nft-studio-deploy-dev.yml, .github/workflows/nft-studio-deploy-pull-request.yml, .github/workflows/nft-studio-deploy-staging.yml, nft-studio/src/components/FileImageUpload.tsx, nft-studio/src/components/FileInput.tsx, nft-studio/src/components/FileInputOverlay.tsx, nft-studio/src/pages/MintNFT.tsx
- Implements style/ layout changes to the Mint NFT page
- Shows the supported file formats and file size limits
- Validates the file/shows the error message if the file is not supported
- Updates the subscan URL for DEV and staging environments
Closes #652, #657
=> Changes to the mint nft page

onboarding/api/src/services/templateTabs.test.ts, onboarding/api/src/services/templateTabs.ts
This pull request removes conditional logic that was preventing the residential country field from being prefilled in certain cases.
Onboarding API
=> fix: always include country

nft-studio/src/components/RemoveListingDialog.tsx, nft-studio/src/components/SellDialog.tsx
This pull request changes text in the NFT sale modals
Closes #687 , #689
=> chore(nft-studio): change modals text

nft-studio/src/pages/MintNFT.tsx
This pull request removes the "by" label in NFT Mint page
Closes #691
=> Remove by label in Mint NFT page

nft-studio/src/components/BuyDialog.tsx, nft-studio/src/components/CreateCollectionDialog.tsx, nft-studio/src/components/RemoveListingDialog.tsx, nft-studio/src/components/SellDialog.tsx, nft-studio/src/components/TransferDialog.tsx
This pull request closes modals when the transaction is pending (after signing)
=> Close dialogs when transaction is pending

.github/workflows/nft-studio-deploy-dev.yml, .github/workflows/nft-studio-deploy-prod.yml, .github/workflows/nft-studio-deploy-pull-request.yml, .github/workflows/nft-studio-deploy-staging.yml
This pull request switch to the dedicated pinata gateways provided by @offerijns 
See https://centrifugehq.slack.com/archives/C02R0G0Q0P5/p1647012489827779
=> Nft pinata dedicated gateway

nft-studio/src/components/Identity.tsx, nft-studio/src/pages/MintNFT.tsx, nft-studio/src/pages/NFT.tsx
This pull request adds the "back" buttons to Mint NFT and NFT pages
Closes #682
=> chore(nft-studio): add back buttons to NFT pages

fabric/src/components/Card/index.ts, nft-studio/src/components/FileImageUpload.tsx, nft-studio/src/components/PageHeader.tsx, nft-studio/src/components/SplitView.tsx, nft-studio/src/components/shared/PageWithSideBar.tsx, nft-studio/src/pages/MintNFT.tsx
This pull request applies some style amendments
Closes #719
=> Nft style amendments

gateway/Dockerfile, onboarding/api/src/utils/mailer.ts
This pull request updates the sender email while sending emails from sendgrid
=> Fix sendgrid sender email

fabric/src/components/Checkbox/index.tsx, nft-studio/src/components/CreateCollectionDialog.tsx
Add terms to Create Collection dialog
=> NFT playground: Add terms

.github/workflows/tinlake-ui-deploy-to-dev.yml
This pull request will point the tinlake-ui dev deployment to onboarding api staging environment
=> Point tinlake dev to onboard staging environment

onboarding/api/src/app.module.ts, onboarding/api/src/controllers/agreement.controller.ts, onboarding/api/src/services/mailer.service.ts, onboarding/api/src/services/pool.service.ts, package.json, yarn.lock
This pull request triggers subscription agreement email in both agreement callback and docusign connect webhook
=> Make mailer service injectible and trigger agreement email

.github/workflows/onboard-api.yml
=> Revert docker image tag

centrifuge-js/src/modules/pools.ts
Adds a function to CentJS that calculate how much a user can collect for a tranche.
CentrifugeJS
=> CentrifugeJS: Add getPendingCollect function

.github/workflows/nft-studio-deploy-prod.yml, .github/workflows/nft-studio-deploy-staging.yml
Adds the right endpoints for staging and production
NFT Playground
=> NFT Playground: Prod config

.github/workflows/tinlake-ui-deploy-to-dev.yml, .github/workflows/tinlake-ui-deploy-to-prod.yml, .github/workflows/tinlake-ui-deploy-to-staging.yml, .github/workflows/tinlake-ui-pull-request.yml, tinlake-ui/.env.mainnet-example, tinlake.js/src/actions/admin.ts
This pull request fixes an issue where the min/max TIN ratio was being updated through the assessor contract, while it should use the pool admin contract if possible.
=> fix: set min/max tin ratio using pool admin if available, and swap subgraph

gateway/Dockerfile
This pull request attempts to fix docker builds for Gateway
=> Attempt to fix docker build

gateway/packages/lib/src/centrifuge-node-client/api.ts, gateway/packages/ui/package.json, yarn.lock
This pull request fixes the fetch error generated by cent client
=> Add isomorphic-fetch to ui

gateway/packages/lib/src/centrifuge-node-client/api.ts, gateway/packages/server/src/documents/__tests__/documents.controller.spec.ts, gateway/packages/server/src/documents/documents.controller.ts, gateway/packages/ui/src/documents/CreateDocument.tsx, gateway/packages/ui/src/documents/EditDocument.tsx
This pull request fixes gateway 2.0 migration issues
=> Fix create document

gateway/packages/lib/src/centrifuge-node-client/api.ts, gateway/packages/server/src/documents/__tests__/documents.controller.spec.ts, gateway/packages/server/src/documents/documents.controller.ts, gateway/packages/server/src/nfts/nfts.controller.ts, gateway/packages/ui/src/documents/CreateDocument.tsx, gateway/packages/ui/src/documents/EditDocument.tsx
This pull request fixes nft minting on gateway
=> Fix gateway

gateway/packages/lib/src/centrifuge-node-client/api.ts, gateway/packages/server/src/nfts/nfts.controller.ts
This pull request fixes Oracle call parameters naming convention to snake case
=> Fix Oracle parameters in snake case

gateway/packages/lib/src/centrifuge-node-client/api.ts, gateway/packages/server/src/nfts/nfts.controller.ts
This pull request attempts to fix one last bug on receiving data from the node in snake case convention.
=> One more snake case fix

centrifuge-js/src/modules/pools.ts
Currently on main, when a new pool is created it is not yet indexed by subquery. Our query for `createdAt` is undefined in this case
=> Centrifuge App: Fix query on new pools

centrifuge-js/src/CentrifugeBase.ts, centrifuge-js/src/modules/pools.ts, fabric/src/components/Checkbox/index.tsx, fabric/src/components/InputBox/index.tsx, fabric/src/components/Tabs/index.tsx, fabric/src/components/TextInput/index.tsx, nft-studio/package.json, nft-studio/src/components/DataTable.tsx, nft-studio/src/components/DebugFlags/config.ts, nft-studio/src/components/Identity.tsx, nft-studio/src/components/NavigationTabs.tsx, nft-studio/src/pages/IssuerCreatePool/RiskGroupsInput.tsx, nft-studio/src/pages/IssuerPool/Configuration/Admins.tsx, nft-studio/src/pages/IssuerPool/Configuration/index.tsx, nft-studio/src/pages/IssuerPool/Header.tsx, nft-studio/src/pages/IssuerPool/index.tsx, nft-studio/src/utils/usePermissions.ts, nft-studio/src/utils/usePools.ts
Adds the Admin section to the Configuration page
Centrifuge App
=> Centrifuge App: Configure Admins

.github/workflows/centrifuge-app-deploy-demo.yml
Setup deployment of the App pointing to the demo environment.
=> Centrifuge App: Demo deployment

centrifuge-js/src/CentrifugeBase.ts, centrifuge-js/src/modules/pools.ts, centrifuge-js/src/utils/BN.ts, nft-studio/src/components/InvestRedeem.tsx, nft-studio/src/components/PoolList.tsx, nft-studio/src/pages/IssuerCreatePool/index.tsx, nft-studio/src/pages/IssuerCreatePool/pinPoolMetadata.ts, nft-studio/src/pages/IssuerCreatePool/validate.ts, nft-studio/src/pages/Pool.tsx, nft-studio/src/pages/Tokens.tsx, nft-studio/src/types/index.ts, nft-studio/src/utils/formatting.ts, nft-studio/src/utils/validation/index.ts, nft-studio/vite.config.ts
- Check whether write-off groups percentages and days are unique and ensure that there is at least one group with 100% write-off
- Allow pools to be create using the PermissionedEur currency
Centrifuge App, CentrifugeJS
=> Centrifuge App: Create pool changes

centrifuge-js/src/modules/pools.ts, nft-studio/src/components/DebugFlags/config.ts, nft-studio/src/components/InvestRedeem.tsx, nft-studio/src/components/TransactionsProvider.tsx, nft-studio/src/pages/IssuerCreatePool/index.tsx, nft-studio/src/pages/IssuerPool/Header.tsx, nft-studio/src/pages/IssuerPool/Investors/index.tsx, nft-studio/src/pages/IssuerPool/index.tsx, nft-studio/src/utils/formatting.ts, nft-studio/src/utils/useCentrifugeTransaction.ts
Adds the tab to the issuers page to add/remove investors to tranches
Also removes epoch time from pool creation
Centrifuge App
=> Centrifuge App: Issuer Investors Tab

.github/workflows/centrifuge-app-deploy-demo.yml, fabric/src/components/InteractiveCard/index.tsx, nft-studio/src/components/IssuerSection.tsx, nft-studio/src/components/PillButton.tsx, nft-studio/src/components/PoolCard.tsx, nft-studio/src/components/ReserveChart.tsx, nft-studio/src/components/Root.tsx, nft-studio/src/components/Tooltips.tsx, nft-studio/src/pages/PoolDetail/OverviewTab/index.tsx, nft-studio/src/pages/Token.tsx, nft-studio/src/utils/usePools.ts
Tickets:
#736 
#706 
#732
#771
=> Centrifuge App: Design Feedback for `/tokens`,  `/token/:tid` and  `pools/:pid`

nft-studio/src/components/DebugFlags/DebugFlags.tsx, nft-studio/src/components/DebugFlags/config.ts, nft-studio/src/components/DebugFlags/index.tsx, nft-studio/src/components/InvestRedeem.tsx, nft-studio/src/components/Menu.tsx, nft-studio/src/components/Root.tsx, nft-studio/src/pages/Loan/RiskGroupValues.tsx, nft-studio/src/pages/Loan/index.tsx, nft-studio/src/pages/Token.tsx
- Adds Invest card to Token detail
- Fixes Redeem not showing
- Add maturity date to loan pricing section
- Adds dark mode toggle to debug panel
Noticed a few issues with dark mode already, but leaving those for later
Centrifuge App
=> Centrifuge App: Fixes

nft-studio/src/components/LoanList.tsx, nft-studio/src/components/ReserveChart.tsx, nft-studio/src/pages/IssuerPool/Header.tsx, nft-studio/src/pages/PoolDetail/OverviewTab/index.tsx
This pull request... 
- fixes charts according to updated [design](https://www.figma.com/file/d1bEBkwllUQe27nQM6VlJu/Centrifuge-app---Version-1?node-id=4235%3A98485) 
- removes portfolio tab from issuer pools
- removes maturity column from asset when asset is unpriced and not borrow against (if I don't do this origination date is set to 1970 so we get obscure maturities)
Please note:
I wasn't able to use the font-variants that were requested (slashed zeros). Our font Inter doesn't support it.
You can test it on the[ google font page for Inter](https://fonts.google.com/specimen/Inter?preview.text=012344&preview.text_type=custom) by adding the following CSS to a test element
```css
font-variant-numeric: slashed-zero;
```
=> Centrifuge App: Update chart styles

centrifuge-js/src/modules/nfts.ts, centrifuge-js/src/modules/pools.ts, nft-studio/src/components/InvestRedeem.tsx, nft-studio/src/pages/IssuerPool/Investors/index.tsx, nft-studio/src/pages/Loan/FinanceForm.tsx
Fixes Redeem not showing and showing the wrong values.
Fixes Repay All tx showing as failed even though it succeeded
Centrifuge App
=> Centrifuge App: Bugfixes in Redeem and Repay flows

fabric/src/components/StatusChip/index.tsx, fabric/src/components/Thumbnail/index.tsx, fabric/src/theme/tokens/typography.ts, nft-studio/src/components/CollectionCard.tsx, nft-studio/src/components/ContextActions.tsx, nft-studio/src/components/DataTable.tsx, nft-studio/src/components/Dialogs/CreateCollectionDialog.tsx, nft-studio/src/components/Identity.tsx, nft-studio/src/components/InvestRedeem.tsx, nft-studio/src/components/LoanList.tsx, nft-studio/src/components/NFTCard.tsx, nft-studio/src/components/PageHeader.tsx, nft-studio/src/components/Root.tsx, nft-studio/src/pages/AccountNFTs.tsx, nft-studio/src/pages/Collection.tsx, nft-studio/src/pages/Collections.tsx, nft-studio/src/pages/CreateLoan.tsx, nft-studio/src/pages/IssuerCreatePool/index.tsx, nft-studio/src/pages/IssuerPool/Configuration/Admins.tsx, nft-studio/src/pages/Loan/FinanceForm.tsx, nft-studio/src/pages/Loan/PricingForm.tsx, nft-studio/src/pages/Loan/index.tsx, nft-studio/src/pages/MintNFT.tsx, nft-studio/src/pages/NFT.tsx, nft-studio/src/pages/PoolDetail/Header.tsx, nft-studio/src/pages/PoolDetail/OverviewTab/index.tsx, nft-studio/src/pages/Token.tsx, nft-studio/src/pages/Tokens.tsx, nft-studio/src/utils/formatting.ts, nft-studio/src/utils/useFocusInvalidInput.ts
Implement a bunch of design feedback. 
- Keep submit buttons enabled, even when there are errors. adds hook to focus invalid input upon submission
- Fix asset table overflow
- Add back buttons to page headers
- Change nft pages paths to make the Nfts menu item highlighted when on those pages
- Text tweaks
Centrifuge App
=> Centrifuge App: Design feedback

centrifuge-js/src/Centrifuge.ts, centrifuge-js/src/CentrifugeBase.ts, centrifuge-js/src/modules/nfts.ts, centrifuge-js/src/modules/pools.ts, centrifuge-js/src/modules/proxies.ts, centrifuge-js/src/modules/utils.ts, nft-studio/src/components/AccountsMenu.tsx, nft-studio/src/components/CentrifugeProvider.tsx, nft-studio/src/components/DebugFlags/config.ts, nft-studio/src/components/Identity.tsx, nft-studio/src/components/Root.tsx, nft-studio/src/components/Web3Provider.tsx, nft-studio/src/pages/CreateLoan.tsx, nft-studio/src/pages/IssuerPool/Configuration/Admins.tsx, nft-studio/src/pages/Loan/index.tsx, nft-studio/src/utils/useAddress.ts, nft-studio/src/utils/useBalances.ts, nft-studio/src/utils/useCentrifugeQuery.ts, nft-studio/src/utils/useCentrifugeTransaction.ts, nft-studio/src/utils/usePermissions.ts, nft-studio/src/utils/web3.ts
Adds proxy support to CentJS and the App
Centrifuge App, CentrifugeJS
=> Centrifuge App: Add proxy support

onboarding/api/src/services/mailer.service.ts
=> 784 onboarding emails voided declined

nft-studio/src/pages/Loan/FinanceForm.tsx
=> Centrifuge App: Fix Finance form

fabric/src/icon-svg/icon-pools.svg, nft-studio/src/components/Menu.tsx
This pull request re-adds the pool menu item.
=> Re-add pool menu

.eslintrc.js, fabric/src/components/Button/VisualButton.tsx, nft-studio/package.json, nft-studio/src/components/EpochList.tsx, nft-studio/src/components/InvestRedeem.tsx, nft-studio/src/components/InvestmentsList.tsx, nft-studio/src/components/TokenList.tsx, nft-studio/src/components/TokenListByPool.tsx, nft-studio/src/components/Web3Provider.tsx, nft-studio/src/pages/InvestmentsToken.tsx, nft-studio/src/pages/IssuerCreatePool/index.tsx, nft-studio/src/pages/IssuerCreatePool/pinPoolMetadata.ts, nft-studio/src/pages/IssuerPool/Configuration/PoolConfig.tsx, nft-studio/src/pages/IssuerPool/Investors/index.tsx, nft-studio/src/pages/Token.tsx, nft-studio/src/types/index.ts, nft-studio/vite.config.ts, yarn.lock
Saves tranche metadata by trancheId and updates the UI to expect it in that way (breaks tranche metadata for all pools until they are resaved). Also persists proxy address to localstorage.
Centrifuge App
=> Centrifuge App: Tranche metadata update

.github/workflows/altair-app-deploy-demo.yml, .github/workflows/altair-app-deploy-dev.yml, .github/workflows/centrifuge-app-deploy-demo.yml, .github/workflows/centrifuge-app-deploy-dev.yml
This pull request... adds distinct deployments for altair and centrifuge.
- https://dev.app.cntrfg.com/
- https://dev.app.altair.cntrfg.com/
- https://demo.app.cntrfg.com/
- https://demo.app.altair.cntrfg.com/
=> Centrifuge App: add altair deployments

centrifuge-js/src/modules/pools.ts, centrifuge-js/src/types/subquery.ts
This pull request updates the calls to the subquery.
=> Update subquery calls

centrifuge-app/src/utils/useCentrifugeTransaction.ts
=> Centrifuge App: Fix tx signing (Talisman and Polkadot.js)

centrifuge-app/src/pages/Loans.tsx, centrifuge-app/src/pages/PoolDetail/AssetsTab/index.tsx
Fixes two forgotten links after refactoring
@onnovisser feel free to go ahead and merge this when you see it 🙏
=> Centrifuge App: Fix broken links

tinlake-ui/package.json, tinlake-ui/services/centChain/index.ts, tinlake-ui/utils/cfgRewardProofs.ts, yarn.lock
- updates the `@polkadot/api` dependency to `^7.6.1`.
- uses `web3Enable`
- refactors `radClaims.accountBalances` to `claims.claimedAmounts`
- adds logic to dedupe the claim addresses
=> fix: claiming logic

centrifuge-app/src/components/Web3Provider.tsx, centrifuge-app/src/pages/IssuerPool/Investors/index.tsx
The wallet extensions appear sometimes not be ready immediately on page load, causing the wallet to appear to be disconnected. Now it'll try to reconnect a few times when the page loads.
Also blocks pooladmins from change investors.
=> Centrifuge App: Fix reconnecting wallet

centrifuge-app/src/components/Charts/PoolAssetReserveChart.tsx, centrifuge-app/src/components/DataTable.tsx, centrifuge-app/src/components/LoanList.tsx, centrifuge-app/src/components/RiskGroupList.tsx, centrifuge-app/src/pages/PoolDetail/Header.tsx, centrifuge-app/src/pages/Token.tsx
fixes some small bugs 🐛 
#783 
#831 
#885
=> Centrifuge App: Pool detail & pool overview bug fixes

centrifuge-app/src/components/Charts/PoolAssetReserveChart.tsx, centrifuge-app/src/components/Charts/ReserveCashDragChart.tsx, centrifuge-app/src/components/DataTable.tsx, centrifuge-app/src/components/InvestmentsList.tsx, centrifuge-app/src/components/LoanList.tsx, centrifuge-app/src/components/MenuSwitch.tsx, centrifuge-app/src/components/PoolList.tsx, centrifuge-app/src/components/RiskGroupList.tsx, centrifuge-app/src/components/TokenList.tsx, centrifuge-app/src/components/TokenListByPool.tsx, centrifuge-app/src/pages/Loans.tsx, centrifuge-app/src/pages/PoolDetail/AssetsTab/index.tsx, centrifuge-app/src/pages/Token.tsx, centrifuge-app/src/pages/Tokens.tsx, centrifuge-js/src/modules/pools.ts, fabric/src/components/Select/index.tsx, fabric/src/theme/tokens/modeDark.ts
- increases click radius on pool/token toggle
- fixes senior protection calculations
- #871 
- #885
- converts table row click to anchor 
- improves sorting in asset list
=> Centrifuge App: Altair bugs

centrifuge-app/src/pages/PoolDetail/AssetsTab/index.tsx, fabric/src/components/CurrencyInput/index.tsx
- fixes bug #895 
- fixes max input initial value
=> Centrifuge App: Fix initial currency input value

tinlake-ui/components/HelpMenu/index.tsx
Closes #854
N/A
Fixes 404 dead link
=> Fix bad documentation link

centrifuge-app/src/components/DataTable.tsx, centrifuge-app/src/components/GlobalStyle.tsx, centrifuge-app/src/components/MaxReserveForm.tsx, centrifuge-app/src/components/Menu.tsx, centrifuge-app/src/components/PageHeader.tsx, centrifuge-app/src/components/PageWithSideBar.tsx, centrifuge-app/src/components/TextWithPlaceholder.tsx, centrifuge-app/src/pages/IssuerCreatePool/WriteOffInput.tsx, centrifuge-app/src/pages/IssuerCreatePool/validate.ts, centrifuge-app/src/pages/IssuerPool/Investors/index.tsx, centrifuge-app/src/utils/validation/index.ts
=> Centrifuge App: Wording and layout improvements 

.github/workflows/nft-studio-deploy-dev.yml, .github/workflows/nft-studio-deploy-prod.yml, .github/workflows/nft-studio-deploy-pull-request.yml, .github/workflows/nft-studio-deploy-staging.yml, centrifuge-js/src/CentrifugeBase.ts, centrifuge-js/src/modules/nfts.ts, nft-studio/src/components/CollectionCard.tsx, nft-studio/src/pages/Collection.tsx
... updates centrifuge-js for nft-playground (not for centrifuge-app). This will allow a seamless transition when the altair chain get updates (class --> collection, instance --> item)
I've tested the PR deployments for pre and post spec version 1007 and it worked nicely.
URLs used pre 1007:
```
collator-wss-url: wss://fullnode-collator-2.development.cntrfg.com
relay-wss-url: wss://fullnode-relay-2.development.cntrfg.com
```
URLs used post 1007
```
collator-wss-url: wss://fullnode.altair-dev.cntrfg.com
relay-wss-url: wss://rococo-rpc.polkadot.io
```
ℹ️  we don't have a deployment setup for staging on netlify, I don't feel like it's necessary to set that up again. Once this PR is merged it should hopefully deploy to dev nicely. I've configured the dev deployment to use …
=> nft-studio: altair backward compatibility

.github/workflows/nft-studio-deploy-dev.yml
I forgot to point the dev workflow to the correct branch in my last PR. This should trigger the dev deployment when merged.
=> NFT-studio: fix dev deployment

centrifuge-app/src/components/DataTable.tsx, centrifuge-app/src/components/LoanList.tsx, centrifuge-app/src/components/RiskGroupList.tsx, centrifuge-app/src/components/TokenList.tsx, centrifuge-app/src/components/TokenListByPool.tsx, centrifuge-app/src/components/Tooltips.tsx, centrifuge-app/src/pages/IssuerCreatePool/WriteOffInput.tsx, centrifuge-app/src/pages/IssuerPool/Configuration/Admins.tsx, centrifuge-app/src/pages/IssuerPool/Investors/index.tsx, centrifuge-app/src/pages/Loan/FinanceForm.tsx, centrifuge-app/src/pages/Loan/index.tsx, centrifuge-app/src/pages/Token.tsx, tinlake-ui/components/HelpMenu/index.tsx
Tickets:
- #905 
- #902 
- #899 
- #901
- #886
=> Centrifuge-app: Altair tooltips and more

centrifuge-app/src/pages/Pools.tsx, centrifuge-app/src/pages/Tokens.tsx, centrifuge-js/src/modules/pools.ts
Fixes a bug where the pools query never resolves, when there are no pools.
CentrifugeJS
=> CentrifugeJS: Fix pools query not resolving when there are no pools

centrifuge-app/src/pages/Loan/FinanceForm.tsx, centrifuge-js/src/modules/pools.ts
Adds Close button to close loans whose maturity dates have passed without ever being financed (#903).
Centrifuge App, CentrifugeJS
=> Centrifuge App: Add Close loan button

centrifuge-app/src/pages/Loan/FinanceForm.tsx
Always shows the Close button on the Finance form when the loan is active.
Centrifuge App
=> Centrifuge App: Always show Close button on Finance form

centrifuge-app/src/components/Tooltips.tsx, centrifuge-app/src/components/TransactionToasts.tsx, centrifuge-app/src/pages/IssuerPool/Configuration/Admins.tsx, centrifuge-app/src/pages/Loan/PricingForm.tsx, centrifuge-js/src/modules/pools.ts
=> Centrifuge App: UI improvments and label updates

centrifuge-app/src/components/InvestRedeem.tsx, centrifuge-app/src/pages/PoolDetail/LiquidityTab/index.tsx, centrifuge-js/src/modules/pools.ts, fabric/src/components/Tooltip/index.tsx
Shows feedback when a pool is in a submission period and disallows orders during that time.
=> Centrifuge App: Disallow orders during submission period

.github/workflows/altair-app-deploy-prod.yml, .github/workflows/altair-app-deploy-staging.yml, .github/workflows/centrifuge-app-deploy-prod.yml, .github/workflows/centrifuge-app-deploy-staging.yml, centrifuge-app/README.md
sets up workflows and add documentation for:
1. altair staging [netlify](https://app.netlify.com/sites/staging-altair-app/overview)
2. altair prod [netlify](https://app.netlify.com/sites/nft-studio/overview)
3. centrifuge staging - not yet set up on netlify
4. centrifuge prod - not yet set up on netlify
Note: all deployments are still missing the subquery URL
=> Centrifuge App: Prepare prod and staging environments

centrifuge-js/src/modules/pools.ts
=> Centrifuge App: Fix pool proposal method

.github/workflows/altair-app-deploy-dev.yml, .github/workflows/altair-app-deploy-prod.yml, .github/workflows/altair-app-deploy-staging.yml, .github/workflows/centrifuge-app-deploy-dev.yml, centrifuge-app/src/components/Charts/PoolAssetReserveChart.tsx, centrifuge-app/src/components/Charts/ReserveCashDragChart.tsx, centrifuge-app/src/pages/Pool/Overview/index.tsx, centrifuge-js/src/CentrifugeBase.ts
=> Centrifuge App: Update subquery urls

centrifuge-app/src/components/Tooltips.tsx, centrifuge-app/src/utils/useTransactionFeeEstimate.ts, centrifuge-js/src/modules/pools.ts
This pull request... fixes bug with token price calculations (by using the price from the last epoch instead of the rpc method)
=> Centrifuge App: Fix token prices and update tooltip copy

.github/workflows/altair-app-deploy-demo.yml, .github/workflows/altair-app-deploy-dev.yml, .github/workflows/altair-app-deploy-prod.yml, .github/workflows/altair-app-deploy-staging.yml, .github/workflows/centrifuge-app-build-and-deploy.yml, .github/workflows/centrifuge-app-deploy-demo.yml, .github/workflows/centrifuge-app-deploy-dev.yml, .github/workflows/centrifuge-app-deploy-prod.yml, .github/workflows/centrifuge-app-deploy-pull-request.yml, .github/workflows/centrifuge-app-deploy-staging.yml, centrifuge-app/src/components/Dialogs/PreimageHashDialog.tsx, centrifuge-app/src/components/Menu.tsx, centrifuge-app/src/config.ts, centrifuge-app/src/pages/IssuerCreatePool/index.tsx, centrifuge-app/src/utils/useCentrifugeTransaction.ts, centrifuge-js/src/modules/pools.ts, centrifuge-js/src/types/index.ts
=> Centrifuge App: Add `notePreimage` option to create pool

centrifuge-app/src/components/DataTable.tsx
=> Centrifuge App: Fix hover on sortable table header

tinlake-ui/components/Loan/Data/index.tsx, tinlake-ui/components/Scorecard/index.tsx, tinlake-ui/containers/PoolManagement/Liquidity.tsx, tinlake-ui/containers/PoolManagement/Risk.tsx, tinlake-ui/public/static/tooltips.json, tinlake-ui/utils/useLoan.ts, tinlake.js/src/types/tinlake.ts
This pull request
- makes changes to the asset page
- removes the `Alert` for pools on the management page
[Preview link](https://pr-939--dev-tinlake.netlify.app/pool/0x4b6ca198d257d755a5275648d471fe09931b764a/fortunafi-1/assets/asset?assetId=3)
Closes #632 
Closes #924
=> chore: update asset ui page

centrifuge-app/src/components/InvestRedeem.tsx
This pull request... fixes redeeming
=> Centrifuge App: Fix redeeming

centrifuge-app/src/pages/Pool/Overview/index.tsx
Show invest card in sidebar even when not whitelisted as a placeholder until we have the onboarding stuff.
=> Centrifuge App: Show invest card when not whitelisted

tinlake-ui/.eslintrc.js, tinlake-ui/components/Footer/InvestmentDisclaimer.tsx, tinlake-ui/components/MintNFT/index.tsx, tinlake-ui/components/Onboarding/InfoBox.tsx, tinlake-ui/components/Onboarding/LinkStep.tsx, tinlake-ui/components/Overview/Archived.tsx, tinlake-ui/components/Overview/OverviewHeader.tsx, tinlake-ui/components/Overview/index.tsx, tinlake-ui/components/PoolList/index.tsx, tinlake-ui/components/Scorecard/index.tsx, tinlake-ui/components/ValueNFT/index.tsx, tinlake-ui/components/Web3Wallet/Toast.tsx, tinlake-ui/components/Web3Wallet/Web3Wallet.tsx, tinlake-ui/containers/PoolManagement/AdminLog.tsx, tinlake-ui/containers/PoolManagement/Memberlist.tsx, tinlake-ui/containers/PoolManagement/Risk.tsx
This pull request fixes typescript and linter config within `tinlake-ui`.
=> fix: typescript, linter

tinlake-ui/containers/PoolManagement/Liquidity.tsx
This pull request refactors the Locked Credit Line to the minimum of 1. Max Locked Credit Line given TIN and 2. Debt Ceiling - 100,000.
Closes #969
=> fix: calculate new debt ceiling max

centrifuge-app/src/components/InvestRedeem.tsx, centrifuge-app/src/pages/Pool/Assets/index.tsx, centrifuge-app/src/pages/Pool/Liquidity/index.tsx, centrifuge-app/src/pages/Pool/Overview/index.tsx, centrifuge-app/src/utils/useTransactionFeeEstimate.ts
Implement design feedback. Also fixes infinite loop in getting tx fee.
=> Centrifuge App: Invest tweaks

tinlake-ui/containers/SetCentAccount/index.tsx
This pull request adds a warning alert if the user's selected account balance is less than or equal to `0` when linking a wallet.
Closes #971 
**For account with balance above zero:**
**For account with balance zero or below:**
=> feat: add warning if cfg balance is zero

centrifuge-app/src/components/Dialogs/PreimageHashDialog.tsx, centrifuge-app/src/pages/IssuerCreatePool/index.tsx, centrifuge-js/src/modules/pools.ts
Quick fix to get the pool proposal past democracy, logs the metadata hash and write-off groups, for doing those transactions after proposal passes.
=> Centrifuge App: Fix pool proposal

centrifuge-app/src/components/TokenList.tsx
Fixes the sorting of the capacity column.
=> Centrifuge App: Fix tokens table

tinlake-ui/package.json, tinlake-ui/utils/cfgRewardProofs.ts, yarn.lock
This pull request adds `@polkadot-util@9.7.2` to `tinlake-ui` in order to support the older `bnToU8a` call signature.
=> fix: install @polkadot-util@9.7.2

centrifuge-app/src/components/Tooltips.tsx, centrifuge-app/src/pages/IssuerCreatePool/TrancheInput.tsx, centrifuge-app/src/pages/IssuerCreatePool/index.tsx, centrifuge-app/src/pages/IssuerCreatePool/validate.ts, centrifuge-app/src/pages/Pools.tsx
=> Centrifuge App: tranche symbol validation & investments subtitle

centrifuge-app/src/components/InvestRedeem.tsx, centrifuge-app/src/components/InvestmentsList.tsx, centrifuge-app/src/components/MaxReserveForm.tsx, centrifuge-app/src/components/RiskGroupList.tsx, centrifuge-app/src/pages/IssuerCreatePool/index.tsx, centrifuge-app/src/pages/IssuerCreatePool/pinPoolMetadata.ts, centrifuge-app/src/pages/IssuerPool/Investors/index.tsx, centrifuge-app/src/pages/Loan/FinanceForm.tsx, centrifuge-app/src/pages/Loan/PricingForm.tsx, centrifuge-app/src/utils/formatting.ts, centrifuge-app/src/utils/useCurrencies.ts, centrifuge-app/src/utils/usePools.ts, centrifuge-js/src/CentrifugeBase.ts, centrifuge-js/src/index.ts, centrifuge-js/src/modules/pools.ts, centrifuge-js/src/utils/BN.ts
Splits up Balance into TokenBalance and CurrencyBalance. CurrencyBalances can have varying amount of decimals.
CentrifugeJS, Centrifuge App
=> CentrifugeJS: Refactor balances

centrifuge-app/src/components/InvestRedeem.tsx, centrifuge-js/src/modules/pools.ts, centrifuge-js/src/utils/BN.ts
Give TokenBalance variable decimals
=> CentrifugeJS: TokenBalance with variable decimals

centrifuge-app/src/components/Dialogs/InvestmentDisclaimerDialog.tsx, centrifuge-app/src/components/Footer.tsx, centrifuge-app/src/components/PageWithSideBar.tsx, fabric/src/theme/tokens/typography.ts, fabric/src/theme/types.ts
=> Centrifuge App: Add footer links

tinlake-ui/components/Loan/Data/index.tsx, tinlake-ui/components/Loan/List/index.tsx, tinlake-ui/containers/Investment/View/InvestmentOverview.tsx, tinlake-ui/utils/export.ts, tinlake-ui/utils/useAssetListWriteOffStatus.ts, tinlake-ui/utils/useWriteOffPercentage.ts, tinlake.js/package.json, tinlake.js/src/actions/admin.ts
This pull request adds another cell to display the "Applied write-off" to the risk table when viewing an asset. If the write-off % is 100%, the status will display "repaid" instead of "ongoing".
Closes #960
=> feat: add write off info

.github/workflows/tinlake-ui-deploy-to-dev.yml, .github/workflows/tinlake-ui-deploy-to-prod.yml, .github/workflows/tinlake-ui-deploy-to-staging.yml, .github/workflows/tinlake-ui-pull-request.yml, tinlake-ui/utils/useWriteOffPercentage.ts
This pull request fixes ci caching. There is an issue when making a changes to one of the workspaces not breaking the cached modules potentially resulting in failed builds.
Used this to update the CI: https://stackoverflow.com/questions/64226272/caching-npm-dependency-with-github-action
=> fix: caching

.github/workflows/centrifuge-js-publish.yml, centrifuge-js/README.md, centrifuge-js/package.json
=> Centrifuge JS: Add action to deploy cent-js

.github/workflows/centrifuge-app-deploy-pull-request.yml, centrifuge-app/src/components/TokenList.tsx, centrifuge-app/src/pages/Tokens.tsx
=> CentrifugeApp: Update token list's protection

onboarding-ui/utils/useOnboardingState.ts
This pull request fixes the `placeholderPoolId` logic to work with kovan network as well.
=> fix: placeholder pool id logic

onboarding-ui/utils/useOnboardingState.ts
This pull request updates the placeholder pool id for Kovan network.
=> fix: placeholder kovan pool id

.github/workflows/centrifuge-js-publish.yml
This pull request... should fix centrifugeJS deployments
=> CentrifugeJS: Add registry url to deployment

onboarding/api/src/controllers/kyc.controller.ts
=> fix: redirect url

centrifuge-js/src/modules/pools.ts
=> CentrifugeApp: Fix `lastUpdated` query 

onboarding/api/src/controllers/kyc.controller.ts, onboarding/api/src/services/pool.service.ts
This pull request fixes the redirect urls in `onboarding-api` and also stops emails from sending when whitelisted since it is not functioning correctly.
=> fix: endpoints and email

gateway/packages/lib/src/centrifuge-node-client/api.ts, gateway/packages/lib/src/models/user.ts, gateway/packages/server/src/config.ts, gateway/packages/server/src/documents/__tests__/documents.controller.spec.ts, gateway/packages/server/src/users/__tests__/users.controller.spec.ts, gateway/packages/ui/src/test-utilities/default-data.ts
Issue leftover from migration to parachain
=> revert wrong case

centrifuge-app/src/components/RiskGroupList.tsx, centrifuge-app/src/pages/CreateLoanFromNFT.tsx
- #1020 
- fixes redirect after creating asset (altair)
=> Centrifuge App: Fix weighted riskAdjustment and financingFee

centrifuge-app/src/components/Charts/CustomChartElements.tsx, centrifuge-app/src/components/Charts/PoolAssetReserveChart.tsx, centrifuge-app/src/components/Charts/PriceYieldChart.tsx, centrifuge-app/src/components/Charts/ReserveCashDragChart.tsx, centrifuge-app/src/pages/Pool/Overview/index.tsx, centrifuge-app/src/utils/usePools.ts, centrifuge-js/src/modules/pools.ts, centrifuge-js/src/types/subquery.ts, fabric/src/components/InteractiveCard/index.tsx
=> Centrifuge App: Token price chart

onboarding-ui/components/Onboarding/KycStep.tsx
This pull request changes the accreditation link to use Securitize instead of InvestReady.
Closes #1026
=> fix: accreditation link

centrifuge-app/src/components/Charts/PriceYieldChart.tsx, centrifuge-app/src/pages/Pool/Liquidity/index.tsx, centrifuge-app/src/pages/Pool/Overview/index.tsx
- #1028 
Also improves loading state of charts to prevent CLS (cumulative layout shift)
=> Centrifuge App: Update range on price chart

centrifuge-app/src/config.ts, centrifuge-app/src/pages/IssuerCreatePool/index.tsx, centrifuge-app/src/pages/IssuerCreatePool/validate.ts, centrifuge-app/src/pages/IssuerPool/Assets/CreateLoan.tsx, centrifuge-app/src/pages/IssuerPool/Configuration/Details.tsx, centrifuge-app/src/pages/Loan/index.tsx, centrifuge-app/src/utils/useCentrifugeTransaction.ts
Fixes adding monetary values when creating documents and fixes displaying them. Also makes POD endpoint optional and adds error handling for when creating the document fails.
=> Centrifuge App: Fix monetary values in Create Asset flow

centrifuge-app/src/components/DemoBanner.tsx, centrifuge-app/src/components/Root.tsx, fabric/src/components/Banner/index.tsx, fabric/src/index.ts
=> CentrifugeApp: Demo environment banner

fabric/src/components/Banner/index.tsx
=> CentrifugeApp: Fix types and builds

centrifuge-js/README.md
=> CentrifugeJS: Create a pool & Usage documentation

centrifuge-app/src/pages/Pools.tsx, centrifuge-app/src/pages/Tokens.tsx
Hides unlisted pool and their tokens from the Pools/Tokens pages
=> Centrifuge App: Hide unlisted pools

centrifuge-js/package.json, centrifuge-js/src/modules/pools.ts
=> CentrifugeJS: release v0.2.0

centrifuge-app/src/components/DemoBanner.tsx, fabric/src/components/Banner/index.tsx
=> CentrifugeApp: Persist demo banner and update copy

.github/workflows/onboarding-app-deploy-to-dev.yml, .github/workflows/onboarding-app-deploy-to-prod.yml, .github/workflows/onboarding-app-deploy-to-staging.yml, .github/workflows/onboarding-app-pull-request.yml, .github/workflows/tinlake-ui-deploy-to-dev.yml, .github/workflows/tinlake-ui-deploy-to-prod.yml, .github/workflows/tinlake-ui-deploy-to-staging.yml, .github/workflows/tinlake-ui-pull-request.yml, onboarding-ui/config.ts, package.json, tinlake-ui/.env.mainnet-example, tinlake-ui/package.json
This pull request reinstates the subgraph url fix, fix port number, fleshes out start script.
=> fix: port, script, subgraph

faucet-api/src/index.ts
=> CentrifugeApp: Improve faucet cors handling

centrifuge-app/src/pages/Pools.tsx, centrifuge-app/src/utils/usePools.ts, centrifuge-js/src/modules/pools.ts
This pull request updates centrifuge.js to account for the latest centrifuge-chain changes, notably the pool-registry pallet.
=> Update centrifuge.js for latest chain upgrades

centrifuge-app/src/utils/useMetadata.ts, centrifuge-js/src/modules/pools.ts, centrifuge-react/package.json
=> CentrifugeJS: Fix pool events

centrifuge-js/package.json
=> CentrifugeJS: Bump version

centrifuge-js/src/modules/pools.ts
=> Centrifuge App: Switch interest rate APR percent to percent

centrifuge-js/src/modules/pools.ts
=> CentrifugeJS: Round rate to 4 decimals when pricing loans

centrifuge-app/src/components/Charts/PoolAssetReserveChart.tsx, centrifuge-app/src/components/Charts/PriceYieldChart.tsx, centrifuge-app/src/components/Charts/ReserveCashDragChart.tsx, centrifuge-app/src/pages/Pool/Overview/index.tsx, centrifuge-js/src/modules/pools.ts, centrifuge-js/src/types/subquery.ts, fabric/src/components/InteractiveCard/index.tsx
=> CentrifugeJS: Fix subquery naming bug

centrifuge-app/src/components/AuthProvider.tsx, centrifuge-app/src/components/Web3Provider.tsx, centrifuge-app/src/pages/Onboarding/LinkWallet.tsx, centrifuge-app/src/pages/Onboarding/index.tsx, centrifuge-app/src/utils/formatting.ts
This pull request integrates authentication and proxy authorization into the new onboarding flow.
=> integrate auth

.github/workflows/root.yml
This pull request fixes the versions of the CI config for the `root` job.
=> change versions

onboarding-api/README.md, onboarding-api/src/controllers/businessVerification.ts, onboarding-api/src/controllers/businessVerificationConfirm.ts, onboarding-api/src/database/index.ts
=> Onboarding: Add dateOfBrith to UBO in business verification

centrifuge-app/src/pages/Onboarding/BusinessInformation.tsx, centrifuge-app/src/pages/Onboarding/BusinessOwnership.tsx, centrifuge-app/src/pages/Onboarding/InvestorType.tsx, centrifuge-app/src/pages/Onboarding/LinkWallet.tsx, centrifuge-app/src/pages/Onboarding/index.tsx, fabric/src/components/Stepper/Stepper.stories.tsx, fabric/src/components/Stepper/index.tsx, onboarding-api/src/index.ts
This pull request refactors the linking wallet step for onboarding and also removes unnecessary buttons to navigate through the flow.
=> refactor link wallet ui

yarn.lock
Centrifuge App dev server wasn't working because of package changes in a recent commit
=> Fix packages

centrifuge-app/src/components/DebugFlags/context.ts, centrifuge-app/src/pages/Onboarding/BusinessOwnership.tsx, centrifuge-app/src/pages/Onboarding/KnowYourCustomer/AuthorizedSignerVerification.tsx, centrifuge-app/src/pages/Onboarding/KnowYourCustomer/CountryOfIssuance.tsx, centrifuge-app/src/pages/Onboarding/KnowYourCustomer/LivelinessCheck.tsx, centrifuge-app/src/pages/Onboarding/KnowYourCustomer/PhotoID.tsx, centrifuge-app/src/pages/Onboarding/KnowYourCustomer/index.tsx, centrifuge-app/src/pages/Onboarding/index.tsx, fabric/src/components/Stepper/index.tsx
This pull request implements the basic KYC components of the onboarding flow including placeholders for the ShuftiPro iframes.
=> skeleton for know your customer screens

centrifuge-app/README.md, centrifuge-app/netlify.toml, centrifuge-app/vite.config.ts
=> Centrifuge App: Fix dev server

fabric/src/components/TextInput/index.tsx
Textarea resize thumb was hidden and it was difficult to resize the input.
To review: Create new pool has a textarea
=> Unhide the resize thumb

centrifuge-app/src/pages/IssuerCreatePool/index.tsx, centrifuge-app/src/pages/IssuerCreatePool/useStoredIssuer.ts, centrifuge-app/src/pages/IssuerPool/Configuration/Details.tsx, centrifuge-js/src/modules/metadata.ts, centrifuge-js/src/modules/pools.ts, fabric/src/components/Tooltip/index.tsx
Fixed a couple of bugs on the Create Pool page
- Fixes converting pool metadata to base64, could fail when using special characters
- Fixes the redirect after creating a pool
- Fixes the issuer name and description fields being greyed out even though it looks like it finished loading stored values for the same address
- Fixes tooltip underline, when the text spans multiple lines
#1109
=> Centrifuge App: Fix create pool

centrifuge-app/.gitignore
=> Ignores centrifuge-app functions folder

centrifuge-app/src/utils/formatting.ts
=> Centrifuge App: Fix Borrowed/Repaid formatting

onboarding-api/src/controllers/kyb/confirmOwners.ts, onboarding-api/src/controllers/kyb/verifyBusiness.ts, onboarding-api/src/controllers/user/getUser.ts, onboarding-api/src/database/index.ts, onboarding-api/src/index.ts
=> OnboardingAPI: Split users into entities and individuals

onboarding-api/src/controllers/user/getUser.ts, onboarding-api/src/index.ts
=> OnboardingAPI: Convert getUser to use GET

centrifuge-app/src/components/DemoBanner.tsx, fabric/src/components/Banner/index.tsx
- uses local storage to save seen state
- adds underline to anchor
- adds inline padding to fabric Banner
=> DemoBanner seen state

.github/workflows/altair-app-deploy-prod.yml
This pull request adds a `onboarding-api-url` property to the `Altair app PROD` workflow.
=> add onboarding-api-url property to workflow

.github/workflows/centrifuge-app-deploy-pull-request.yml, onboarding-api/package.json, onboarding-api/src/controllers/kyb/confirmOwners.ts, onboarding-api/src/controllers/kyb/verifyBusiness.ts, onboarding-api/src/database/index.ts, onboarding-api/src/index.ts
=> OnboardingAPI: Update data shape

centrifuge-app/src/pages/IssuerCreatePool/index.tsx, centrifuge-app/src/pages/Onboarding/BusinessOwnership.tsx, centrifuge-app/src/pages/Onboarding/KnowYourCustomer/AuthorizedSignerVerification.tsx, centrifuge-app/src/pages/Onboarding/KnowYourCustomer/IdentityVerification.tsx, centrifuge-app/src/pages/Onboarding/KnowYourCustomer/index.tsx, centrifuge-app/src/pages/Onboarding/index.tsx
This pull request integrates the ShuftiPro `iframe`s.
Closes #1131
=> integrate shuftipro into onboarding UI

.github/workflows/centrifuge-app-deploy-demo.yml, .github/workflows/centrifuge-app-deploy-dev.yml, .github/workflows/centrifuge-app-deploy-staging.yml
This pull request updates the `onboarding-api-url` in the various Github actions to the newly updated url.
=> update onboarding api urls

centrifuge-app/src/components/Tooltips.tsx, centrifuge-app/src/pages/IssuerCreatePool/TrancheInput.tsx
Adds tooltips to <TranchInput>
=> adds ToolTips to TranchInput

centrifuge-app/src/pages/Onboarding/BusinessInformation.tsx, onboarding-api/README.md, onboarding-api/package.json, onboarding-api/src/controllers/kyb/confirmOwners.ts, onboarding-api/src/controllers/kyb/verifyBusiness.ts, onboarding-api/src/controllers/user/getUser.ts, onboarding-api/src/controllers/user/setVerifiedIdentity.ts, onboarding-api/src/controllers/user/startKyc.ts, onboarding-api/src/database/index.ts, onboarding-api/src/index.ts, onboarding-api/src/middleware/cors.ts, onboarding-api/src/utils/shuftiProRequest.ts, yarn.lock
=> OnboardingAPI: Add start kyc endpoint

centrifuge-app/index.html
=> updates site meta description

.github/workflows/centrifuge-app-deploy-dev.yml, .github/workflows/centrifuge-app-deploy-pull-request.yml, yarn.lock
=> Centrifuge App: Update Subquery url

.github/workflows/onboarding-api.yml, onboarding-api/package.json, onboarding-api/src/controllers/user/getUser.ts, onboarding-api/src/middleware/verifyJw3t.ts, onboarding-api/src/utils/centrifuge.ts, yarn.lock
- installs centrifuge-js (bundle is huge now...)
- checks incoming requests for proxies
- throws error from `getUser` endpoint if no user is found
=> OnboardingAPI: verify proxied accounts

centrifuge-app/src/utils/getActiveOnboardingStep.ts, centrifuge-app/src/utils/useOnboardingStep.ts
This pull request fixes an issue with the onboarding auth logic.
=> fix onboarding auth logic

centrifuge-app/src/components/Dialogs/ConfirmResendEmailVerificationDialog.tsx, centrifuge-app/src/components/Dialogs/DataSharingAgreementDialog.tsx, centrifuge-app/src/components/Dialogs/EditOnboardingEmailAddressDialog.tsx, centrifuge-app/src/pages/Onboarding/BusinessInformation.tsx, centrifuge-app/src/pages/Onboarding/BusinessOwnership.tsx, centrifuge-app/src/pages/Onboarding/KnowYourCustomer/index.tsx, centrifuge-app/src/pages/Onboarding/LinkWallet.tsx, centrifuge-app/src/pages/Onboarding/StyledInlineFeedback.tsx
This pull request adds ui logic for confirming email address.
Closes #1094
=> add onboarding ui email verification

centrifuge-app/src/components/InvestRedeem.tsx, centrifuge-app/src/pages/CreateLoanFromNFT.tsx, centrifuge-app/src/pages/IssuerCreatePool/index.tsx, centrifuge-app/src/pages/IssuerPool/Assets/CreateLoan.tsx, centrifuge-app/src/pages/IssuerPool/Configuration/Details.tsx, centrifuge-app/src/pages/Loan/PricingForm.tsx, centrifuge-app/src/pages/Onboarding/BusinessInformation.tsx, centrifuge-app/src/pages/Onboarding/KnowYourCustomer/AuthorizedSignerVerification.tsx, centrifuge-app/src/pages/Pool/Reporting/index.tsx, fabric/src/components/Select/index.tsx
Refactor fabric `<Select/>` to use native `<select>`
=> Refactor to use native Select

centrifuge-app/src/pages/Onboarding/BusinessOwnership.tsx, centrifuge-app/src/pages/Onboarding/KnowYourCustomer/index.tsx, centrifuge-app/src/pages/Onboarding/TaxInfo.tsx, onboarding-api/src/controllers/user/startKyc.ts
This pull request includes a few fixes and quality of life upgrades.
=> refetch user on focus

centrifuge-react/src/hooks/useCentrifugeQuery.ts
=> Centrifuge App: Fix useCentrifugeQuery not returning new data

centrifuge-app/src/components/Dialogs/ExecutiveSummaryDialog.tsx, centrifuge-app/src/components/Root.tsx, centrifuge-app/src/pages/InvestmentDisclaimer.tsx, onboarding-api/src/controllers/agreement/signAgreement.ts, onboarding-api/src/controllers/emails/sendVerifyEmail.ts, onboarding-api/src/controllers/emails/verifyEmail.ts, onboarding-api/src/controllers/kyb/confirmOwners.ts, onboarding-api/src/controllers/kyb/verifyBusiness.ts, onboarding-api/src/controllers/user/getTaxInfo.ts, onboarding-api/src/controllers/user/getUser.ts, onboarding-api/src/controllers/user/setVerifiedIdentity.ts, onboarding-api/src/controllers/user/startKyc.ts, onboarding-api/src/controllers/user/uploadTaxInfo.ts, onboarding-api/src/controllers/user/verifyAccreditation.ts, onboarding-api/src/emails/index.ts, onboarding-api/src/emails/sendVerifyEmailMessage.ts, onboarding-api/src/utils/fetchUser.ts, onboarding-api/src/utils/verifyJwt.ts
- adds disclaimer page to link from email
- creates helper for fetching user and error handling
- unifies error handling
- general clean up
=> OnboardingAPI: Email verify clean up and controller refactor

fabric/src/components/Select/index.tsx
=> fix disabled state

centrifuge-app/src/pages/Pool/Overview/index.tsx
https://app.zenhub.com/workspaces/centrifuge-applications-5fa29e924059e5001625e2a3/issues/gh/centrifuge/apps/1117
=> adds link to account on subscan

centrifuge-app/src/components/Head.tsx
=> slash prefixed path according to vite docs

onboarding-api/package.json, onboarding-api/src/controllers/user/updateInvestorStatus.ts, onboarding-api/src/emails/index.ts, onboarding-api/src/emails/sendApproveInvestorMessage.ts, onboarding-api/src/emails/sendRejectInvestorMessage.ts, onboarding-api/src/utils/getPoolById.ts, yarn.lock
=> OnboardingAPI: Send investor approval/rejection emails

centrifuge-app/src/components/OnboardingProvider.tsx, centrifuge-app/src/pages/Onboarding/ApprovalStatus.tsx, centrifuge-app/src/pages/Onboarding/InvestorType.tsx
This pull request addresses the issue where the dev chain was reset. It hardcodes metadata.
=> fix: hardcode pool data

centrifuge-js/src/modules/pools.ts
=> CentrifugeJS: Fix rates

centrifuge-app/src/pages/IssuerPool/Investors/index.tsx
https://app.zenhub.com/workspaces/centrifuge-applications-5fa29e924059e5001625e2a3/issues/gh/centrifuge/apps/1185
=> Updates wording

onboarding-api/src/utils/fetchUser.ts
=> OnboardingAPI: Add firestore error log

pinning-api/src/controllers/pinFile.ts, pinning-api/src/controllers/pinJson.ts, pinning-api/src/utils/api.ts
=> PinningApi: Fix data from axios response

centrifuge-app/src/components/OnboardingProvider.tsx, centrifuge-app/src/pages/Onboarding/EmailVerified.tsx, centrifuge-app/src/pages/Onboarding/UpdateInvestorStatus.tsx, centrifuge-app/src/pages/Onboarding/index.tsx, onboarding-api/src/controllers/user/updateInvestorStatus.ts
This pull request implements some minor improvements to the onboarding ui.
=> implement minor onboarding ui improvements

centrifuge-app/src/components/OnboardingProvider.tsx, centrifuge-app/src/pages/Onboarding/Accreditation.tsx, centrifuge-app/src/pages/Onboarding/BusinessInformation.tsx, centrifuge-app/src/pages/Onboarding/BusinessOwnership.tsx, centrifuge-app/src/pages/Onboarding/EmailVerified.tsx, centrifuge-app/src/pages/Onboarding/KnowYourCustomer/SignerVerification.tsx, centrifuge-app/src/pages/Onboarding/KnowYourCustomer/index.tsx, centrifuge-app/src/pages/Onboarding/LinkWallet.tsx, centrifuge-app/src/pages/Onboarding/SignSubscriptionAgreement.tsx, centrifuge-app/src/pages/Onboarding/UpdateInvestorStatus.tsx, centrifuge-app/src/pages/Onboarding/geographyCodes.ts, centrifuge-app/src/pages/Onboarding/index.tsx, centrifuge-app/src/pages/Onboarding/queries/useStartKYC.ts, centrifuge-app/src/types/index.ts, onboarding-api/src/controllers/kyb/confirmOwners.ts, onboarding-api/src/controllers/kyb/verifyBusiness.ts, onboarding-api/src/controllers/user/startKyc.ts, onboarding-api/src/controllers/user/updateInvestorStatus.ts, onboarding-api/src/database/index.ts
- adds two more form fields to the `BusinessOwnership` component
- refactors the UI of the `BusinessOwnership` component
- adds support to the backend for the two new UBO fields
- adds `paddingLeft` and `pointer` for all checkboxes
- uses `Residency` instead of `Residence`
New Business Ownership UI
=> refactor ubos

.github/actions/prepare-deploy/action.yml
Quick fix on the logic that would make demo deployments point to DEV instead (demo is not being updated).
=> Patch GHA deploy to demo logic

onboarding-api/env-vars/altair.env, onboarding-api/env-vars/catalyst.env, onboarding-api/env-vars/demo.env, onboarding-api/env-vars/development.env, onboarding-api/env-vars/production.env
This pull request fixes the redirect urls. Without the `scheme`, the verify email button in the verification email does not work. There was also an incorrect trailing `s` on `app`.
=> fix: redirect urls

centrifuge-js/package.json, centrifuge-js/src/modules/auth.ts
=> CentrifugeJS: Make jw3t work with KeyringPair

fabric/src/components/InputBox/index.tsx, fabric/src/components/Select/index.tsx
=> enable click on chevron

onboarding-api/src/database/index.ts
This pull request renames the onboarding bucket.
=> fix: rename onboarding bucket

centrifuge-app/src/pages/Pool/Overview/index.tsx
This pull request triggers the wallet connect dialog when a user clicks `Invest` on a token when not connected.
=> fix: trigger wallet connect

centrifuge-js/src/modules/pools.ts
Fixes event names so getPools doesn't refetch every block.
=> CentrifugeJS: Fix getPools

centrifuge-app/src/components/ConnectToast.tsx, centrifuge-app/src/components/Onboarding/Container.tsx, centrifuge-app/src/components/ValidationToast.tsx, centrifuge-app/src/pages/Onboarding/Accreditation.tsx, centrifuge-app/src/pages/Onboarding/BusinessInformation.tsx, centrifuge-app/src/pages/Onboarding/BusinessOwnership.tsx, centrifuge-app/src/pages/Onboarding/InvestorType.tsx, centrifuge-app/src/pages/Onboarding/KnowYourCustomer/SignerVerification.tsx, centrifuge-app/src/pages/Onboarding/KnowYourCustomer/index.tsx, centrifuge-app/src/pages/Onboarding/LinkWallet.tsx, centrifuge-app/src/pages/Onboarding/SignSubscriptionAgreement.tsx, centrifuge-app/src/pages/Onboarding/TaxInfo.tsx, centrifuge-app/src/pages/Onboarding/queries/useUploadTaxInfo.ts
This pull request implements UI form validation to onboarding.
=> implement form validation for onboarding pages

onboarding-api/src/controllers/user/startKyc.ts
This pull request fixes the individual flow.
=> fix: individual flow

centrifuge-app/src/components/LoanList.tsx, centrifuge-app/src/components/Menu.tsx, centrifuge-app/src/components/MenuSwitch.tsx, centrifuge-app/src/components/PoolCard.tsx, centrifuge-app/src/components/Root.tsx, centrifuge-app/src/components/TokenList.tsx, centrifuge-app/src/pages/InvestmentDisclaimer.tsx, centrifuge-app/src/pages/IssuerPool/Header.tsx, centrifuge-app/src/pages/Loan/index.tsx, centrifuge-app/src/pages/Onboarding/ApprovalStatus.tsx, centrifuge-app/src/pages/Pool/Header.tsx, onboarding-api/src/emails/sendApproveInvestorMessage.ts
renames 'investments' to 'pools'
=> renames 'investments' to 'pools'

centrifuge-app/src/pages/Onboarding/InvestorType.tsx, centrifuge-app/src/pages/Onboarding/UltimateBeneficialOwners.tsx, centrifuge-app/src/pages/Onboarding/index.tsx, centrifuge-app/src/pages/Onboarding/queries/useConfirmUltimateBeneficialOwners.ts, centrifuge-app/src/utils/getActiveOnboardingStep.ts
- removes the hover background color, and adds a `not-allowed` cursor for the investor type step when completed
- renames all use of "business owners" to "ultimate beneficial owners"
- fixes active step logic
=> onboarding ui tweaks

centrifuge-app/src/components/InvestRedeem/InvestRedeem.tsx, centrifuge-app/src/components/InvestRedeem/InvestRedeemTinlakeProvider.tsx, centrifuge-app/src/config.ts
Fix Tinlake invest data to account for empty data when an address isn't provided
=> Centrifuge App: Fix Tinlake invest card

centrifuge-app/src/components/DebugFlags/config.ts, centrifuge-app/src/utils/tinlake/useTinlakePools.ts, centrifuge-app/src/utils/useListedPools.ts
Always showing Tinlake pools now
=> Centrifuge App: Remove Tinlake pools flag

centrifuge-js/src/modules/proxies.ts, centrifuge-js/src/utils/index.ts, centrifuge-react/src/components/WalletProvider/WalletProvider.tsx
Gets proxies directly from the chain instead of the SubQuery
=> Centrifuge App: Get proxies directly from chain

centrifuge-app/src/components/Onboarding/ChoosePool.tsx, centrifuge-app/src/components/OnboardingProvider.tsx, centrifuge-app/src/pages/Onboarding/GlobalStatus.tsx, centrifuge-app/src/pages/Onboarding/InvestorType.tsx, centrifuge-app/src/pages/Onboarding/KnowYourCustomer/SignerVerification.tsx, centrifuge-app/src/pages/Onboarding/KnowYourCustomer/index.tsx, centrifuge-app/src/pages/Onboarding/TaxInfo.tsx, centrifuge-app/src/pages/Onboarding/UltimateBeneficialOwners.tsx, centrifuge-app/src/pages/Onboarding/index.tsx, centrifuge-app/src/pages/Onboarding/queries/useStartKYC.ts, centrifuge-app/src/pages/Onboarding/queries/useVerifyBusiness.ts, centrifuge-app/src/types/index.ts, onboarding-api/src/controllers/emails/verifyEmail.ts, onboarding-api/src/controllers/user/setVerifiedIdentity.ts, onboarding-api/src/controllers/user/startKyc.ts
- adds support for email verification within the `Individual` onboarding flow
- adds better support for global onboarding
Closes #1259
=> add support for individual email verification

onboarding-api/src/controllers/auth/authenticateWallet.ts
=> OnboardingAPI: Fix cookie clearing on successful authentication

centrifuge-app/package.json, onboarding-api/package.json, yarn.lock
This pull request updates the `jw3t` library which was updated to include a [commit](https://github.com/hamidra/jw3t/commit/6fc1449c4de412b3935b9fc0f6f636ced712ae94) that removes a noisy `console.log`.
=> update jw3t library

centrifuge-app/src/pages/Onboarding/UpdateInvestorStatus.tsx, centrifuge-app/src/pages/Onboarding/queries/useStartKYC.ts, centrifuge-app/src/pages/Onboarding/queries/useUpdateInvestorStatus.ts, centrifuge-app/src/pages/Onboarding/queries/useVerifyBusiness.ts, onboarding-api/README.md, onboarding-api/env-vars/development.env, onboarding-api/src/controllers/kyb/verifyBusiness.ts, onboarding-api/src/controllers/user/startKyc.ts, onboarding-api/src/controllers/user/updateInvestorStatus.ts, onboarding-api/src/emails/sendDocumentsMessage.ts, onboarding-api/src/utils/centrifuge.ts
- updates memeberlist proxy address (since chain reset)
- removes poolId and trancheId from all global steps
- adds pool name on approving/rejecting investor (issuer view)
- improves documentation and adds link to postman collection
=> OnboardingAPI: Improved documentation

centrifuge-app/src/pages/Onboarding/SignSubscriptionAgreement.tsx
- enable the user to download the subscription agreement and review it in detail
Ticket: https://github.com/centrifuge/apps/issues/1281
=> Download subscription agreement as pdf

centrifuge-app/src/pages/Pool/Liquidity/index.tsx
Order overview should be last section within the view
Ticket: https://github.com/centrifuge/apps/issues/1270
=> Section order Liquidity view

centrifuge-app/src/components/EpochList.tsx, centrifuge-app/src/components/LiquidityEpochSection.tsx
This pull request... disables the solver until the solution formula is fixed.
=> CentrifugeApp: Disable-solver

onboarding-api/src/middleware/cors.ts
This pull request strengthens the CORS logic for determining is an origin should be allowed.
=> fix: make cors domains regexs stronger

.github/workflows/centrifuge-app.yml, .github/workflows/faucet-api.yml, .github/workflows/onboarding-api.yml, .github/workflows/pinning-api.yml
Small fix to make sure functions and buckets are deployed on changes to the .github/actions libraries.
=> Add triggers on .github/actions changes

onboarding-api/src/controllers/emails/verifyEmail.ts
This pull request enforces that when a user is verifying their email address, the email address in the database should match the email address in the jwt.
=> check for matching email address

centrifuge-app/src/components/Menu/GovernanceMenu.tsx, centrifuge-app/src/components/Menu/IssuerMenu.tsx, centrifuge-app/src/components/Menu/Toggle.tsx, centrifuge-app/src/components/Menu/index.tsx, centrifuge-app/src/components/Menu/styles.ts, fabric/src/icon-svg/icon-governance.svg
Issue: https://github.com/centrifuge/apps/issues/1345
=> Adds Governance entry to Menu

onboarding-api/src/middleware/cors.ts
This pull request ensures that a request to the `onboarding-api` only has a single origin.
=> fix: ensure single origin

centrifuge-app/.env-config/.env.altair, onboarding-api/env-vars/altair.env, onboarding-api/env-vars/catalyst.env, onboarding-api/env-vars/demo.env, onboarding-api/env-vars/development.env, onboarding-api/env-vars/production.env, onboarding-api/src/database/index.ts, onboarding-api/src/utils/types.d.ts
=> CentrifugeApp: point altair to goerli and use env variables for buckets

.github/workflows/prod-deploy.yml
One character typo on the GHA sync between staging and prod
=> Fix small typo on Staging bucket

onboarding-api/env-vars/altair.secrets
=> Onboarding: Update Altair secrets

centrifuge-app/src/pages/Onboarding/KnowYourCustomer/index.tsx
This pull request fixes the issue where a user still proceeds in the onboarding flow even when their KYC submission was denied.
The user will see this screen and will no longer be advanced to the next step:
=> fix: kyc decline

onboarding-api/src/index.ts, onboarding-api/src/middleware/restrictedPool.ts, onboarding-api/src/utils/isRestrictedPool.ts
This pull request restricts a user from onboarding with a restricted pool id.
=> chore: add middleware for restricted pools

centrifuge-app/src/components/OnboardingAuthProvider.tsx, centrifuge-app/src/pages/Onboarding/LinkWallet.tsx, onboarding-api/src/controllers/user/startKyc.ts, onboarding-api/src/utils/envCheck.ts, onboarding-api/src/utils/shuftiProRequest.ts, onboarding-api/src/utils/types.d.ts
=> Onboarding: Improved loading state and dev env check

centrifuge-app/src/pages/Onboarding/UpdateInvestorStatus.tsx, onboarding-api/src/controllers/user/startKyc.ts
=> Onboarding: Fix blockexplorer link after whitelisting

centrifuge-app/src/components/MaxReserveForm.tsx
=> Allow zero as max reserve

centrifuge-app/src/components/InvestRedeem/InvestRedeem.tsx
=> Centrifuge App: Combine approve and invest

centrifuge-app/src/components/Menu/GovernanceMenu.tsx
Subtask of: https://github.com/centrifuge/apps/issues/1386
=> align icons in governance menu

centrifuge-app/src/pages/Tokens.tsx
Subtask of: https://github.com/centrifuge/apps/issues/1386
=> Display 'Tokens' on tokens overview page

centrifuge-app/src/components/Footer.tsx
Subtask of: https://github.com/centrifuge/apps/issues/1386
=> Adds support link to footer

centrifuge-app/src/components/InvestRedeem/InvestRedeem.tsx, centrifuge-react/src/utils/formatting.ts
- Show right token in invest form
- Round low balances to 2 decimals in wallet button
Bug 4 and 6 of #1386
=> Centrifuge App: Show right token in invest form

onboarding-api/src/controllers/auth/authenticateWallet.ts, onboarding-api/src/utils/centrifuge.ts
=> Onboarding: Fix authentication with substrate

centrifuge-app/src/pages/Onboarding/KnowYourBusiness/BusinessInformation.tsx, centrifuge-app/src/pages/Onboarding/KnowYourCustomer/SignerVerification.tsx, centrifuge-app/src/pages/Onboarding/geographyCodes.ts, onboarding-api/src/controllers/kyb/verifyBusiness.ts, onboarding-api/src/controllers/user/startKyc.ts, onboarding-api/src/utils/geographyCodes.ts
This pull request removes the choice for restricted countries from the UI when onboarding. There is also a server side check in place to ensure a user can not onboard with a restricted country.
=> restrict countries

centrifuge-app/src/config.ts, onboarding-api/src/utils/tinlake.ts
=> updates mainnet ipfs hash

centrifuge-app/src/components/InvestRedeem/InvestRedeem.tsx, centrifuge-app/src/pages/Onboarding/index.tsx, onboarding-api/src/middleware/canOnboardToTinlakeTranche.ts
This pull request fixes a type error.
=> fix type error

centrifuge-app/src/components/Dialogs/DataSharingAgreementDialog.tsx, centrifuge-app/src/pages/Onboarding/LinkWallet.tsx
- updates content 'Data sharing consent'
- also removes nested button from label
Subtask of: https://github.com/centrifuge/apps/issues/1404
=> Updates content 'Data sharing consent'

centrifuge-app/src/components/Dialogs/ExecutiveSummaryDialog.tsx, centrifuge-app/src/components/IssuerSection.tsx
Subtask of: https://github.com/centrifuge/apps/issues/1404
=> Display pool issuer name in ExecutiveSummaryDialog

centrifuge-app/src/components/Tooltips.tsx, centrifuge-app/src/pages/Pool/Overview/index.tsx
Subtask of: https://github.com/centrifuge/apps/issues/1404
=> Refactor wording from APY to APR

centrifuge-app/src/components/PoolCard.tsx, centrifuge-app/src/pages/Pool/Overview/index.tsx, centrifuge-app/src/utils/getPoolValueLocked.ts
- creates new util
- refactors PoolCard and pool Overview to use new util
Subtask of: https://github.com/centrifuge/apps/issues/1404
=> Pool value locked

centrifuge-app/src/utils/useListedPools.ts
Show spinner if TInlake pools are loading instead of "There are no pools yet"
=> Centrifuge App: Loading state for Tinlake pools

centrifuge-app/src/pages/IssuerPool/Assets/CreateLoan.tsx
=> conditionally display create asset link

centrifuge-app/src/pages/Onboarding/Accreditation.tsx, centrifuge-app/src/pages/Onboarding/SignSubscriptionAgreement.tsx
- updates copy for entity accreditation
- adds dialog to confirm signing accreditation
Closes #1420
=> Onboarding: Accredited investor check

centrifuge-app/src/components/LiquidityEpochSection.tsx
=> CentrifugeApp: Multiply orders by token price to get DAI value

centrifuge-app/src/pages/Onboarding/KnowYourBusiness/ManualBusinessVerification.tsx, centrifuge-app/src/pages/Onboarding/KnowYourBusiness/index.tsx, centrifuge-app/src/pages/Onboarding/KnowYourCustomer/IdentityVerification.tsx, centrifuge-app/src/pages/Onboarding/KnowYourCustomer/index.tsx
This pull request improves the ShuftiPro iframe in several ways:
1. The `iframe` is now embedded within a `dialog` allowing more space for the user to operate within the `iframe`.
2. The QR code functionality for uploading images via mobile is now available.
3. When uploading documents for manual KYB, the document preview is more improved.
QR code functionality:
Improved PDF preview: 
Improved camera view:
=> fix: improve shuftipro iframe

centrifuge-app/src/pages/IssuerPool/Investors/OnboardingSettings.tsx
=> Onboarding: Fix external link and filter countries that have been selected

centrifuge-app/src/components/DebugFlags/config.ts, centrifuge-app/src/pages/IssuerPool/Access/AssetOriginators.tsx, centrifuge-app/src/pages/IssuerPool/Access/CreatePodAccount.tsx, centrifuge-app/src/pages/IssuerPool/Assets/CreateLoan.tsx, centrifuge-js/src/modules/pod.ts, centrifuge-js/src/modules/pools.ts, centrifuge-react/src/components/CentrifugeProvider/CentrifugeProvider.tsx
Adds a button to create a pod account to the AO form on the access page. Hidden behind a debug flag.
Also funds the AO with enough funds to create 100 loans when setting it up.
=> Centrifuge App: Create Dev Pod Account

centrifuge-app/src/pages/IssuerCreatePool/useStoredIssuer.ts, centrifuge-app/src/pages/IssuerPool/Access/PoolManagers.tsx, centrifuge-app/src/pages/IssuerPool/Configuration/Admins.tsx, centrifuge-app/src/pages/IssuerPool/Configuration/ViewLoanTemplate.tsx, centrifuge-app/src/pages/IssuerPool/Investors/InvestorStatus.tsx, centrifuge-app/src/pages/IssuerPool/Investors/OnboardingSettings.tsx, centrifuge-app/src/pages/IssuerPool/Investors/index.tsx, centrifuge-app/src/pages/Loan/index.tsx, centrifuge-app/src/utils/parseMetadataUrl.ts, centrifuge-app/src/utils/usePermissions.ts, centrifuge-js/src/modules/metadata.ts, centrifuge-js/src/modules/pools.ts, centrifuge-react/src/components/Transactions/TransactionToasts.tsx, onboarding-api/README.md, onboarding-api/src/utils/centrifuge.ts
Changes MemberListAdmin to InvestorAdmin. Also fixes IPFS URIs
=> Centrifuge App: Fix pool role and IPFS URIs

centrifuge-app/src/components/Menu/index.tsx, centrifuge-app/src/pages/IssuerCreatePool/index.tsx, centrifuge-app/src/pages/IssuerPool/Access/AssetOriginators.tsx, centrifuge-app/src/pages/IssuerPool/Access/CreatePodAccount.tsx, centrifuge-app/src/pages/IssuerPool/Configuration/EpochAndTranches.tsx, centrifuge-app/src/utils/usePermissions.ts, centrifuge-js/src/modules/multisig.ts, centrifuge-js/src/modules/pools.ts, centrifuge-react/src/components/WalletProvider/WalletProvider.tsx, centrifuge-react/src/hooks/useCentrifugeQueries.ts
- Fixes "Epoch and Tranches" form submission
- Disables use of `useCentrifugeQueries`, which occasionally entered an infinite loop
- Fixes negative transfer when removing hot wallet from AO
- Fixes pending multisigs not refetching after approving
=> Centrifuge App: Fix tranche updates

centrifuge-app/src/pages/IssuerPool/Assets/CreateLoan.tsx, centrifuge-app/src/pages/IssuerPool/Configuration/Details.tsx, centrifuge-app/src/utils/usePools.ts, centrifuge-js/src/modules/pools.ts
Rename `pod.url` to `pod.node` in pool metadata and add `pod.indexer`. Important to get this in first, in case a pool launches before the indexer work is done, so we don't have to migrate metadata later.
=> CentrifugeJS: Rename pod.url to pod.node

centrifuge-js/src/modules/pools.ts
This reverts commit 5f3eed2b700157210b2f686d1fc15061cc6e06e5.
Reverts an early fix for finding a currency
=> Revert "Find currency by symbol (#1454)"

.github/README.md, centrifuge-app/src/components/OnboardingAuthProvider.tsx, centrifuge-app/src/pages/Onboarding/SignSubscriptionAgreement.tsx, centrifuge-app/src/pages/Onboarding/index.tsx, centrifuge-app/src/utils/tinlake/useTinlakePools.ts, onboarding-api/src/utils/annotateAgreementAndSignAsInvestor.ts, onboarding-api/src/utils/centrifuge.ts
- removes proxy call from transfer since it's not needed
- clear onboarding auth token when a new wallet is connected
- fixes agreements not appearing for tinlake pools
- cleans up a bit :)
=> Onboarding: Remove proxy call from transfer

centrifuge-app/src/components/Dialogs/FaucetConfirmationDialog.tsx, centrifuge-app/src/components/Faucet.tsx, centrifuge-app/src/components/PageWithSideBar.tsx, centrifuge-app/src/pages/Onboarding/KnowYourCustomer/index.tsx, centrifuge-app/src/pages/Onboarding/UltimateBeneficialOwners.tsx, centrifuge-app/src/pages/Pool/Overview/index.tsx, faucet-api/package.json, faucet-api/src/index.ts, onboarding-api/src/controllers/kyb/confirmOwners.ts, onboarding-api/src/database/index.ts, yarn.lock
- fixes aUSD transfer from the faucet (it was using an outdated version of aUSD)
- makes the faucet agnostic to pool currencies
- moves the faucet to display only in pool detail pages and sends the native currency and the pool currency to the user
- enforces a minimum age of 18 to onboard (also for UBOs). Closes #1456
=> Faucet: Use foreignAsset key for faucet & Onboarding: minimum age 18

.github/README.md, .github/actions/prepare-deploy/action.yml, .github/workflows/catalyst-deploy.yml, .github/workflows/centrifuge-app.yml, .github/workflows/onboarding-api.yml, .github/workflows/pinning-api.yml
Have consistency between the release tags and the catalyst tag
=> Change catalyst tag to centrifuge-app/v*

centrifuge-app/src/components/LoanLabel.tsx
=> Fix labels

centrifuge-app/package.json, centrifuge-app/src/utils/tinlake/useTinlakePools.ts, yarn.lock
- Unexpected token error thrown in graphql-request caused by vite
Context and fix:
[Vite Environment Variable Replacements #13594](https://github.com/vitejs/vite/discussions/13594)
https://github.com/vitejs/vite/discussions/13594#discussioncomment-6250699
=> Fix broken development environment

centrifuge-react/src/components/WalletMenu/WalletMenu.tsx
=> Centrifuge App: Fix copy and subscan buttons in wallet menu

centrifuge-app/src/utils/useMetadata.ts
Fixes pools list when a pool has no metadata
=> Centrifuge App: Fix pools list

centrifuge-app/src/components/Root.tsx, centrifuge-app/src/components/SupportedBrowserBanner.tsx, fabric/src/components/Banner/index.tsx
=> CentrifugeApp: Unsupported browser handling

centrifuge-app/src/components/InvestRedeem/InvestRedeem.tsx
=> Centrifuge App: Fix Tinlake collect currency symbol

centrifuge-app/src/pages/IssuerPool/Assets/CreateLoan.tsx, centrifuge-app/src/pages/Loan/ExternalFinanceForm.tsx, centrifuge-app/src/pages/Loan/index.tsx, centrifuge-js/src/CentrifugeBase.ts, centrifuge-js/src/modules/pools.ts
Updates external finance form with latest chain changes. also add runtime call to get loan portfolio with accrued interest and present value (not used yet)
=> CentrifugeApp: Fix external loan financing

centrifuge-app/src/components/DebugFlags/components/ConvertEvmAddress.tsx, centrifuge-app/src/components/Identity.tsx, centrifuge-app/src/components/OnboardingAuthProvider.tsx, centrifuge-app/src/pages/IssuerPool/Configuration/AddAddressInput.tsx, centrifuge-app/src/utils/usePodAuth.ts, centrifuge-js/src/CentrifugeBase.ts, centrifuge-js/src/modules/utils.ts, centrifuge-react/src/components/CentrifugeProvider/CentrifugeProvider.tsx, centrifuge-react/src/components/CentrifugeProvider/index.tsx, centrifuge-react/src/components/WalletMenu/WalletMenu.tsx, centrifuge-react/src/components/WalletProvider/AccountButton.tsx, centrifuge-react/src/components/WalletProvider/WalletProvider.tsx, centrifuge-react/src/components/WalletProvider/utils.ts, onboarding-api/src/utils/networks/centrifuge.ts
Gets the cent chain ID from chain instead of inferring from the config. Adds a `useCentrifugeUtils` hook for easy address formatting
=> CentrifugeJS: Get chain ID from chain

centrifuge-app/src/utils/tinlake/useTinlakePools.ts
=> CentrifugeApp: Log maxSeniorRatio error to fix the app

onboarding-api/src/utils/networks/centrifuge.ts
=> OnboardingAPI: updateMember for liquidity pools

.github/README.md, centrifuge-app/README.md
=> CentrifugeApp: Update docs

onboarding-api/src/emails/sendDocumentsMessage.ts
=> OnboardingAPI: Fix email sending to issuer

centrifuge-app/src/components/InvestRedeem/InvestRedeemProvider.tsx, centrifuge-app/src/pages/Pool/Overview/index.tsx, onboarding-api/env-vars/demo.env
- prepares onboarding api for algol (new endpoint and new pure proxy)
- fixes bug where user wishing to onboard to tinlake is restored 
=> OnboardingAPI: demo/algol setup

centrifuge-app/src/components/DebugFlags/config.ts, centrifuge-app/src/components/PortfolioCta/index.tsx
=> CentrifugeApp: Hide portfolio card behind debug flag

centrifuge-app/src/components/PortfolioCta/index.tsx
=> CentrifugeApp: Hide portfolio card take 2

centrifuge-app/src/components/LayoutBase/styles.tsx
=> Centrifuge App: Make wallet button non sticky

centrifuge-app/src/pages/Pools.tsx
=> CentrifugeApp: Display pools as open when most junior tranche has capacity

centrifuge-app/src/utils/usePodAuth.ts
=> Centrifuge App: Fix POD auth

centrifuge-js/src/modules/pools.ts
=> CentrifugeJS: Return empty permissions

centrifuge-app/src/utils/formatting.ts
=> Centrifuge App: Fix token price formatting

centrifuge-js/src/modules/pools.ts
=> Centrifuge App: Fix foreign assets

centrifuge-app/src/pages/IssuerCreatePool/index.tsx
=> Centrifuge App: Fix pool create type

centrifuge-app/src/components/LiquidityTransactionsSection.tsx
=> CentrifugeApp: Hide section title in liquidity tab if no table is displayed

onboarding-api/src/controllers/user/startKyc.ts
=> Onboarding: Allow users not living in country of their passport

centrifuge-app/src/components/PoolCard/index.tsx, centrifuge-app/src/components/PoolList.tsx, centrifuge-app/src/pages/Pools.tsx
This pull request manually changes the status of the Anemoy pool to `Upcoming` and sorts the pools by `Upcoming`.
=> chore: change anemoy status

centrifuge-js/src/modules/pools.ts
=> CentrifugeApp: Display LpEthUsdc as USDC

centrifuge-app/src/utils/usePermissions.ts
=> Centrifuge App: Fix for connecting single account

LICENSE
=> Add OSS license

onboarding-api/src/emails/sendDocumentsMessage.ts, onboarding-api/src/emails/sendVerifiedBusinessMessage.ts, onboarding-api/src/emails/sendVerifyEmailMessage.ts
=> Onboarding: update support email

centrifuge-app/src/components/InvestmentsList.tsx, centrifuge-app/src/components/TokenList.tsx
=> Centrifuge App: Asset class fix

centrifuge-app/src/utils/usePools.ts
Disable suspense for fetching subquery data, to still show the asset detail page when there's an error
=> Centrifuge App: Fix asset detail when subquery is down

centrifuge-app/src/components/PoolFilter/index.tsx, centrifuge-app/src/components/PoolList.tsx
=> Centrifuge App: Fix asset class in pool table

centrifuge-app/src/pages/Pool/Overview/index.tsx
=> CentrifugeApp: Fix connection guard for evm wallets on cent pool

centrifuge-app/src/components/Portfolio/Transactions.tsx
This pull request addresses a bug that crashes the app when viewing the `/portfolio` page when connected with an EVM wallet.
=> fix: fix trx bug

centrifuge-app/src/components/Report/PoolBalance.tsx, centrifuge-app/src/components/Report/ReportContext.tsx, centrifuge-js/src/modules/pools.ts
=> Centrifuge App: Fix investor transaction report

centrifuge-app/src/components/OnboardingAuthProvider.tsx, centrifuge-app/src/components/OnboardingProvider.tsx, centrifuge-app/src/pages/Onboarding/CompleteExternalOnboarding.tsx, centrifuge-app/src/pages/Onboarding/GlobalStatus.tsx, centrifuge-app/src/pages/Onboarding/LinkWallet.tsx, centrifuge-app/src/pages/Onboarding/index.tsx
This pull request refactors onboarding to open the global onboarding flow in a new window when using the app with [Safe](https://app.safe.global/).
Closes #1664 
Onboarding
=> fix: use new window

centrifuge-app/src/components/LoanList.tsx, centrifuge-app/src/pages/Pools.tsx, centrifuge-js/src/modules/nfts.ts
Getting NFT data was breaking because nftSales pallet isn't in the Centrifuge runtime.
=> Centrifuge App: Fix getting loan NFT data

centrifuge-js/src/modules/liquidityPools.ts
Fixes the query for domain routers to account for the different enum options
=> CentrifugeJS: Fix query for domain routers

centrifuge-app/src/pages/IssuerCreatePool/index.tsx
Get the right env var when creating a pool
=> Centrifuge App: Fix env var

centrifuge-app/src/components/Portfolio/InvestedTokens.tsx
This pull request fixes column spacing on portfolio and prime page.
`/portfolio` and `/prime/aave` page.
=> fix: portfolio column spacing

centrifuge-app/src/components/DataTable.tsx, centrifuge-app/src/components/Root.tsx, centrifuge-app/src/config.ts, centrifuge-app/src/pages/IssuerPool/Access/AssetOriginators.tsx, centrifuge-app/src/pages/IssuerPool/Investors/OnboardingSettings.tsx, centrifuge-app/src/pages/Loan/ExternalFinanceForm.tsx, centrifuge-app/src/pages/Loan/FinanceForm.tsx, centrifuge-app/src/utils/usePermissions.tsx, centrifuge-js/package.json, centrifuge-js/src/modules/liquidityPools.ts, centrifuge-js/src/modules/pools.ts, centrifuge-react/src/components/CentrifugeProvider/CentrifugeProvider.tsx, centrifuge-react/src/components/WalletProvider/index.tsx, fabric/src/components/Grid/index.tsx, yarn.lock
Add inputs in the AO section for Withdraw addresses. Stores these, besides on-chain also in the pool config, to store the needed data for the XCM call, and an optional name. Also adds a dropdown to the finance forms to withdraw to the defined addresses.
Open items for follow-up:
- Set names for the withdraw addresses
- Show balance of the addresses
- Ensure the pool admin pure proxy is always one of the addresses
- Update styling of the inputs when it's designed
[#1240](https://github.com/centrifuge/apps/issues/1240)
=> Centrifuge App: Restricted transfers

centrifuge-app/src/pages/Loan/FinanceForm.tsx, centrifuge-js/src/modules/pools.ts
Fix selecting any existing withdraw address when financing a loan
=> Centrifuge App: Fix borrow and withdraw

centrifuge-app/src/components/DebugFlags/config.ts, centrifuge-app/src/pages/IssuerPool/Access/CreatePodAccount.tsx
=> Centrifuge App: Add POD admin debug flag

centrifuge-app/src/components/Swaps/Orders.tsx, centrifuge-app/src/components/Swaps/Swap.tsx, centrifuge-app/src/utils/validation/index.ts, centrifuge-js/src/modules/liquidityPools.ts, centrifuge-js/src/modules/pools.ts, centrifuge-react/src/hooks/useCentrifugeTransaction.ts
Adds a partial fulfillment option to the swap form
#1602
=> Centrifuge App: Partial swap order fulfillment

centrifuge-app/src/components/DebugFlags/config.ts, centrifuge-app/src/pages/IssuerPool/Investors/InvestorStatus.tsx
=> Centrifuge App: Remove liquidity pools debug flag

centrifuge-app/src/components/Root.tsx
=> Centrifuge App: Change Base Goerli RPC endpoint

centrifuge-js/src/modules/liquidityPools.ts
Fixes checking if a currency for LP needs to be added
=> CentrifugeJS: Fix LP add currency

centrifuge-js/src/modules/liquidityPools.ts, centrifuge-js/src/modules/liquidityPools/abi/LiquidityPool.abi.json
Fixes the transaction to invest with permit for Liquidity Pools.
=> CentrifugeJS: Fix LP invest with permit

.github/actions/prepare-deploy/action.yml
=> Fix ff prod deployments

centrifuge-js/src/modules/liquidityPools.ts
=> Hardcode USDC permit

centrifuge-js/src/modules/pools.ts
Fixes the type that changed after the latest chain upgrade
[#1749](https://github.com/centrifuge/apps/issues/1749)
=> Fix transfer debt

centrifuge-app/src/pages/Loan/ExternalFinanceForm.tsx, centrifuge-app/src/pages/Loan/ExternalRepayForm.tsx, centrifuge-app/src/pages/Loan/FinanceForm.tsx, centrifuge-app/src/pages/Loan/OraclePriceForm.tsx, centrifuge-app/src/pages/Loan/RepayForm.tsx, centrifuge-app/src/pages/Loan/TransferDebtForm.tsx, centrifuge-app/src/utils/validation/index.ts, fabric/src/components/CurrencyInput/CurrencyInput.stories.tsx, fabric/src/components/CurrencyInput/index.tsx
Also replaces the inputs in the finance and repay forms with the new inputs, mainly because the new currency input is less buggy.
#1713
=> Centrifuge App: Use 8 decimals for face value and settlement price

centrifuge-app/src/components/InvestRedeem/InvestRedeemDrawer.tsx, centrifuge-js/src/modules/liquidityPools.ts, centrifuge-react/src/components/WalletProvider/WalletProvider.tsx
Fixes the isSmartContractWallet context value
=> Fix using Liquidity Pools with Safe

centrifuge-app/src/utils/useAddress.ts
Will allow viewing of portfolio page for a debug address
#1760
=> Fix debug address

centrifuge-app/src/components/DebugFlags/config.ts, centrifuge-app/src/components/Report/Holders.tsx, centrifuge-app/src/components/Report/ReportContext.tsx, centrifuge-app/src/components/Report/ReportFilter.tsx, centrifuge-app/src/components/Report/index.tsx, centrifuge-app/src/utils/usePools.ts, centrifuge-js/src/modules/pools.ts, centrifuge-js/src/types/subquery.ts
=> Holders report

centrifuge-app/src/components/LiquidityEpochSection.tsx, centrifuge-app/src/utils/usePools.ts
Collect at most 10 orders, when closing/executing an epoch.
[#1761](https://github.com/centrifuge/apps/issues/1761)
=> Collect when closing epoch

centrifuge-app/src/components/InvestRedeem/InvestRedeem.tsx, centrifuge-app/src/pages/Pool/Overview/index.tsx, centrifuge-app/src/utils/useConnectBeforeAction.ts
[#1753](https://github.com/centrifuge/apps/issues/1753)
=> Investment follow-up

centrifuge-app/src/pages/Pool/Overview/index.tsx
=> Remove age

centrifuge-app/src/pages/IssuerPool/Access/AssetOriginators.tsx
=> Fix Restricted transfer validation in AO form

centrifuge-app/src/components/InvestRedeem/InvestRedeem.tsx
=> Invest: Update epoch copy

centrifuge-app/src/components/Portfolio/TransferTokensDrawer.tsx
=> Centrifuge App: Fix EVM transfers and send/recieve tab switching

centrifuge-js/src/modules/pools.ts, centrifuge-js/src/modules/proxies.ts
Account Ids are now stored as hex in Subquery. Updates CentJS to send the addresses formatted that way
=> Pass address as hex to Subquery

centrifuge-app/src/components/OnboardingAuthProvider.tsx, centrifuge-app/src/pages/Loan/TransferDebtForm.tsx, centrifuge-app/src/pages/Onboarding/index.tsx
This pull request cleans up typescript errors that were surfacing in the terminal.
=> chore: clean up type errors

centrifuge-app/src/components/PoolCard/index.tsx, centrifuge-app/src/components/Tooltips.tsx
This pull request adds a tooltip for the Anemoy pool APR in the pool list
#1695 part 2
=> Centrifuge App: Add Anemoy APR tooltip

centrifuge-app/src/pages/Pool/Header.tsx
This pull request uses `https://ipfs.io/ipfs/` as the ipfs gateway for cent chain pool icons on the pool detail page rather than `https://centrifuge.mypinata.cloud/ipfs/`.
Pool detail page
=> fix: pool detail icon

centrifuge-app/src/pages/Loan/FinanceForm.tsx
This pull request removes pool reserve text when financing a cash asset.
#1764 
Finance form
=> remove text for cash assets

centrifuge-app/src/components/PoolCard/index.tsx
=> Centrifuge App: Fix target APR

centrifuge-js/src/modules/pools.ts, fabric/src/components/TextInput/index.tsx
The finance and transfer transactions need different proxy types. Fixed by setting the proxies explicitly in the finance functions. A bit hacky, but should this way also work with multiple proxies.
=> Fix finance and transfer

centrifuge-app/src/components/InvestRedeem/InvestRedeem.tsx, centrifuge-app/src/components/Portfolio/Transactions.tsx
=> Show transactions history for specific tranche in Invest drawer

centrifuge-app/src/components/PoolCard/index.tsx, centrifuge-app/src/config.ts, centrifuge-react/src/components/WalletProvider/WalletDialog.tsx
This pull request hides testnets on the `https://app-ff-production.k-f.dev/pools/4139607887` domain and reorders networks to put Ethereum mainnet first.
#1795
Wallet Dialog
=> reorder networks

centrifuge-app/src/components/InvestRedeem/InvestRedeemLiquidityPoolsProvider.tsx
Claim tokens wasn't showing for Liquidity Pools Invest/Redeem.
=> Liquidity Pools: Fix order

centrifuge-app/src/components/DataTable.tsx, centrifuge-app/src/components/PoolCard/index.tsx, centrifuge-app/src/components/Portfolio/CardPortfolioValue.tsx, centrifuge-app/src/components/Portfolio/Holdings.tsx, centrifuge-app/src/components/Tooltips.tsx, centrifuge-app/src/pages/Portfolio/index.tsx, centrifuge-app/src/utils/tinlake/useTinlakeBalances.ts
=> Centrifuge App: Fix tooltip hover, console errors and duplicated DAI

centrifuge-app/src/pages/IssuerCreatePool/validate.ts, centrifuge-app/src/pages/IssuerPool/Assets/CreateLoan.tsx, centrifuge-app/src/pages/IssuerPool/Assets/PricingInput.tsx
=> Centrifuge App: Fix token naming and options for valuation method

centrifuge-react/src/components/WalletProvider/SelectButton.tsx, centrifuge-react/src/components/WalletProvider/WalletDialog.tsx
This pull request hides Celo testnet when on production and also removes the `Beta` chips for the EVM chains.
#1795
WalletDialog
=> remove beta chips, hide celo testnet

centrifuge-app/src/components/InvestRedeem/InvestRedeemLiquidityPoolsProvider.tsx, centrifuge-js/src/modules/liquidityPools.ts
This pull request addresses two issues:
- changes the contract for checking balance to the token address
- converts `amount` to `string` before approving token
Investing on Liquidity Pools
=> fix: liquidity pool invest bugs

centrifuge-app/src/components/InvestRedeem/InvestRedeem.tsx
=> Centrifuge App: Update onboarding text for issuers that don't support us investors

centrifuge-app/src/components/PoolsTokensShared.tsx, centrifuge-app/src/components/PortfolioCta/Cubes.tsx, centrifuge-app/src/components/PortfolioCta/index.tsx
=> Re-add CTA

centrifuge-app/src/components/Charts/CashDragChart.tsx, centrifuge-app/src/components/DebugFlags/config.ts, centrifuge-app/src/components/LiquidityEpochSection.tsx, centrifuge-app/src/pages/Pool/Liquidity/index.tsx
- hides the `Reserve` value in the `Liquidity` tab
- hides the `Start order execution` button in the `Liquidity` tab for non issuers
#1798 
Liquidity tab on the issuer page
=> hide reserve, hide epoch execution

centrifuge-js/src/modules/liquidityPools.ts, centrifuge-js/src/modules/liquidityPools/abi/LiquidityPool.abi.json
=> Update LP calls

centrifuge-app/src/components/LiquidityEpochSection.tsx
=> Fix account bug

centrifuge-js/src/modules/liquidityPools.ts
=> Centrifuge App: Fix invalid arrayify value in LP invest tx

centrifuge-js/src/modules/liquidityPools.ts
=> Centrifuge App: Use HashZero to represent empty bytes for LP

centrifuge-app/src/components/InvestRedeem/types.ts, centrifuge-js/src/modules/liquidityPools.ts
=> Centrifuge App: fix empty hash

centrifuge-app/src/components/Menu/index.tsx, centrifuge-app/src/components/Portfolio/AssetAllocation.tsx, centrifuge-app/src/components/Portfolio/CardPortfolioValue.tsx, centrifuge-app/src/components/Portfolio/Holdings.tsx, centrifuge-app/src/components/Portfolio/Transactions.tsx, centrifuge-app/src/pages/Portfolio/index.tsx, centrifuge-app/src/pages/Prime/Detail.tsx
=> Centrifuge App: Empty portfolio state

centrifuge-js/src/modules/pools.ts
This pull request refactors the `getDailyPoolStates` function to use the `endCursor` returned from the subquery responses to ensure that ALL necessary data is retrieved.
Pool page
=> fix: refactor snapshots to use cursor

centrifuge-app/src/pages/IssuerPool/Access/AssetOriginators.tsx
Limit the destinations that can be selected for withdraw addresses based on the transferability of the pool currency.
[#1818](https://github.com/centrifuge/apps/issues/1818)
=> Restricted Transfer: Limit destinations

centrifuge-js/src/modules/pools.ts
=> Centrifuge App: Fix poolId in subql query

centrifuge-js/src/modules/pools.ts
Reverts centrifuge/apps#1853
Problem was fixed on subql side therefore this change is not necessary anymore
=> Revert "Centrifuge App: Fix poolId in subql query"

centrifuge-app/src/components/Charts/PriceChart.tsx, centrifuge-app/src/components/Portfolio/TransferTokensDrawer.tsx, centrifuge-js/src/modules/pools.ts
#1835 improve clickable copy address in Receive tab (portfolio)
#1836 bug where cfg price chart flashes 100% before calculating price difference
=> Centrifuge App: Remove extra circle around copy to clipboard button

centrifuge-app/src/pages/Loan/ExternalFinanceForm.tsx, centrifuge-app/src/utils/validation/index.ts
This pull request allows users to finance an oracle asset with a face value of 0. This will allow a workaround to update oracle pricing until the next chain update.
External finance form
=> chore: allow to finance zero for oracle

centrifuge-js/src/modules/pools.ts
This pull request removes logic so that pool detail pages will load properly until oracle v2 work is done.
`pools.ts`
=> fix: fed value error

centrifuge-app/src/components/LiquidityEpochSection.tsx, centrifuge-app/src/utils/tinlake/useTinlakePools.ts
Fix transaction when batching execute epoch with collecting investments.
=> Fix execute epoch transaction

centrifuge-app/src/components/InvestRedeem/InvestRedeemTinlakeProvider.tsx, centrifuge-app/src/components/Portfolio/CardPortfolioValue.tsx, centrifuge-app/src/components/Portfolio/Holdings.tsx, centrifuge-app/src/config.ts, centrifuge-app/src/pages/Portfolio/index.tsx, centrifuge-app/src/utils/address.ts, centrifuge-app/src/utils/tinlake/currencies.ts, centrifuge-app/src/utils/tinlake/useTinlakeBalances.ts, centrifuge-js/src/index.ts
Show Tinlake holdings on the portfolio page
=> Show Tinlake portfolio

centrifuge-app/src/components/ExpiringCFGRewardsBanner.tsx, centrifuge-app/src/utils/tinlake/useTinlakeRewards.ts
This pull request shows the cfg rewards expiry banner for users that have cfg rewards but no linked addresses.
#1869
=> fix: show rewards banner for unlinked

centrifuge-app/src/components/InvestRedeem/InvestRedeem.tsx, centrifuge-app/src/components/InvestRedeem/types.ts, centrifuge-app/src/components/IssuerSection.tsx, centrifuge-app/src/components/PortfolioCta/index.tsx, centrifuge-app/src/components/Tooltips.tsx, centrifuge-js/src/modules/pools.ts
This pull request makes code changes to address TypeScript errors.
😄
=> chore: typescript clean up

centrifuge-app/src/components/InvestRedeem/InvestRedeemCentrifugeProvider.tsx, centrifuge-app/src/components/InvestRedeem/InvestRedeemLiquidityPoolsProvider.tsx, centrifuge-app/src/components/InvestRedeem/InvestRedeemTinlakeProvider.tsx, centrifuge-app/src/components/InvestRedeem/types.ts
When there are multiple liquidity pools for a tranche, prefer USDC.
=> Select USDC by default as LP currency

centrifuge-app/src/components/PoolCard/PoolStatus.tsx, centrifuge-app/src/components/PoolList.tsx
#1896 Adds archive pool status and closes onboarding for archived pools ([metadata update PR](https://github.com/centrifuge/tinlake-pools-mainnet/pull/96))
=> Archived pool status and filter for tinlake pools

centrifuge-app/src/components/PoolFilter/index.tsx, centrifuge-app/src/components/PoolList.tsx
=> Hide archived pools by default

centrifuge-app/src/components/PoolFilter/utils.ts, centrifuge-app/src/config.ts, onboarding-api/src/utils/networks/tinlake.ts
=> Update pool hash

centrifuge-app/src/pages/Loan/TransferDebtForm.tsx
=> Disallow transferring debt from external to external loans

centrifuge-js/src/modules/pools.ts
=> Disable oracles

centrifuge-app/src/pages/Pool/Overview/index.tsx, centrifuge-app/src/utils/tinlake/useTinlakePools.ts, centrifuge-app/src/utils/useAverageMaturity.ts, centrifuge-js/src/modules/pools.ts
This pull request fixes a type error with `yield30DaysAnnualizedByPoolIdTrancheId` and also removes cash assets from being considered in the average asset maturity calculation.
#1878
=> fix: type error and remove cash valuation from avg asset maturity

.github/actions/deploy-gfunction/action.yml, .github/workflows/onboarding-api.yml
```
Memory limit of 256 MiB exceeded with 264 MiB used. Consider increasing the memory limit, see https://cloud.google.com/functions/docs/configuring/memory 
```
This increases the memory limit of the cloud functions
=> Increase functions memory limit

.github/actions/deploy-gfunction/action.yml
=> Fix typo pipeline

centrifuge-app/.env-config/.env.altair, centrifuge-app/.env-config/.env.catalyst, centrifuge-app/.env-config/.env.demo, centrifuge-app/.env-config/.env.development, centrifuge-app/.env-config/.env.example, centrifuge-app/.env-config/.env.production, centrifuge-app/package.json, centrifuge-app/src/components/PoolFees/ChargeFeesDrawer.tsx, centrifuge-app/src/components/PoolFees/EditFeesDrawer.tsx, centrifuge-app/src/components/PoolFees/index.tsx, centrifuge-app/src/pages/IssuerCreatePool/PoolFeeInput.tsx, centrifuge-app/src/pages/IssuerCreatePool/index.tsx, centrifuge-app/src/pages/IssuerPool/Header.tsx, centrifuge-app/src/pages/IssuerPool/PoolFees/index.tsx, centrifuge-app/src/pages/IssuerPool/index.tsx, centrifuge-app/src/utils/formatting.ts, centrifuge-js/src/modules/pools.ts, yarn.lock
[#1875](https://github.com/centrifuge/apps/issues/1875)
=> Add pool fees to create pool form

centrifuge-app/src/components/IssuerSection.tsx, centrifuge-app/src/pages/Pool/Overview/index.tsx
Revert changes on main for the new pool overview page
=> Revert pool overview

centrifuge-app/src/components/IssuerSection.tsx, centrifuge-app/src/pages/IssuerCreatePool/PoolReportsInput.tsx, centrifuge-app/src/pages/IssuerCreatePool/index.tsx, centrifuge-app/src/pages/IssuerPool/Configuration/Issuer.tsx, centrifuge-js/src/modules/pools.ts
Adds pool analysis section to create pool and configuration page. pointed to the RU branch because that has a working create pool form.
[#1829](https://github.com/centrifuge/apps/issues/1829)
=> Add pool analysis section to Create Pool form

centrifuge-app/src/components/InvestRedeem/InvestRedeemTinlakeProvider.tsx
Fix collect ui showing for in the Tinlake invest/redeem drawer, even when there's nothing to collect.
[#1940](https://github.com/centrifuge/apps/issues/1940)
=> Fix Tinlake collect

centrifuge-app/src/components/PoolOverview/AssetsByMaturity.tsx, centrifuge-app/src/components/PoolOverview/Cashflows.tsx, centrifuge-app/src/components/PoolOverview/KeyMetrics.tsx, centrifuge-app/src/components/PoolOverview/PoolAnalysis.tsx, centrifuge-app/src/components/PoolOverview/PoolPerfomance.tsx, centrifuge-app/src/components/PoolOverview/PoolStructure.tsx, centrifuge-app/src/components/PoolOverview/TrancheTokenCards.tsx, centrifuge-app/src/components/PoolOverview/TransactionHistory.tsx, centrifuge-app/src/pages/Pool/Overview/index.tsx
This pull request implements the new layout for the pool overview page.
Closes #1857 
Pool overview page
=> pool detail page layout redesign

centrifuge-app/src/pages/IssuerPool/Configuration/Admins.tsx, centrifuge-app/src/pages/Loan/index.tsx, centrifuge-app/src/utils/usePodAuth.ts, centrifuge-app/src/utils/usePodDocument.ts, centrifuge-js/src/modules/pod.ts
Add support for reading loan documents with the PODReadAccess pool permission
=> Add POD Read Access

centrifuge-js/package.json
=> Bump CentrifugeJS version

centrifuge-app/src/components/PoolOverview/KeyMetrics.tsx, centrifuge-app/src/pages/Pool/Overview/index.tsx, centrifuge-app/src/utils/date.ts
This pull request finishes the key metrics card for the new pool detail page design.
#1881 
Pool detail page
=> feat: key metrics card

centrifuge-app/src/pages/Loan/TransferDebtForm.tsx
Instead of showing an borrowing amount input, show a face value input for the settlement loan, when transferring debt from an external loan.
=> Change inputs for transferring debt from external loan

centrifuge-app/src/components/PoolOverview/KeyMetrics.tsx, centrifuge-app/src/components/PoolOverview/PoolStructure.tsx, centrifuge-app/src/pages/Pool/Overview/index.tsx
This pull request implements the `Pool structure` card for the pool detail page epic redesign.
#1890 
Pool detail page
=> feat: pool structure card

centrifuge-app/src/components/Tooltips.tsx, centrifuge-app/src/pages/IssuerCreatePool/index.tsx, centrifuge-app/src/utils/useCreatePoolFee.ts
=> Pool type follow up

centrifuge-js/src/modules/pools.ts
=> Fix asset value and nav calc

centrifuge-js/src/modules/liquidityPools.ts
=> Fix breaking changes rt upgrade 1041

centrifuge-app/src/components/LoanList.tsx
=> Settlement account follow up

centrifuge-app/src/components/Charts/PoolPerformanceChart.tsx, centrifuge-app/src/components/LoanList.tsx, centrifuge-app/src/components/PoolOverview/Cashflows.tsx, centrifuge-app/src/components/PoolOverview/KeyMetrics.tsx, centrifuge-app/src/components/PoolOverview/PoolStructure.tsx, centrifuge-app/src/components/PoolOverview/TrancheTokenCards.tsx, centrifuge-app/src/components/PoolOverview/TransactionHistory.tsx, centrifuge-app/src/pages/Pool/Assets/index.tsx, centrifuge-app/src/pages/Pool/Overview/index.tsx, centrifuge-app/src/utils/tinlake/useTinlakePools.ts, centrifuge-js/src/modules/pools.ts
This pull request addresses a few tweaks for the new pool detail page.
#1987 
Pool detail page
=> fix: tweaks

centrifuge-app/src/components/DebugFlags/components/ConvertAddress.tsx, centrifuge-app/src/components/DebugFlags/config.ts, centrifuge-app/src/components/LayoutBase/index.tsx, centrifuge-app/src/components/Root.tsx, centrifuge-app/src/pages/ConvertAddress.tsx
Create a page (at `/convert`) with the address converter that's already in the debug panel.
=> Convert address page

centrifuge-react/src/components/WalletMenu/WalletMenu.tsx
=> Connect account dropdown: Remove EVM-on-Substrate converted address section

centrifuge-app/src/components/Portfolio/Holdings.tsx, centrifuge-app/src/components/Portfolio/TransferTokensDrawer.tsx, centrifuge-js/src/modules/pools.ts
- adds warning if you're trying to send native currency to an 0x address
- shows only transferable native currency in holdings table and transfer drawer
TBD: show only transferable native currency in wallet dropdown
#1991
=> CFG transfer warning

centrifuge-app/src/components/PoolCard/index.tsx, centrifuge-app/src/components/PoolFilter/index.tsx, centrifuge-app/src/components/PoolList.tsx
Adds separate table with archived pools and a toggle to show/hide them
#1905
=> archived pools toggle

centrifuge-js/src/CentrifugeBase.ts
=> Fix portfolio runtime call

centrifuge-app/src/components/PoolOverview/PoolStructure.tsx, centrifuge-app/src/pages/Pool/Overview/index.tsx
=> Pool fees in detail page

centrifuge-js/package.json, centrifuge-js/src/modules/auth.ts, package.json, yarn.lock
When using cent-js in an isolate testing environment there appears to be a version mismatch, this fixes the mismatch.
=> Upgrade packages in Centrifuge JS + Bump version

centrifuge-js/src/modules/pools.ts
This pull request maps `localUSDC` to `USDC`.
=> fix: map localusdc to usdc

centrifuge-app/src/components/Portfolio/TransferTokensDrawer.tsx, centrifuge-app/tests/e2e/specs/invest.cy.ts
=> Fix e2e: accept disclaimer and allow transfers of currencies

centrifuge-app/src/components/PoolFees/index.tsx
This pull request adds fee position and fixes the fee percentage bug.
Pool fee page
=> fix: pool fee page

centrifuge-app/src/components/PoolCard/index.tsx
This pull request uses dedicated pinata gateway for pool logos.
#1998
=> fix: use pinata

centrifuge-app/src/components/DebugFlags/config.ts, centrifuge-app/src/components/Root.tsx, centrifuge-react/src/components/WalletProvider/WalletDialog.tsx, centrifuge-react/src/components/WalletProvider/WalletProvider.tsx
This pull request adds a feature flag for toggling the Finoa wallet.
=> chore: add finoa feature flag

centrifuge-app/src/components/Portfolio/AssetAllocation.tsx
=> Fix undefined bug in portfolio

centrifuge-app/src/pages/IssuerCreatePool/validate.ts, centrifuge-app/src/pages/IssuerPool/Assets/PricingInput.tsx
=> Add extension days input

centrifuge-app/src/components/PoolList.tsx
This pull request hides the NS3 pool from the pool list.
=> chore: hide ns3 pool

centrifuge-js/src/modules/pools.ts
=> Fix asset tx history start date

centrifuge-app/src/pages/NavManagement.tsx
=> Update oracle collection when pricing

centrifuge-app/src/pages/Pool/Header.tsx
This pull request uses our dedicated pinata gateway for ipfs for pool detail page logos.
=> fix: anemoy logo

centrifuge-app/src/components/Charts/CashDragChart.tsx, centrifuge-app/src/components/Charts/PoolPerformanceChart.tsx, centrifuge-app/src/components/PoolFees/ChargeFeesDrawer.tsx, centrifuge-app/src/pages/Pool/Assets/index.tsx, centrifuge-app/src/utils/getPoolTVL.ts, centrifuge-app/src/utils/tinlake/useTinlakePools.ts, centrifuge-js/src/modules/pools.ts, onboarding-api/src/utils/networks/tinlake.ts
- fixes NAV in asset tab (adds reserve)
- exposes `total` and `aum` from pool.nav and deprecates `nav.latest`
- updates hash for tinlake pools to close NS2
=> Fix nav assets tab + close NS2 onboarding

centrifuge-app/src/components/InvestRedeem/InvestRedeem.tsx
Only show domains of liquidity pools that were actually completely deployed
=> Fix domains shown in the Invest/Redeem component

centrifuge-app/src/components/Charts/CashflowsChart.tsx
This pull request fixes a bug on Firefox where text overlaps.
#2078
=> fix: firefox overlapping

centrifuge-app/src/components/PoolOverview/KeyMetrics.tsx
=> Fix overdue asset count

centrifuge-app/src/config.ts, onboarding-api/src/utils/networks/tinlake.ts
This pull request updates the ipfs hash to archive BT1 and BT2.
=> chore: update ipfs pool hash

centrifuge-app/tests/e2e/specs/invest.cy.ts
=> Fix copy in E2E tests

centrifuge-js/src/modules/liquidityPools.ts
Only call `allowInvestmentCurrency` once per currency
=> Fix lp deployment

centrifuge-app/src/components/LiquidityEpochSection.tsx
Borrower hot wallets can also close epochs, but the Close Epoch button wasn't being shown for them.
=> Show Close Epoch button for borrower

.github/workflows/e2e.yml, centrifuge-app/env.sample, centrifuge-app/tests/e2e/data/pool.json, centrifuge-app/tests/e2e/specs/invest.cy.ts, centrifuge-app/tests/e2e/support/e2e.ts
- runs tests against demo instead of dev
- runs github workflow after demo has been deployed
Closes #2079
=> Migrate e2e to demo

centrifuge-react/src/components/WalletProvider/evm/utils.ts
Get the balance from the read-only RPC provider instead of the wallet's one, as Finoa doesn't support `eth_getBalance`.
=> Fix EVM balance

centrifuge-app/src/components/Portfolio/Holdings.tsx
Hide 0 CFG balance on Prime detail page
=> Prime: hide 0 CFG balance

centrifuge-app/src/components/PoolOverview/TrancheTokenCards.tsx
This pull request fixes text alignment on the tranche token card.
#2066
=> fix: text alignment

centrifuge-app/src/components/Charts/PoolPerformanceChart.tsx, centrifuge-app/src/components/Menu/NavManagementMenu.tsx, centrifuge-app/src/pages/IssuerCreatePool/index.tsx, centrifuge-app/src/pages/MultisigApproval.tsx, centrifuge-app/src/pages/NavManagement/NavManagementAssetTable.tsx, centrifuge-app/src/pages/NavManagement/Overview.tsx, centrifuge-app/src/utils/useCreatePoolFee.ts, centrifuge-app/src/utils/usePoolsForWhichAccountIsFeeder.tsx, centrifuge-js/src/modules/pools.ts
- adds the specs in the ticket
- fixes nav-management menu item, it now renders if you have correct permissions and showOracle debug flag selected
- removes `collectionId` from create pool since it's not needed there anymore
#2043 
#2044
=> Nav management overview + table updates

onboarding-api/env-vars/production.env
=> Add pure proxy to onboarding env

centrifuge-app/src/pages/Loan/TransferDebtForm.tsx
The outstanding interest/principal wasn't calculated correctly for external loans in the transfer debt form
=> Fix transfer debt for external loans

centrifuge-app/src/components/InvestRedeem/InvestForm.tsx
The safe account of a gnosis safe does not pay gas, so the form was disabled when it shouldn't be
=> Invest: disable native currency balance check

centrifuge-app/src/components/DebugFlags/config.ts, centrifuge-app/src/components/Menu/index.tsx
=> Remove Prime debug flag

centrifuge-app/src/components/Portfolio/Holdings.tsx
=> Fix send/receive buttons on portfolio page

centrifuge-app/src/pages/Loan/TransactionTable.tsx
=> Fix types in transaction table

centrifuge-app/src/components/Report/AssetList.tsx, centrifuge-app/src/components/Report/AssetTransactions.tsx, centrifuge-app/src/components/Report/FeeTransactions.tsx, centrifuge-app/src/components/Report/InvestorList.tsx, centrifuge-app/src/components/Report/InvestorTransactions.tsx, centrifuge-app/src/components/Report/PoolBalance.tsx, centrifuge-app/src/components/Report/TokenPrice.tsx
- Fixes decimals
- Add column Current value and Valuation method to Asset list
- Asset list displays overdue repaid assets as "Repaid"
=> Reports feedback

centrifuge-app/src/components/Report/ReportContext.tsx
=> Change From date in reporting

centrifuge-app/src/components/IssuerSection.tsx, centrifuge-app/src/components/PoolCard/index.tsx, centrifuge-app/src/components/PoolOverview/KeyMetrics.tsx, centrifuge-app/src/components/PoolOverview/TrancheTokenCards.tsx, centrifuge-app/src/components/Tooltips.tsx, centrifuge-app/src/pages/IssuerCreatePool/PoolReportsInput.tsx, centrifuge-app/src/pages/IssuerCreatePool/index.tsx, centrifuge-app/src/pages/IssuerCreatePool/validate.ts, centrifuge-app/src/pages/IssuerPool/Assets/PricingInput.tsx, centrifuge-app/src/pages/IssuerPool/Configuration/Issuer.tsx, centrifuge-app/src/pages/Loan/TransactionTable.tsx, centrifuge-app/src/pages/Loan/index.tsx, centrifuge-app/src/pages/Pool/Overview/index.tsx
=> Updates for DYF part 2

centrifuge-app/src/components/DebugFlags/config.ts, centrifuge-app/src/components/Report/OracleTransactions.tsx, centrifuge-app/src/components/Report/ReportContext.tsx, centrifuge-app/src/components/Report/ReportFilter.tsx, centrifuge-app/src/components/Report/TokenPrice.tsx, centrifuge-app/src/components/Report/index.tsx, centrifuge-app/src/utils/usePools.ts, centrifuge-js/src/modules/pools.ts, centrifuge-js/src/types/subquery.ts
=> Add oracle transactions report + token yields (behind debug flag)

centrifuge-app/src/components/Portfolio/Holdings.tsx, centrifuge-app/src/components/Portfolio/Transactions.tsx, centrifuge-app/src/components/Portfolio/usePortfolio.ts, centrifuge-app/src/pages/Prime/index.tsx
=> Fix prime portfolio amounts

centrifuge-app/src/components/Report/OracleTransactions.tsx
=> Fix missing keys

centrifuge-app/src/components/DebugFlags/config.ts, centrifuge-app/src/components/Report/ReportFilter.tsx, centrifuge-js/src/modules/pools.ts
=> Fix missing yields, add oracle tx debug flag

centrifuge-app/src/components/Charts/PoolPerformanceChart.tsx, centrifuge-js/src/modules/pools.ts, centrifuge-js/src/types/subquery.ts
=> Fix NAV values

centrifuge-app/src/components/Report/BalanceSheet.tsx, centrifuge-app/src/components/Report/ReportContext.tsx, centrifuge-app/src/components/Report/ReportFilter.tsx, centrifuge-app/src/pages/Pool/index.tsx
=> Balance sheet UI improvements

centrifuge-app/src/pages/Loan/index.tsx
=> Move timeseries

centrifuge-app/src/components/PoolOverview/TransactionHistory.tsx, centrifuge-app/src/components/Portfolio/TransactionTypeChip.tsx, centrifuge-app/src/components/Report/utils.tsx, centrifuge-js/src/types/subquery.ts
=> Support new asset tx types

centrifuge-app/src/pages/Loan/ExternalFinanceForm.tsx, centrifuge-app/src/pages/Loan/index.tsx
- Remove symbol from external loan quantity field
- Hide private data sections on loan detail page
=> Loan fixes

centrifuge-app/src/components/Portfolio/Transactions.tsx, centrifuge-js/src/modules/pools.ts
Link to the right EVM explorer for LP transactions
=> Fix explorer url in History table

centrifuge-app/src/pages/NavManagement/Overview.tsx
=> Fix NAV Management

centrifuge-app/src/components/Report/AssetTransactions.tsx
=> Fix asset names on asset tx report

centrifuge-app/src/components/Tooltips.tsx, centrifuge-app/src/pages/Loan/TransactionTable.tsx, centrifuge-app/src/pages/Loan/index.tsx
=> YTM tooltips

centrifuge-app/src/pages/Loan/TransactionTable.tsx, centrifuge-app/src/pages/Loan/index.tsx
=> Fix division by zero

centrifuge-app/src/pages/IssuerCreatePool/index.tsx, centrifuge-js/src/modules/pools.ts
=> Enable using native USDC

centrifuge-app/src/components/Charts/CashflowsChart.tsx, centrifuge-app/src/components/PoolOverview/Cashflows.tsx, centrifuge-app/src/components/Report/CashflowStatement.tsx, centrifuge-app/src/components/Report/ReportContext.tsx, centrifuge-app/src/components/Report/ReportFilter.tsx, centrifuge-app/src/components/Report/index.tsx, centrifuge-js/src/modules/pools.ts, centrifuge-js/src/types/subquery.ts
=> Cash flow statement final UI improvements

centrifuge-app/src/components/IssuerSection.tsx, centrifuge-app/src/components/PoolOverview/KeyMetrics.tsx, centrifuge-app/src/pages/Pool/Overview/index.tsx
#[2180](https://github.com/centrifuge/apps/issues/2180)
=> Fix issuer section tinlake

centrifuge-app/src/components/Charts/CashflowsChart.tsx, centrifuge-app/src/components/PoolOverview/Cashflows.tsx, centrifuge-app/src/components/Report/CashflowSheet.tsx, centrifuge-app/src/components/Report/CashflowStatement.tsx, centrifuge-app/src/components/Report/ReportContext.tsx, centrifuge-app/src/components/Report/ReportFilter.tsx, centrifuge-app/src/components/Report/index.tsx, centrifuge-app/src/utils/usePools.ts, centrifuge-js/src/modules/pools.ts, centrifuge-js/src/types/subquery.ts
=> Reports: Cashflow statement

centrifuge-app/src/pages/Loan/TransferDebtForm.tsx
=> Transfer debt bugs

centrifuge-app/src/components/Report/PoolBalance.tsx
Fixes the decimals of the redemptions values in the Pool Balance CSV
=> Fix Pool Balance CSV

centrifuge-app/src/pages/IssuerPool/Header.tsx, centrifuge-app/src/pages/Pool/Header.tsx
=> Hide fees tab on tinlake pools

centrifuge-app/src/components/PoolOverview/TransactionHistory.tsx, centrifuge-app/src/components/Report/CashflowStatement.tsx, centrifuge-js/src/modules/pools.ts, centrifuge-js/src/types/subquery.ts
=> Use paid amounts in cash flow statement

centrifuge-app/src/components/Report/ProfitAndLoss.tsx, centrifuge-app/src/components/Report/ReportFilter.tsx, centrifuge-app/src/pages/Loan/TransactionTable.tsx, centrifuge-js/src/modules/pools.ts, centrifuge-js/src/types/subquery.ts
=> P&L report improvements

centrifuge-app/src/components/Report/ProfitAndLoss.tsx, centrifuge-js/src/modules/pools.ts, centrifuge-js/src/types/subquery.ts
=> Add unrealized profit

centrifuge-app/src/components/Report/BalanceSheet.tsx, centrifuge-app/src/components/Report/CashflowStatement.tsx, centrifuge-app/src/components/Report/ProfitAndLoss.tsx, centrifuge-app/src/components/Report/ReportContext.tsx, centrifuge-app/src/components/Report/ReportFilter.tsx, centrifuge-app/src/components/Report/index.tsx, centrifuge-app/src/pages/Loan/TransactionTable.tsx, centrifuge-app/src/utils/usePools.ts, centrifuge-js/src/modules/pools.ts, centrifuge-js/src/types/subquery.ts
[2188](https://github.com/centrifuge/apps/issues/2188)
=> Report: profit and loss 

centrifuge-app/src/components/LiquidityEpochSection.tsx, centrifuge-app/src/pages/IssuerCreatePool/index.tsx, centrifuge-app/src/pages/IssuerCreatePool/validate.ts, centrifuge-app/src/pages/IssuerPool/Access/AssetOriginators.tsx, centrifuge-app/src/pages/IssuerPool/Assets/CreateLoan.tsx, centrifuge-app/src/pages/IssuerPool/Assets/PricingInput.tsx, centrifuge-app/src/pages/IssuerPool/Pricing/OracleFeeders.tsx, centrifuge-app/src/pages/IssuerPool/index.tsx, centrifuge-app/src/pages/Loan/FinanceForm.tsx, centrifuge-app/src/pages/Loan/PricingValues.tsx, centrifuge-app/src/pages/NavManagement/NavManagementAssetTable.tsx, centrifuge-app/src/utils/usePermissions.tsx, centrifuge-js/src/CentrifugeBase.ts, centrifuge-js/src/modules/pools.ts
TODO : fix "Confirm NAV" in nav management, currently throwing error: `oraclePriceCollection.NotEnoughFeeders: The amount of feeders for a key is not enough`
#2155 Runtime upgrade
#2173 Fix total NAV updating in nav management
=> Runtime upgrade 1100

centrifuge-app/src/pages/IssuerPool/Access/AssetOriginators.tsx
=> Fix AO form

centrifuge-app/src/components/IssuerSection.tsx, centrifuge-app/src/pages/Pool/Overview/index.tsx
- Add direct links to the reports in the reporting tab
- Fix duplicate issuer details 
#2202 
#2219
=> Add links to report

centrifuge-app/src/pages/IssuerCreatePool/TrancheInput.tsx
Use reusable component for currency input to handle decimals
#2224 
- [x ] Dev
It would only affect the min investment input when creating tranches
=> Change Number input for currency input

centrifuge-app/src/components/Charts/AssetPerformanceChart.tsx
- Fix some type errors 
- Render null if the chart data is loaded but non existent
=> Hide AssetPerformanceChart if no data

centrifuge-js/src/modules/metadata.ts
SVG images were sometimes not showing because Piñata didn't return the right MIME type.
=> Fix SVG images not displaying

centrifuge-js/src/CentrifugeBase.ts
=> Upgrade loansApi for dev and demo deployments

centrifuge-app/src/pages/NavManagement/NavManagementAssetTable.tsx
- adds epoch close option in nav management if LiquidityAdmin permissions are already granted
- fixes asset price - was previously showing only updated price
=> UI changes for runtime upgrade

centrifuge-app/src/components/DebugFlags/config.ts, centrifuge-app/src/components/Menu/index.tsx, centrifuge-app/src/pages/IssuerPool/Header.tsx
#[2244](https://github.com/centrifuge/apps/issues/2244)
=> Remove showOracle debug flag

centrifuge-app/src/components/PoolOverview/KeyMetrics.tsx, centrifuge-app/src/pages/Pool/Assets/index.tsx
Total assets and Ongoing assets count must exclude cash assets
#2232 
- [ x ] Dev
- [ x ] Product
- Check the overview pool key metrics assets should exclude cash assets for total & ongoing assets
- Check pool -> assets tab -> key metrics should exclude cash assets for both total and ongoing
=> Remove cash assets from ongoing & total assets count

centrifuge-app/src/pages/IssuerPool/Investors/LiquidityPools.tsx, centrifuge-js/src/modules/liquidityPools.ts, centrifuge-js/src/modules/pools.ts
Adds button to update token prices for all deployed liquidity pools of a domain
=> Liquidity Pools: Update token prices

centrifuge-app/src/components/LiquidityTransactionsSection.tsx
=> Updates to Liquidity tab charts

centrifuge-app/.env-config/.env.production
wss://fullnode.parachain.centrifuge.io is currently not connecting, switching to onfinality so that app can load.
=> Switch out self hosted node for onfinality

centrifuge-app/src/components/LiquidityEpochSection.tsx, centrifuge-app/src/pages/Loan/FinanceForm.tsx, centrifuge-app/src/pages/NavManagement/NavManagementAssetTable.tsx, centrifuge-app/src/pages/NavManagement/Overview.tsx, centrifuge-app/src/utils/useLiquidity.tsx, centrifuge-js/src/modules/pools.ts, fabric/src/theme/tokens/colors.ts, fabric/src/theme/tokens/modeLight.ts
Completes the Nav Management drawer, with nav overview card and token price change.
Also fixes some data and data not being refetched in a couple places.
#2045
=> Nav Management Drawer

centrifuge-app/src/pages/IssuerPool/index.tsx
Add the path to the assets detail page. I somehow missed this while working on react-router-dom v6
- [ x ] Dev
=> Fix bug introduce by react-router-dom update

centrifuge-app/src/utils/usePermissions.tsx
Fix withdraw addresses form not setting the right chain in the dropdown initially
=> Fix withdraw address chain

centrifuge-react/src/components/WalletMenu/WalletMenu.tsx
Show "No accounts" message when no accounts are available after connecting
=> Fix wallet connect

centrifuge-app/src/components/LayoutBase/index.tsx
Remove verification status from menu
#2292
=> Remove verification status

centrifuge-app/src/components/PoolCard/PoolStatus.tsx, centrifuge-app/src/components/PoolFilter/index.tsx, centrifuge-app/src/components/PoolList.tsx
- Update pool maker ---> closed
#2293
=> Update maker pool to closed

centrifuge-app/src/pages/Loan/TransferDebtForm.tsx
=> Fix transfer debt for assets without maturity

centrifuge-app/src/components/Report/AssetList.tsx, centrifuge-js/src/modules/pools.ts
=> Fix asset list for LTF

centrifuge-app/src/pages/Pools.tsx
Replace UI component to utilize width
#2291
=> Update pools page layout graph

centrifuge-app/src/utils/tinlake/useTinlakePools.ts
Fix the Asset list for New Silver, where the query was timing out, by reducing the nesting in the subgraph query.
#2326
=> Fix Tinlake Asset list

centrifuge-app/src/pages/IssuerPool/Assets/CreateLoan.tsx
If cash asset selected then maturity date should be open-end <always>
#2332
=> Remove maturity options for cash assets

centrifuge-js/src/modules/pools.ts
=> Fix open orders in liquidity tab

centrifuge-app/src/pages/NavManagement/NavManagementAssetTable.tsx
=> Fix Nav Management table loans not showing

centrifuge-app/src/components/Charts/AssetPerformanceChart.tsx
=> Fix DYF chart

centrifuge-app/src/config.ts
=> Swap Sepolia RPC

centrifuge-app/src/components/Portfolio/usePortfolio.ts, centrifuge-app/src/pages/Prime/index.tsx
Get Prime portfolio balances in a different way, as Subquery isn't returning any balances atm.
=> Fix Prime balances

centrifuge-app/src/components/PoolFees/ChargeFeesDrawer.tsx
Change some text on fees tab 
#2339
=> Change text on fees change drawer

centrifuge-app/src/components/Report/AssetList.tsx, centrifuge-app/src/pages/Loan/ExternalFinanceForm.tsx, centrifuge-app/src/pages/Loan/ExternalRepayForm.tsx, centrifuge-app/src/pages/Loan/FinanceForm.tsx, centrifuge-app/src/pages/Loan/RepayForm.tsx, centrifuge-app/src/pages/Loan/SourceSelect.tsx, centrifuge-app/src/utils/formatting.ts, centrifuge-js/src/modules/pools.ts
=> Asset redesign fixes

centrifuge-app/src/components/Charts/AssetPerformanceChart.tsx
Add decimal formatting to csv on asset list report download ( https://app.centrifuge.io/#/pools/4139607887/assets/14 )
#2351
=> Add formatting to values csv

centrifuge-js/src/CentrifugeBase.ts
=> Fix EVM gas calculations

centrifuge-app/src/components/Charts/CashflowsChart.tsx
=> Change fees in cashflows chart

centrifuge-app/src/utils/useAverageMaturity.ts
=> Fix average asset maturity

centrifuge-app/src/components/Identity.tsx, centrifuge-app/src/pages/IssuerPool/Pricing/OracleFeeders.tsx, centrifuge-js/src/utils/index.ts
Display EVM address if EVM instead of converting and displaying the substrate address
#2364
=> Display evm address

centrifuge-app/src/components/PoolOverview/TransactionHistory.tsx, centrifuge-app/src/components/Tooltips.tsx, centrifuge-app/src/config.ts, centrifuge-app/src/pages/IssuerPool/Configuration/index.tsx, centrifuge-app/src/pages/IssuerPool/Investors/LiquidityPools.tsx, centrifuge-app/src/pages/IssuerPool/Investors/index.tsx, centrifuge-app/src/pages/Loan/PricingValues.tsx, centrifuge-app/src/utils/getLatestPrice.ts, centrifuge-js/src/modules/liquidityPools.ts
=> Improve LP pool setup, fix pricing section, add base sepolia

centrifuge-js/package.json
=> Bump cent-js version

centrifuge-app/src/components/Report/ReportContext.tsx
- Reporting should keep the params (filters) on url
#2372
=> Persist URL on params

centrifuge-app/src/pages/IssuerPool/Assets/CreateLoan.tsx
=> Disable freezing metadata of new assets

centrifuge-js/src/CentrifugeBase.ts
EVM on Cent chain transactions weren't returning events.
[#2375](https://github.com/centrifuge/apps/issues/2375)
=> Fix creating pools with EVM wallets

centrifuge-app/src/utils/getLatestPrice.ts
=> Fix external asset loading: check for errors in latest price

centrifuge-app/src/pages/IssuerPool/Investors/index.tsx
If you are connected with an EVM wallet as the pool admin, and you click Switch to Ethereum Sepolia, the page goes blank, because the account no longer registers as a pool admin. Remember whether the user was admin at some point while on the Investors tab to keep the tab visible
#2377
=> Fix deploying LP tranches with EVM wallet

centrifuge-app/src/components/Portfolio/Transactions.tsx, centrifuge-app/src/components/RouterLinkButton.tsx
- New tab should open instead of redirecting on page (view all transactions, invest drawer component)
#2315
=> Open view all transactions on new tab

centrifuge-app/src/components/LoanList.tsx, centrifuge-app/src/components/PoolOverview/KeyMetrics.tsx
- fixes some console errors
- fixes rendering of tinlake financing date & maturity date (note: Block tower pools don't have maturity dates)
- for tinlake pools: removes asset column and replaces it with NFT-ID to avoid an entirely blank column
[#2368](https://github.com/centrifuge/apps/issues/2368)
=> Fix financing date on Tinlake

centrifuge-app/src/components/Charts/PoolPerformanceChart.tsx
- Remove nav from csv pool performance graph
#2311
=> Remove nav from csv pool performance graph

centrifuge-app/src/components/LoanList.tsx
Remove maturity date from assets list
#2330
=> Remove maturity data from assets table

centrifuge-app/src/pages/IssuerCreatePool/index.tsx
[#2375](https://github.com/centrifuge/apps/issues/2375)
Sorry for the size of the PR!
=> Fix create pool redirect

.github/workflows/npm-publish.yml
This pull request
Upgrade version of NPM publish action since it's using outdated node 12.
=> Update version of NPM publish action

centrifuge-app/src/pages/Loan/ErrorMessage.tsx, centrifuge-app/src/pages/Loan/ExternalFinanceForm.tsx, centrifuge-app/src/pages/Loan/FinanceForm.tsx
=> Asset flow redesign: Add link to access tab and fix withdraw form validation

centrifuge-app/src/pages/Loan/ExternalFinanceForm.tsx, centrifuge-app/src/pages/Loan/ExternalRepayForm.tsx, centrifuge-app/src/pages/Loan/FinanceForm.tsx, centrifuge-app/src/pages/Loan/RepayForm.tsx
=> Revalidate Finance/Repay form after source/destination changes

centrifuge-app/src/components/LiquidityTransactionsSection.tsx
=> Fix investments chart

centrifuge-app/src/pages/IssuerPool/Configuration/EpochAndTranches.tsx
=> Epoch & Tranches: Submit minimal changes

centrifuge-js/src/modules/pools.ts
Check for existing fees before updating metadata
[#2366](https://github.com/centrifuge/apps/issues/2366)
=> Fix duplicate fees

centrifuge-app/src/pages/Loan/KeyMetrics.tsx, centrifuge-app/src/pages/Loan/TransactionTable.tsx
=> Show P&L for DYF

centrifuge-app/src/components/LoanList.tsx
- Conditionally add maturity date for asset list table. If there's at least one asset with maturity date then display the MD, otherwise hide the column.
#2330
=> Conditionally add maturity date

centrifuge-app/src/pages/NavManagement/NavManagementAssetTable.tsx, centrifuge-app/src/pages/NavManagement/Overview.tsx
This pull request... adjust the numbers in the nav management card so that they're dynamic to the imports (feature requested by product)
=> Hotfix: Nav Management dynamic Card

centrifuge-app/src/utils/useAverageMaturity.ts
Exclude cash assets and assets without maturity from the calculation, and round at the end.
=> Fix average maturity

centrifuge-app/src/components/LayoutBase/styles.tsx, centrifuge-app/src/components/PoolCard/index.tsx, centrifuge-app/src/components/PoolList.tsx, centrifuge-app/src/pages/IssuerCreatePool/index.tsx, centrifuge-app/src/pages/IssuerCreatePool/validate.ts, centrifuge-js/src/modules/pools.ts
- Pool card should display 1,2,3,4 depending on screen size
- Remove pool min investment field
- Connect button should be aline with pool title
#2392
#2391
=> Fixes based on feedback

centrifuge-app/src/components/LiquidityEpochSection.tsx
=> Fix collecting orders on epoch closure

centrifuge-app/src/pages/IssuerCreatePool/index.tsx
#[2447](https://github.com/centrifuge/apps/issues/2447)
=> Fix pool creation by removing interest rate from junior (residual) tranche

onboarding-api/env-vars/demo.env, onboarding-api/src/controllers/kyb/verifyBusiness.ts, onboarding-api/src/emails/sendApproveInvestorMessage.ts, onboarding-api/src/emails/sendDocumentsMessage.ts, onboarding-api/src/emails/sendVerifyEmailMessage.ts
Fix redirects for onboarding after frontend implemented hash router
=> Hotfix: Onboarding fix redirects

centrifuge-app/src/components/Charts/PoolPerformanceChart.tsx, centrifuge-app/src/components/Report/DataFilter.tsx, centrifuge-app/src/components/Report/ReportContext.tsx, centrifuge-app/src/components/Report/index.tsx, fabric/src/components/InputUnit/index.tsx, fabric/src/components/TextInput/index.tsx
- Add new data tab 
- Redesign filters 
#2460
=> Add data page redesign

centrifuge-app/src/components/Onboarding/Header.tsx, centrifuge-app/src/pages/Onboarding/CompleteExternalOnboarding.tsx, centrifuge-app/src/pages/Onboarding/EmailVerified.tsx, centrifuge-app/src/pages/Onboarding/UpdateInvestorStatus.tsx, centrifuge-app/src/pages/Onboarding/index.tsx, onboarding-api/src/controllers/kyb/verifyBusiness.ts, onboarding-api/src/emails/sendApproveInvestorMessage.ts, onboarding-api/src/emails/sendDocumentsMessage.ts, onboarding-api/src/emails/sendVerifyEmailMessage.ts
=> Clean up onboarding UI after redesign

centrifuge-app/src/components/Swaps/Orders.tsx
=> Add ConnectionGuard to swaps fulfillment

centrifuge-app/src/pages/NavManagement/NavManagementAssetTable.tsx
=> Update token price of all deployed domains

centrifuge-app/src/components/IssuerSection.tsx, centrifuge-app/src/components/PoolCard/index.tsx, centrifuge-app/src/pages/Pool/Overview/index.tsx, fabric/src/components/Button/WalletButton.tsx
Small changes I noticed while looking at the main branch for the redesign
=> Small fixes

centrifuge-app/src/components/Portfolio/Holdings.tsx, centrifuge-app/src/components/Portfolio/TransferTokensDrawer.tsx
Don't check tranche permissions for native transfer and pass the right key to the transfer extrinsic
=> Fix CFG transfer

centrifuge-js/src/modules/pools.ts
=> fix: pool snapshots query

centrifuge-app/src/components/LoanList.tsx, centrifuge-react/src/components/WalletMenu/ConnectButton.tsx, centrifuge-react/src/components/WalletMenu/WalletMenu.tsx, fabric/src/components/Button/WalletButton.tsx, fabric/src/components/Checkbox/index.tsx
- increase market price  decimals in the table for ongoing assets from 2 to 4
- a filter/way to hide repaid assets. 
#2531
=> Assets feedback

centrifuge-app/src/components/Report/AssetTransactions.tsx
- Update and replace columns/row
#2526
=> Update data asset transations table

centrifuge-react/src/components/WalletProvider/SelectionStep.tsx, centrifuge-react/src/components/WalletProvider/WalletDialog.tsx
- Make whole box clickable and not only arrow icon
- If you are already connected, the dropdown should be open
#2561
=> Updates connect wallet button

centrifuge-app/src/pages/NavManagement/NavManagementAssetTable.tsx
=> Fix reserve value in NAV management

centrifuge-app/src/components/Report/ReportContext.tsx
[#2572](https://github.com/centrifuge/apps/issues/2572)
=> Set initial state date on chart to one year ago today

centrifuge-app/src/components/PoolOverview/TransactionHistory.tsx, centrifuge-app/src/components/Portfolio/Transactions.tsx, centrifuge-app/src/components/Report/AssetTransactions.tsx, centrifuge-app/src/components/Report/DataFilter.tsx, centrifuge-app/src/components/Report/Orders.tsx, fabric/src/components/Positioner/index.tsx, fabric/src/components/Text/index.tsx
- Modify the asset transactions table inside data tab to be similar to how we have the table in Transaction history on the Overview page. We need to have Purchase of X asset, Sale of x asset, Financing of Y asset under the Transaction column
#2526
=> Modify asset transactions table

centrifuge-app/src/components/Portfolio/CardPortfolioValue.tsx, centrifuge-app/src/components/Portfolio/Transactions.tsx, centrifuge-app/src/pages/Prime/Detail.tsx
- Add USD to prime page
- Change color button download
- Fix jumping on table when clicking 'view all'
#2548
=> Add USD to prime page

centrifuge-app/src/pages/IssuerCreatePool/PoolSetupSection.tsx, centrifuge-app/src/pages/IssuerCreatePool/PoolStructureSection.tsx
=> Change font

.github/actions/build-function/action.yml, .github/actions/deploy-gcs/action.yml, .github/actions/deploy-gfunction/action.yml, .github/workflows/centrifuge-app.yml, .github/workflows/fabric.yml, .github/workflows/prod-deploy.yml
=> Update actions artifact versions (v3.x deprecated, using v4.x now)

centrifuge-js/src/modules/liquidityPools.ts
#[2598](https://github.com/centrifuge/apps/issues/2598)
=> Fix claimRedeem contract call

centrifuge-js/src/CentrifugeBase.ts, centrifuge-js/src/types/index.ts
When the calculated gas amount exceeds the max gas limit, it doesn't get set at all and the transaction might fail as a result. 
[#2566](https://github.com/centrifuge/apps/issues/2566)
=> Fix EVM gas limit

centrifuge-app/src/components/Charts/PoolPerformanceChart.tsx, centrifuge-app/src/components/PoolCard/index.tsx, centrifuge-app/src/components/PoolOverview/KeyMetrics.tsx, centrifuge-app/src/components/PoolOverview/TrancheTokenCards.tsx, centrifuge-app/src/pages/Pool/Overview/index.tsx, centrifuge-js/src/modules/pools.ts
=> Use yield since inception for yields

centrifuge-app/src/pages/Pool/Assets/index.tsx
Fix total nav and pending fees values.
=> Fix calculation fees

centrifuge-app/src/components/DebugFlags/config.ts, centrifuge-app/src/pages/NavManagement/NavManagementAssetTable.tsx
Fix error due to `presentValue` being undefined for inactive cash loans
=> Nav Management: Fix error on submission

centrifuge-app/src/components/InvestRedeem/RedeemForm.tsx
Should multiply by the tokenPrice and not div
#2615
=> Fix token amount calculation

centrifuge-app/src/components/Report/BalanceSheet.tsx, centrifuge-app/src/components/Report/CashflowStatement.tsx, centrifuge-app/src/components/Report/DataFilter.tsx, centrifuge-app/src/components/Report/InvestorTransactions.tsx, centrifuge-app/src/components/Report/PoolBalance.tsx, centrifuge-app/src/components/Report/ProfitAndLoss.tsx, centrifuge-app/src/components/Report/ReportFilter.tsx, centrifuge-app/src/components/Report/TokenPrice.tsx
Persist to, from and groupBy filters and fix linter warnings
#2568
=> Persist to, from and groupBy filters and fix linter warnings

.github/workflows/prod-deploy.yml
The deployment of functions for prod was failing:
https://github.com/centrifuge/apps/actions/runs/13414045735
This is due to how the vars.PINNING_API_FUNCT_SA and vars.ONBOARDING_FUNCT_SA is loaded when they are set in the matrix step.
Moved them to be inside the `steps` section where the variables for   `environment: production` are actually set right
Also added some debug to prove that it works withiout deploying the function when in a PR. It is difficult to test production jobs as they would generally only trigger when we want to fully release so I added extra debug stuff to it
=> ci: Fix functions deploy variables for prod

centrifuge-js/src/modules/liquidityPools.ts
=> New CentrifugeRouter address for Mainnet

centrifuge-app/src/components/Charts/PoolPerformanceChart.tsx, centrifuge-app/src/components/Dashboard/Investors/InvestorDrawer.tsx, centrifuge-app/src/components/IssuerSection.tsx, centrifuge-app/src/components/Menu/index.tsx, centrifuge-app/src/components/Portfolio/CardPortfolioValue.tsx, centrifuge-app/src/components/Portfolio/Holdings.tsx, centrifuge-app/src/components/Portfolio/PortfolioValue.tsx, centrifuge-app/src/components/Portfolio/Transactions.tsx, centrifuge-app/src/components/Portfolio/TransferTokensDrawer.tsx, centrifuge-app/src/components/Portfolio/usePortfolio.ts, centrifuge-app/src/pages/Dashboard/AssetsPage.tsx, centrifuge-app/src/pages/Portfolio/TransactionHistory.tsx, centrifuge-app/src/pages/Portfolio/index.tsx, centrifuge-app/src/pages/Prime/Detail.tsx, centrifuge-js/src/modules/pools.ts, centrifuge-js/src/types/subquery.ts
Add new design to portfolio page 
#2547
=> New portfolio page

centrifuge-app/src/components/Dashboard/Access/PoolManagers.tsx, centrifuge-app/src/components/Dashboard/Investors/AddNewInvestorDrawer.tsx, centrifuge-app/src/components/Dashboard/Investors/SupportedNetworksDrawer.tsx, centrifuge-app/src/components/Dashboard/LandingPage/DashboardTable.tsx, centrifuge-app/src/components/Dashboard/LandingPage/PendingMultisigDrawer.tsx, centrifuge-app/src/components/Dashboard/LandingPage/PoolConfigurationDrawer.tsx, centrifuge-app/src/components/PendingMultisigs/index.tsx, centrifuge-app/src/pages/IssuerCreatePool/PoolAnalysisSection.tsx, centrifuge-app/src/pages/IssuerCreatePool/PoolRatings.tsx, centrifuge-app/src/pages/IssuerCreatePool/PoolStructureSection.tsx, centrifuge-app/src/pages/IssuerCreatePool/ServiceProvidersSection.tsx, centrifuge-app/src/pages/IssuerCreatePool/TranchesSection.tsx, centrifuge-app/src/pages/MultisigApproval.tsx, fabric/src/components/RadioButton/index.tsx
=> Dashboard QA

centrifuge-app/src/components/LayoutBase/styles.tsx, centrifuge-app/src/components/Portfolio/CardPortfolioValue.tsx, centrifuge-app/src/components/Portfolio/Holdings.tsx, centrifuge-app/src/pages/Portfolio/index.tsx
=> Enable address debug flag for portfolio testing

centrifuge-app/src/components/LoanList.tsx, centrifuge-app/src/pages/Loan/KeyMetrics.tsx, centrifuge-app/src/pages/Loan/TransactionTable.tsx, centrifuge-app/src/pages/Loan/index.tsx
- Remove unrealized P&L for assets
#2667
=> Remove P&L

centrifuge-app/src/components/LayoutBase/index.tsx, centrifuge-app/src/components/Menu/index.tsx, centrifuge-app/src/pages/Portfolio/index.tsx
=> Fix wallet button

centrifuge-app/src/components/Dashboard/Account/AssetsSection.tsx, centrifuge-app/src/components/LayoutBase/index.tsx, centrifuge-app/src/components/PoolCard/index.tsx, centrifuge-app/src/components/PoolList.tsx, centrifuge-js/src/modules/pools.ts, centrifuge-js/src/utils/Date.ts, fabric/src/components/Button/WalletButton.tsx
Small UI bugs I found while using the app
- Width and height on pool card was odd for smaller screens
- Connect wallet button had too much padding on the right side if no wallet connected 
#2677 
#2672
=> Small UI fixes

.github/workflows/prod-deploy.yml
=> CI: Quick fix for prod functions deploy

centrifuge-app/src/pages/Portfolio/index.tsx
Before tokens were only shown for users with investments, preventing CFG holders from transferring their tokens
[#2678](https://github.com/centrifuge/apps/issues/2678)
=> Portfolio: show tokens for users without investments

centrifuge-app/src/components/Dashboard/Investors/InvestorTable.tsx
=> Investor list: Format address

centrifuge-js/src/modules/pools.ts
Reduce the amount of pools we're fetching data for, because the Demo UI is dying
=> Reduce the amount of pools

centrifuge-app/src/components/Dashboard/Access/AssetOriginator.tsx, centrifuge-app/src/components/Dashboard/LandingPage/AccessDrawer/AssetOriginator.tsx, centrifuge-app/src/components/Dashboard/LandingPage/AccessDrawer/index.tsx, centrifuge-app/src/components/Dashboard/LandingPage/DashboardTable.tsx
- Increase the amount of asset originators an user can add for a pool
https://kflabs.slack.com/archives/C063K04K1F0/p1743770885112039
=> Fix dashboard bugs

centrifuge-app/src/components/Dashboard/Assets/AssetsTable.tsx, centrifuge-app/src/components/Dashboard/Investors/AddNewInvestorDrawer.tsx
- Add validation to check if investor address already exist 
#2685
=> Add address already exist validate

centrifuge-app/src/components/Dashboard/Account/AssetsSection.tsx
This pull request... comments out attestation signing temp.
=> Temp remove attestation

centrifuge-app/src/components/Charts/PoolPerformanceChart.tsx, centrifuge-app/src/components/Charts/SimpleBarChart.tsx, centrifuge-app/src/components/Report/BalanceSheet.tsx, centrifuge-app/src/components/Report/ReportFilter.tsx, centrifuge-app/src/components/Report/utils.tsx
- Timestamp was taking local timezone instead of UTC for UI display
=> Fix reports timestamp

centrifuge-app/src/components/Dashboard/Investors/AddNewInvestorDrawer.tsx
- PoolId does not longer exist on formik.values causing the error
=> Fix bugs on adding new investor

centrifuge-app/src/components/Charts/PoolPerformanceChart.tsx, centrifuge-app/src/components/Dashboard/Investors/AddNewInvestorDrawer.tsx, centrifuge-app/src/components/Dashboard/Investors/InvestorTable.tsx, centrifuge-app/src/components/Dashboard/utils.ts, centrifuge-app/src/components/PoolCard/index.tsx, centrifuge-app/src/components/PoolOverview/KeyMetrics.tsx, centrifuge-app/src/components/PoolOverview/TrancheTokenCards.tsx, centrifuge-app/src/pages/Dashboard/InvestorsPage.tsx, centrifuge-app/src/pages/IssuerCreatePool/PoolDetailsSection.tsx, centrifuge-app/src/pages/Pool/Overview/index.tsx
- Change APY
- Fix bug on whitelisted investor not checking on centrifuge addresses
- Error message color should be green for existing investors
=> Change apy

centrifuge-app/src/components/Dashboard/LandingPage/AccessDrawer/AssetOriginator.tsx
Fix the validation for withdraw addresses
=> Fix withdraw address validation

centrifuge-app/src/components/Dashboard/LandingPage/AccessDrawer/index.tsx
Form submission broke when the admin debug section was not shown
=> Fix access drawer form submission

centrifuge-app/src/components/Dashboard/Account/AssetsSection.tsx
Was accidentally disabled when the attestation was commented out
=> Update portfolio valuation in batch

centrifuge-app/src/components/Dashboard/utils.ts, centrifuge-app/src/components/PoolCard/index.tsx, centrifuge-app/src/components/PoolOverview/KeyMetrics.tsx, centrifuge-app/src/components/PoolOverview/TrancheTokenCards.tsx, centrifuge-app/src/pages/Pool/Overview/index.tsx
- On the latest release we sent some hardcoded code to for a super quick fix. This is a cleanup to remove the hardcoded parts and to make sure when we release a new pool it will work as expected.
- Fix some bugs when launching new pool 
#2716
#2717
=> Cleanup minInv & apy

centrifuge-app/src/components/Dashboard/LandingPage/PoolConfigurationDrawer.tsx, centrifuge-app/src/components/PoolCard/index.tsx, centrifuge-app/src/components/PoolOverview/KeyMetrics.tsx, centrifuge-app/src/pages/IssuerCreatePool/TranchesSection.tsx
- Add Weighted Average Maturity
#2712
=> Add Weighted Average Maturity

.github/workflows/prod-deploy.yml
This pull request fixes a situation where the slack notify job will trigger both failure and success regardless of the status of the deployment jobs
This runs only when deploying to PROD by promoting a release
=> Fix the notifications for prod deploys

centrifuge-app/src/components/Dashboard/LandingPage/PoolConfigurationDrawer.tsx
Fixes the configuration overriding certain pool metadata fields, like `adminMultisig`
=> Fix configuration form

centrifuge-app/src/components/Dashboard/Account/AssetsSection.tsx
- Remove a dup tx to close epoch when updating nav
=> Remove dup close epoch tx

centrifuge-app/src/components/Dashboard/Investors/AddNewInvestorDrawer.tsx, centrifuge-app/src/components/Portfolio/TransferTokensDrawer.tsx, centrifuge-app/src/utils/usePermissions.tsx
Fix checking whether the investor is already part of the memberlist
=> Fix investor memberlist check

centrifuge-app/src/components/PoolOverview/KeyMetrics.tsx, centrifuge-app/src/pages/IssuerCreatePool/TranchesSection.tsx, centrifuge-js/src/modules/pools.ts
=> Fix average maturity instead of percentage should just be a number

centrifuge-app/src/components/LoanList.tsx
- Subquery is not returning data but we had the data already from onchain
=> Fix asset list

centrifuge-js/src/modules/pools.ts
=> Hide for now

centrifuge-app/src/components/Dashboard/LandingPage/IssuerDetailsSection.tsx, centrifuge-app/src/components/Dashboard/LandingPage/PoolConfigurationDrawer.tsx, centrifuge-app/src/pages/IssuerCreatePool/utils.ts
- fix bugs when trying to update metadata
=> Fix bugs when updating metadata

centrifuge-app/src/components/Dashboard/LandingPage/AssetsCsvUpload.tsx, centrifuge-app/src/components/Dashboard/LandingPage/PoolConfigurationDrawer.tsx, centrifuge-app/src/components/IssuerSection.tsx, centrifuge-app/src/components/LoanList.tsx, centrifuge-app/src/pages/Pool/Overview/HoldingsTable.tsx, centrifuge-app/src/pages/Pool/Overview/index.tsx, centrifuge-js/src/modules/pools.ts
- Add ability to upload csv to metadata 
-  add table to display data
#2735
=> Add ability to upload csv to metadata

centrifuge-js/src/modules/liquidityPools.ts
=> Update router addresses

centrifuge-app/src/pages/Portfolio/CFGTokenMigrationCent.tsx, centrifuge-app/src/pages/Portfolio/index.tsx
- Add migration banner to migrate page
=> add migration banner to migrate page

centrifuge-app/src/components/Dashboard/Account/OnchainSection.tsx, centrifuge-app/src/components/Dashboard/LandingPage/AccessDrawer/OracleFeeders.tsx
- Use liquidity hook instead of subquery
- Update oracle collection when adding a feeder to avoid issues with nav
=> Fix pending redemption and investment

centrifuge-app/src/pages/Portfolio/useTokenBalance.tsx
When changing wallets with different providers within the portfolio it was not updating the balance.
=> Fix caching

centrifuge-app/src/pages/Portfolio/CFGTokenMigration.tsx, centrifuge-app/src/pages/Portfolio/CFGTokenMigrationCent.tsx, centrifuge-app/src/pages/Portfolio/useTokenBalance.tsx, centrifuge-react/src/components/WalletProvider/ConnectionGuard.tsx
* Fix getting EVM provider
* Add Connect/Switch button to form
=> Fix Migrate pages breaking when no wallet connected

centrifuge-app/src/pages/Portfolio/index.tsx
=> fix: bug on banner

centrifuge-app/src/components/PoolList.tsx
=> fix: pool list layout

centrifuge-app/src/components/Report/useReportsQuery.tsx
=> Fix subquery URL on reports

centrifuge-app/src/components/Dashboard/Assets/UploadAssetTemplateForm.tsx
=> fix_assets_template

centrifuge-app/src/components/DebugFlags/config.ts, centrifuge-app/src/components/LayoutBase/index.tsx, centrifuge-app/src/components/Menu/index.tsx, centrifuge-app/src/pages/Pools.tsx
=> fix: debug flag name
