centrifuge/apps

- tinlake-ui/components/Loan/List/index.tsx
- tinlake-ui/components/OnboardModal/index.tsx
- tinlake-ui/components/Overview/index.tsx
- tinlake-ui/components/PoolTitle/index.tsx
- tinlake-ui/components/TINRatioBar/index.tsx
- tinlake-ui/components/TinlakeExplainer/index.tsx
- tinlake-ui/components/Tooltip/index.tsx
- tinlake-ui/containers/Investment/View/EpochOverview.tsx
- tinlake-ui/containers/Investment/View/InvestmentOverview.tsx
- tinlake-ui/containers/Investment/View/TrancheOverview.tsx
- tinlake-ui/containers/Investment/View/index.tsx
- tinlake-ui/pages/pool/[root]/[slug]/assets/index.tsx
- tinlake-ui/pages/pool/[root]/[slug]/demo/value-nft.tsx
> feat(tinlake-ui): fix tin ratio bar flickering, add pool titles, add loan empty state

- tinlake-ui/components/Header/index.tsx
- tinlake-ui/config.ts
- tinlake-ui/containers/Portfolio/index.tsx
- tinlake-ui/ducks/portfolio.ts
This pull request implements the [`multicall.js`](https://github.com/makerdao/multicall.js) library for the `/portfolio` page in order to get real time data rather than just the daily updates from the subgraph.
I used `any[]` type on [here](https://github.com/centrifuge/apps/compare/use-multicall-on-portfolio#diff-0a9ef8b7e0d47f2972a9b22bf5c91b8a05e3e4cdec0f95c7f242c370ac075dbaR106) and [here](https://github.com/centrifuge/apps/compare/use-multicall-on-portfolio#diff-0a9ef8b7e0d47f2972a9b22bf5c91b8a05e3e4cdec0f95c7f242c370ac075dbaR120) because there seems to be a problem with the way that `multicall.js` ships their types. There is currently a [pull request](https://github.com/makerdao/multicall.js/pull/29) raised on the `multicall.js` repo to fix the issue.
[Staging …
> feat: implement multicall for portfolio page

- .github/workflows/tinlake-ui-deploy-to-dev.yml
- .github/workflows/tinlake-ui-deploy-to-prod.yml
- .github/workflows/tinlake-ui-deploy-to-staging.yml
- tinlake-ui/components/Auth/index.tsx
- tinlake-ui/ducks/auth.ts
Was getting this runtime error since `useQueryDebugEthAddress` was being used inside a `thunk` which goes against React's [rules of hooks](https://reactjs.org/docs/hooks-rules.html#only-call-hooks-from-react-functions) can only be used in function components.
I refactored to move the implementation to the `Auth` component which passes the hook's return data to the `thunk`.
Also slipped in a few ci tweaks 😉
> fix: hook use in thunk

- tinlake-ui/components/PoolsMetrics/index.tsx
- tinlake-ui/ducks/rewards.ts
- tinlake-ui/services/apollo/index.ts
This pull requests adds the AO rewards to the investor rewards amount on the dashboard page.
**NOTE:** This functionality will not work on `Kovan` or `mainnet` until the latest version of the subgraph that contains the [toDateAORewardAggregateValue](https://github.com/centrifuge/tinlake-subgraph/blob/39558c47e892ac7b2825c6a051a9925567d59a04/schema.graphql#L187) property is deployed. Otherwise, the dashboard will render with `0.0000 CFG`:
> feat: add AO rewards to investor rewards

- tinlake-ui/components/TinlakeExplainer/index.tsx
This pull request updates the link on the `Read more about Tinlake` button under `Learn more` on the homepage.
> fix: docs link

- tinlake-ui/containers/Investment/View/EpochOverview.tsx
This pull request hides the `Close epoch` button on the investment page unless the user is either the pool admin or uses query params (`?show_close_epoch=true`) in the url.
[Preview link with query params](https://pr-249--dev-tinlake.netlify.app/pool/0x25dF507570c8285E9c8E7FFabC87db7836850dCd/new-silver-2/investments?show_close_epoch=true)
Addresses the `MUST HAVE`s of #235
> feat: conditionally render "Close epoch" button

- tinlake-ui/services/apollo/index.ts
This pull request increases the query response from the default of 100 to an explicit 1000.
Closes #257
> fix: increase loans query amount to 1000

- tinlake-ui/containers/Investment/View/EpochOverview.tsx
- tinlake-ui/containers/Investment/View/index.tsx
- Adds more dependencies to the `useEffect` that executes the `loadPool` `thunk` in order to refetch the pool when changes to the epoch flow are made
- Adds another `case` to the `EpochButton` component to show a `disabled` `Close epoch` `button` for when an epoch is `open`
Two caveats:
1. Sometimes it can take absurdly long to eventually rerender to the proper view like (5-10 seconds)
2. For the flow where closing the epoch is automatically executed, the UI does not properly rerender once the 5 minutes pass to go from `Lock DAI` -> `Epoch Executed`.
Closes #235
> fix: properly update ui on closing epoch flow

- tinlake-ui/ducks/transactions.ts
Don't hide pending transactions after a timeout, but keep them visible until they succeed or fail.
Closes #143
> always show pending transations

- tinlake-ui/containers/CentChainWalletDialog/index.tsx
- tinlake-ui/containers/Investment/View/RedeemCard.tsx
- tinlake-ui/containers/SetCentAccount/index.tsx
This pull request adds warning messages for investors that are redeeming before linking their cent chain addresses.
The info blocks do not have the yellow background with the full-width style because I used the `Alert` component that is already used throughout the app. If we want to change the alert style, we should probably do it for all alerts to remain consistent.
Closes #254
> fix: add warning messages for redemptions

- tinlake-ui/containers/Loan/Borrow/index.tsx
- tinlake-ui/containers/Loan/Issue/index.tsx
- tinlake-ui/containers/Loan/Repay/index.tsx
- tinlake-ui/pages/pool/[root]/[slug]/assets/index.tsx
Fixes (i), (ii) and (iii) of #144 
(i) Show "Lock NFT" button only when account is pool admin, has a proxy, or `lockNFT` query param is set.
(ii) Adds success feedback for locking NFT
(iii) Hide "Repay" button when you can borrow, hide "Finance" button when you can't.
Closes #109
> Asset tab UI tweaks

- tinlake-ui/ducks/loans.ts
Checks if loan NFT is burned before checking if the collateral NFT is in the SHELF contract
Closes #253
> Fix loan status bug if NFT is locked again

- tinlake-ui/containers/Loan/Issue/index.tsx
- tinlake-ui/pages/pool/[root]/[slug]/assets/issue.tsx
- tinlake-ui/services/tinlake/actions.ts
Disabled the Lock NFT button when the owner of the NFT isn't the connected address.
Also fixes the error messages that were not being displayed.
Closes #67
> Prevent borrower from Locking NFT that is not in his wallet

- gateway/packages/ui/src/documents/AttributeField.tsx
Now leaves timezone info intact when passing the date
> Gateway: fix incorrect date in date input

- tinlake-ui/package.json
- tinlake-ui/static/wallet/copy.svg
- yarn.lock
Contributes to https://github.com/centrifuge/apps/issues/363
> chore(tinlake-ui): change copy icon

- .github/workflows/tinlake-ui-deploy-to-dev.yml
- .github/workflows/tinlake-ui-deploy-to-prod.yml
- .github/workflows/tinlake-ui-deploy-to-staging.yml
- .github/workflows/tinlake-ui-pull-request.yml
- tinlake-ui/README.md
This pull request refactors the Github Actions config to deploy pull requests to both `kovan` and `mainnet`. Also, deploys `main` branch to both `kovan` and `mainnet` as well.
> ci: deploy pr to mainnet

- tinlake-ui/components/Header/index.tsx
Closes [#371](https://github.com/centrifuge/apps/issues/371)
> #371 hide rewards when wallet is not connected

- tinlake-ui/components/Overview/index.tsx
- tinlake-ui/containers/Investment/View/InvestmentOverview.tsx
- tinlake-ui/containers/Investment/View/styles.tsx
- tinlake-ui/public/static/tooltips.json
This pull request applies the following design changes to the Poostatus section of the Pool overview page:
- Remove connection between asset and investment side and display both as columns
- New Title of section: "Pool Status"
- Asset side:
- Add Titles: Asset & Liquidity
- Rows under Assets
- Remove average financing amount
- Rows under Liquidity
- Remove Reserve
- Add Available Liquidity calculated as Available Liquidity = Reserve + Available Credit Line for Maker pools and Available Liquidity = Reserve for non-Maker pools
- Rename Reserve Ratio to Cash drag
- Token/Investment side
- Remove tranche values
- Remove the % from the token price in the Drop component
Closes #428
Tinlake UI, Pool overview page
> Update pool status view

- tinlake-ui/containers/Investment/View/InvestmentOverview.tsx
This pull request fixes the percentage of Junior held by provider, shown in the investment overview page
Closes #499
Pool overview page
> Fix percentage of Junior held by provider in investment overview

- .github/workflows/fabric-publish.yml
- fabric/README.md
Change the Github Action for publishing Fabric to happen when a tag is pushed
> Fabric: change when publish happens

- centrifuge-js/src/index.ts
- centrifuge-js/src/modules/utils.ts
- centrifuge-js/src/utils/index.ts
- moving static utils methods to `utils/index.ts`
- exporting all methods in `utils/index.ts` as named exports from the `@centrifuge/centrifuge-js` package
- also keep the methods as instance methods in the `utils` module
> feat(centrifuge-js): expose static utils as named exports

- .github/workflows/fabric-publish.yml
- fabric/CHANGELOG.md
- fabric/package.json
Publishes the first version of Fabric. `yarn publish` didn't work, so replacing it with `npm publish`
> Fabric: publish first version and fix Github Action

- .github/workflows/tinlake-ui-deploy-to-dev.yml
- .github/workflows/tinlake-ui-deploy-to-prod.yml
- .github/workflows/tinlake-ui-deploy-to-staging.yml
- .github/workflows/tinlake-ui-pull-request.yml
- tinlake-ui/.env.mainnet-example
- tinlake-ui/containers/ClaimRewards/index.tsx
- tinlake-ui/containers/UserRewards/index.tsx
- tinlake-ui/services/apollo/index.ts
- tinlake-ui/utils/hooks.ts
- tinlake-ui/utils/usePortfolio.ts
This pull request swaps the subgraph out for the newest version which splits the CFG reward rate into two separate reward rates. One for DROP investments and one for TIN investments. This PR also updates the UI accordingly.
> Swap in split rewards subgraph

- .github/workflows/changelog-generator.yml
This pull request fixes the (currently broken) automatic changelog generation when merging to the `main` branch. The issue was due to an external update, requiring `io-events` to use ruby >= 3.
The PR updates to ruby 3.1.
Here is the resulting changelog: https://github.com/centrifuge/apps/blob/changelog/CHANGELOG.md
Changelog generation
> Fix changelog

- fabric/src/components/Toast/index.tsx
- nft-studio/src/components/TransactionToasts.tsx
This pull request introduces 2 changes:
- The transaction toasts will be shown only after signing / canceling the transaction (pending / success / fail)
- The success / failure toasts will dismiss automatically after 5 secs
Closes #655
> Transaction toasts changes

- fabric/src/components/Card/index.ts
- fabric/src/theme/tokens/modeDark.ts
- fabric/src/theme/tokens/modeLight.ts
- nft-studio/lambda/pinCollectionMetadata.js
- nft-studio/lambda/pinFileWithMetadata.js
- nft-studio/src/components/CollectionCard.tsx
- nft-studio/src/components/CreateCollectionDialog.tsx
- nft-studio/src/components/NFTCard.tsx
- nft-studio/src/components/TextWithPlaceholder.tsx
- nft-studio/src/components/VisibilityChecker.tsx
- nft-studio/src/pages/Collection.tsx
- nft-studio/src/pages/MintNFT.tsx
- nft-studio/src/pages/NFT.tsx
* Change input background color
* Fix vertical line on NFT page
* Fix NFT width on NFT page
* Add text placeholders while metadata is loading
* Load metadata in cards on intersection with the viewport
* Tweak NFT count background color in collection card
* Add border around collection logo
* Add title and collection link to Mint NFT page
* Check file size in Netlify functions
> NFT Studio: Styling tweaks

- fabric/src/components/FileUpload/index.tsx
- fabric/src/utils/useControlledState.ts
- fabric/src/utils/useEventCallback.ts
- fabric/src/utils/usePrevious.ts
- nft-studio/public/index.html
- nft-studio/src/components/CollectionCard.tsx
- nft-studio/src/components/CreateCollectionDialog.tsx
- nft-studio/src/pages/MintNFT.tsx
- nft-studio/src/pages/NFT.tsx
When in the Create Collection dialog and going to the Terms dialog and back, the collection logo wasn't being saved. Changes the Fabric FileUpload component so that it's state can optionally be controlled via props.
NFT Playground, Fabric
> NFT Playground: Save collection logo when switching dialogs

- centrifuge-js/src/modules/pools.ts
- nft-studio/src/components/Charts/CustomChartElements.tsx
- nft-studio/src/components/Charts/PoolAssetReserveChart.tsx
- nft-studio/src/components/Charts/ReserveCashDragChart.tsx
- nft-studio/src/components/Charts/RiskGroupSharesPieChart.tsx
- nft-studio/src/components/DataTable.tsx
- nft-studio/src/components/DataTableGroup.tsx
- nft-studio/src/components/EpochList.tsx
- nft-studio/src/components/InvestRedeem.tsx
- nft-studio/src/components/RiskGroupList.tsx
- nft-studio/src/components/Tooltips.tsx
- nft-studio/src/pages/PoolDetail/Header.tsx
- nft-studio/src/pages/PoolDetail/LiquidityTab/index.tsx
- nft-studio/src/pages/PoolDetail/OverviewTab/index.tsx
- nft-studio/src/utils/date.ts
- Adds liquidity tab to public pool
- refactors custom chart components for easier reuse
It does not include calculation for 30d sum as they are not yet available via subquery
Tickets:
#713
#710 (missing some values in the summary b/c they are not available on subgraph yet)
#824
> firefox messed up the screenshot 😱 
nft-studio
> Centrifuge App: Pool detail liquidity tab

- tinlake-ui/services/centChain/index.ts
This pull request refactors the `claimCFGRewards` function to use `signAndSend` instead of just `send`. This will require the user to sign the transaction.
This pull request impacts CFG reward claiming.
> chore: refactor to use signAndSend

- centrifuge-app/src/components/InvestRedeem.tsx
- centrifuge-app/src/components/InvestmentsList.tsx
- centrifuge-app/src/pages/Pools.tsx
- centrifuge-app/src/pages/Tokens.tsx
- centrifuge-js/src/CentrifugeBase.ts
- centrifuge-js/src/modules/pools.ts
- centrifuge-js/src/utils/web3.ts
Get token prices via RPC so they're more up to date. We currently get them from the latest epoch, so it's usually out of date. It needs to do a rpc call per pool. It does this in parallel with the rest of the pool data, but allows the pool to emit it's first value without having to wait for all the requests to finish. A side-effect of this is that `tokenPrice` can be `null` in the returned data and you can visually see the TVL increase as data loads on the Pools/Tokens page.
CentrifugeJS, Centrifuge App
> Centrifuge App: Get token prices via RPC

- centrifuge-app/src/components/Dialogs/SellDialog.tsx
- centrifuge-app/src/components/InvestRedeem.tsx
- centrifuge-app/src/components/MaxReserveForm.tsx
- centrifuge-app/src/components/RiskGroupList.tsx
- centrifuge-app/src/pages/CreateLoan.tsx
- centrifuge-app/src/pages/IssuerCreatePool/index.tsx
- centrifuge-app/src/pages/Loan/FinanceForm.tsx
- centrifuge-app/src/pages/Loan/PricingForm.tsx
- centrifuge-app/src/pages/Loan/RiskGroupValues.tsx
- centrifuge-app/src/pages/Loan/index.tsx
- centrifuge-app/src/pages/Loans.tsx
- centrifuge-app/src/pages/PoolDetail/AssetsTab/index.tsx
- centrifuge-app/src/pages/Pools.tsx
- centrifuge-app/src/pages/Tokens.tsx
- centrifuge-app/src/utils/formatting.ts
- centrifuge-app/src/utils/validation/index.ts
- centrifuge-js/src/modules/pools.ts
- fabric/src/components/CurrencyInput/CurrencyInput.stories.tsx
- fabric/src/components/CurrencyInput/index.tsx
- updates all currency inputs with thousand separator
- invest form (with max button)
- redeem form (with max button)
- finance form (with max button)
- repay form (with max button)
- create pool --> initial max reserve field
- price asset --> collateral value field
- sell asset --> price field
- rounds max button input down to 2 decimal places
- adds decimals to invest/redeem/finance/repayment forms to avoid losing precision on max button press
- fixes some broken (back)links
- removes the `=` in the pricing form (#874)
- implements change requests in #846 and #844
- allows financing after the asset has been fully financed and repaid (#886) 
#846 
#844
#874
#886
> Centrifuge App: Fix finance and repayment forms

- centrifuge-js/src/modules/pools.ts
Checks for more events when refetching pools, so pools now also get refetching when the max reserve gets set, the epoch is closed, etc.
Centrifuge App
> Centrifuge App: Fix pools refetching

- tinlake-bot/src/index.ts
This PR removes the tinlake bot's "close pool" cron job.
> Fix: Remove close pools cron job from bot

- centrifuge-app/src/components/InvestRedeem.tsx
- centrifuge-app/src/react-app-env.d.ts
- centrifuge-app/src/utils/useCentrifugeTransaction.ts
- centrifuge-app/src/utils/useTransactionFeeEstimate.ts
- centrifuge-js/src/CentrifugeBase.ts
This pull request... 
- stops the transaction before signing if the native balance is too low. It sends error message into toast (before `sendAndSign` is called on any tx, we make sure the native token balance is greater than the estimated fee)
- adds the possibility to get the tx fee from `useCentrifugeTransaction` so it can be displayed to the user. For now I've only implemented it in the invest form.
#929
> CentrifugeJS: Add error handling for insufficient native balances

- centrifuge-app/.gitignore
Removes all not used references to .env files. These were confusing to me, as we only use one single .env file. .env is ignored already on root level of the mono repo, but leaving it in place to make sure it will never end up getting pushed.
> removes not used .env.*  references

- .github/actions/prepare-deploy/action.yml
- .github/workflows/centrifuge-app.yml
- .github/workflows/demo-deploys.yml
- .github/workflows/fabric.yml
- .github/workflows/faucet-api.yml
- .github/workflows/npm-publish.yml
- .github/workflows/onboarding-api.yml
- .github/workflows/pinning-api.yml
- .github/workflows/prepare-pr.yml
Fixing PR open/close jobs:
P.S: Added some last minute changes to try to fix the manual jobs (deploy to demo and npm-publish)
> Gh actions/fix pr workflow

- .github/workflows/demo-deploys.yml
- .github/workflows/faucet-api.yml
* Include Faucet-api when deploying to demo
* Force deployment to demo regardless of deploy_to var passed to faucet-api (deploy only demo and dev)
> GH Actions: Include Faucet API on demo deploys

- centrifuge-app/src/components/InvestRedeem/InvestRedeem.tsx
- centrifuge-app/src/components/PageWithSideBar.tsx
- centrifuge-react/src/components/WalletProvider/ConnectionGuard.tsx
- always displays the invest card in the sidebar of the pool overview page with corresponding text in the button
- hides faucet card when user is connected to EVM wallet or viewing a Tinlake pool
> always show invest card in sidebar

- centrifuge-app/src/components/LabelValueStack.tsx
- centrifuge-app/src/components/PoolCard.tsx
After adding a tooltip to Ethereum icon (if pool is eth based), the html was invalid because of a button being nested inside a button
Solution
- refactor `PoolCard` to be dedicated component -> decided against extending `InteractiveCard` to keep the complexity low and be able to define proper html tags
- `PoolCard` navigates now with a Link and not a button
- extends `LabelValueStack` to accept 'as' render props -> enable proper html tags
- tab focus now shows as outline around '>' icon
> refactor PoolCard

- centrifuge-app/src/components/Charts/ReserveCashDragChart.tsx
- centrifuge-app/src/pages/Pool/Liquidity/index.tsx
Partly resolves: [1270](https://github.com/centrifuge/apps/issues/1270)
- display ReserveCashDragChart as last section in this view
- refactors ReserveCashDragChart to default function export -> React.VFC is deprecated / no need for additional typing
> Change section order on PoolLiquidity view

- .github/README.md
- onboarding-api/src/controllers/agreement/getUnsignedAgreement.ts
- onboarding-api/src/utils/annotateAgreementAndSignAsInvestor.ts
This pull request temporarily configures cent app to fetch for a generic subscription agreement from the Google bucket. Right now, all of the pool/tranche specific documents are identical anyway. Until we are ready to release the app or until we automate the subscription agreement upload step, then I don't think we are ready to have pool/tranche specific subscription agreements. It is just making it unnecessarily painful for testing.
> fetch for generic subdoc link

- centrifuge-app/src/config.ts
New asset class `Trade Finance` for the Defactor pool
Issue: https://github.com/centrifuge/apps/issues/1336
> 'Trade Finance' asset class

- centrifuge-app/src/components/MaxReserveForm.tsx
- centrifuge-app/src/pages/IssuerPool/Liquidity/index.tsx
- centrifuge-app/src/pages/Pool/Liquidity/index.tsx
- use actual pool max reserve as initial value
- enable `formik` to update initial value when pool params are updated -> `enableReinitialize`
- solve ui and code being out of sync: ui displays max reserve value, but `formik` value is `''` (invalid number error thrown -> see screenshot) 
- `MaxReserveForm` checks internally if for 'liquidity admin' right -> removes equal checks higher in the application tree
- React.VFC deprecated -> use React.FC
> Refactor MaxReserveForm

- centrifuge-app/src/components/LoanList.tsx
In the assets tab, there is an amount and status column and both display the same status of the asset. This ticket removes the duplicate.
issue: https://github.com/centrifuge/apps/issues/1304
> removes status labels

- centrifuge-app/src/components/DebugFlags/config.ts
- centrifuge-app/src/pages/Onboarding/queries/useVerifyBusiness.ts
- set dryRun to false by default
- adds debug option to toggle dryRun
Issue: https://github.com/centrifuge/apps/issues/1351
> Refactors dryRun option

- centrifuge-app/.env-config/.env.development
- centrifuge-app/src/utils/tinlake/useTinlakePools.ts
This pull request fixes the broken asset lists by switching the subgraph query to get loans via pools instead of querying all loans and filtering by pools. For some reason the latter is incredibly slow. Affected pools are NS2 and Branch 3, but this should speed up asset list querying across the board.
> Fix Asset Lists

- centrifuge-app/src/components/LoanLabel.tsx
- centrifuge-app/src/components/LoanList.tsx
- centrifuge-app/src/components/Report.tsx
- centrifuge-app/src/config.ts
- centrifuge-app/src/pages/IssuerCreatePool/validate.ts
- centrifuge-app/src/pages/IssuerPool/Assets/CreateLoan.tsx
- centrifuge-app/src/pages/IssuerPool/Assets/PricingInput.tsx
- centrifuge-app/src/pages/Loan/FinanceForm.tsx
- centrifuge-app/src/pages/Loan/PricingValues.tsx
- centrifuge-app/src/pages/Loan/index.tsx
- centrifuge-app/src/pages/Pool/Assets/index.tsx
- centrifuge-app/src/utils/useLoans.ts
- centrifuge-app/src/utils/validation/index.ts
- centrifuge-js/src/modules/pools.ts
This pull request implements the ability to create an asset with the valuation type as `oracle`.
Closes #1458
> feat: implement oracle UI

- centrifuge-js/src/modules/pools.ts
Error thrown because of missing 'normalizedDebt' for loan data of type ActiveLoanData:
- adds 'normalizedDebt' to ActiveLoanData > pricing > internal (as returned from 'api.query.loans.activeLoans()'
- refactor 'getOutstandingDebt' to get retrieve 'normalizedDebt' from internals
test on pool: 4285291163
> fix Error: getLoans normalizedDept

- centrifuge-app/src/components/LiquidityRewards/LiquidityRewardsProvider.tsx
- centrifuge-app/src/components/TinlakeRewards/ClaimTinlakeRewards.tsx
- centrifuge-app/src/components/TinlakeRewards/utils.test.ts
- centrifuge-app/src/components/TinlakeRewards/utils.ts
- centrifuge-app/src/utils/tinlake/useTinlakePortfolio.ts
- centrifuge-app/src/utils/tinlake/useTinlakeRewards.ts
- centrifuge-app/vite.config.ts
> Centrifuge App: Fix Tinlake rewards claiming

- centrifuge-app/src/components/DebugFlags/DebugFlags.tsx
- centrifuge-app/src/components/DebugFlags/components/ConvertEvmAddress.tsx
- centrifuge-app/src/components/DebugFlags/config.ts
Adds a button to the debug panel to convert an EVM address to their respective Substrate address for a given EVM chain.
> Centrifuge App: Convert EVM address to Subtrate

- centrifuge-app/src/pages/Onboarding/queries/useSignRemark.ts
- onboarding-api/src/controllers/auth/authenticateWallet.ts
- onboarding-api/src/database/index.ts
- onboarding-api/src/utils/networks/centrifuge.ts
- onboarding-api/src/utils/networks/evm.ts
- onboarding-api/src/utils/types.d.ts
When onboarding with evm on cent chain, if your DEVEL balance is too low we now pay for the remark signing tx.
> OnboardingAPI: Implement faucet for remark signing evm on cent chain

- centrifuge-js/src/modules/pools.ts
> CentrifugeJS: Loan present value

- centrifuge-js/src/modules/pools.ts
> CentrifugeJS: Fix currencies

- centrifuge-app/src/components/PoolCard/PoolStatus.tsx
- centrifuge-app/src/components/PoolCard/index.tsx
- centrifuge-app/src/components/PoolFilter/SortButton.tsx
- centrifuge-app/src/components/PoolFilter/index.tsx
- centrifuge-app/src/pages/Pools.tsx
This pull request adds the two upcoming pools, New Silver Series 3 and Flowcarbon Nature Offsets Series 2.
Closes #1582
> add upcoming pools

- centrifuge-app/src/pages/IssuerPool/Assets/CreateLoan.tsx
- centrifuge-app/src/pages/IssuerPool/Assets/PricingInput.tsx
- centrifuge-app/src/pages/Loan/FinancingRepayment.tsx
- centrifuge-app/src/pages/Loan/TransactionTable.tsx
- centrifuge-app/src/pages/Loan/index.tsx
- centrifuge-app/src/utils/usePools.ts
> Fix internal assets

- centrifuge-app/src/components/AssetSummary.tsx
- centrifuge-app/src/components/LoanLabel.tsx
- centrifuge-app/src/components/LoanList.tsx
- centrifuge-app/src/components/PageSection.tsx
- centrifuge-app/src/components/PageSummary.tsx
- centrifuge-app/src/components/Report/AssetList.tsx
- centrifuge-app/src/components/Tooltips.tsx
- centrifuge-app/src/pages/IssuerCreatePool/validate.ts
- centrifuge-app/src/pages/IssuerPool/Assets/CreateLoan.tsx
- centrifuge-app/src/pages/IssuerPool/Assets/PricingInput.tsx
- centrifuge-app/src/pages/Loan/ExternalFinanceForm.tsx
- centrifuge-app/src/pages/Loan/FinancingRepayment.tsx
- centrifuge-app/src/pages/Loan/HoldingsValues.tsx
- centrifuge-app/src/pages/Loan/OraclePriceForm.tsx
- centrifuge-app/src/pages/Loan/PricingValues.tsx
- centrifuge-app/src/pages/Loan/TransactionTable.tsx
- centrifuge-app/src/pages/Loan/index.tsx
- centrifuge-app/src/pages/Pool/Assets/index.tsx
- centrifuge-app/src/utils/date.ts
- centrifuge-app/src/utils/getLatestPrice.ts
- centrifuge-app/src/utils/usePools.ts
- centrifuge-app/src/utils/validation/index.ts
- centrifuge-js/src/modules/pools.ts
- centrifuge-js/src/types/subquery.ts
This pull request implements the oracle-v2 work to support the shadow pool.
Related work that will be done in a follow up pull request:
- Add `Export` functionality to the `Transaction history` table
- Add external anchor link to each transaction in the `Transaction history` table
Closes #1502
> feat: implement oracle-v2

- centrifuge-app/src/components/PoolsTokensShared.tsx
- centrifuge-app/src/components/PortfolioCta/index.tsx
- centrifuge-app/src/utils/useLoans.ts
> Centrifuge App: Remove accrued interest from portfolio card

- centrifuge-app/src/pages/Loan/FinanceForm.tsx
- centrifuge-app/src/utils/tinlake/useTinlakePools.ts
- centrifuge-app/src/utils/usePools.ts
> Centrifuge App: Fix Tinlake assets

- centrifuge-js/src/modules/proxies.ts
- centrifuge-react/src/components/WalletProvider/WalletProvider.tsx
- centrifuge-react/src/hooks/useCentrifugeTransaction.ts
> Centrifuge App: Get all proxies

- centrifuge-app/src/components/OnboardingAuthProvider.tsx
- onboarding-api/src/controllers/auth/authenticateWallet.ts
- onboarding-api/src/utils/networks/evm.ts
- onboarding-api/src/utils/networks/networkSwitch.ts
This pull request fixes an issue when authenticating on the `/onboarding` page with a Safe wallet. Since Safe wallets are smart contracts, they [can not generate ECDSA signatures](https://ethereum.stackexchange.com/questions/122458/web3-eth-personal-sign-with-walletconnect-and-gnosis-safe/122469#122469). Therefore, Safe uses [EIP-1271](https://eips.ethereum.org/EIPS/eip-1271) for message signing and validating signatures. I mostly followed this [guide](https://docs.safe.global/safe-smart-account/signatures/eip-1271#verifying-a-signature) from Safe's documentation in order to implement the signature validation for when a user is using Safe. However, since we generate jwt's on the server side, I needed to do the check on both the frontend/backend.
Closes #1649
> fix: safe auth

- centrifuge-app/src/components/Report/InvestorTransactions.tsx
Trunacte account addresses only in the table, not in the exported CSV file
> Centrifuge App: Fix formatting for investor transactions

- centrifuge-app/src/components/Portfolio/InvestedTokens.tsx
- centrifuge-app/src/components/Portfolio/Transactions.tsx
- centrifuge-app/src/config.ts
- centrifuge-app/src/pages/Portfolio/TransactionHistory.tsx
- centrifuge-app/src/pages/Portfolio/index.tsx
- centrifuge-app/src/pages/Prime/Detail.tsx
- centrifuge-app/src/pages/Prime/index.tsx
- centrifuge-js/src/modules/pools.ts
- centrifuge-react/src/components/WalletMenu/ConnectButton.tsx
- centrifuge-react/src/components/WalletMenu/WalletMenu.tsx
- centrifuge-react/src/components/WalletMenu/index.tsx
Prime detail page without portfolio graph and P&L
[#1640](https://github.com/centrifuge/apps/issues/1640)
> Centrifuge App: Prime detail

- centrifuge-js/src/modules/pools.ts
> Fix closed asset handling

- centrifuge-app/src/components/InvestRedeem/InvestRedeemLiquidityPoolsProvider.tsx
- centrifuge-react/src/components/WalletProvider/WalletProvider.tsx
> Centrifuge App: Disable permits for smart contract wallets

- centrifuge-app/src/pages/Loan/FinancingRepayment.tsx
- centrifuge-app/src/pages/Loan/index.tsx
This pull request updates the asset detail page:
- removes `View NFT` button for all assets
- swaps `Transaction history` and `Remaining maturity` chart
- removes `Remaining maturity` for `oracle` and `cash` assets
- removes `Pricing` and `Financing & repayment cash flow` for `cash` assets
#1796 
#1764 
Asset detail page
> chore: update asset detail page

- centrifuge-app/src/components/PoolFees/index.tsx
- centrifuge-js/src/modules/pools.ts
> Fix fee position adding when updating fees

- centrifuge-app/src/pages/Loan/HoldingsValues.tsx
- centrifuge-app/src/pages/Loan/TransactionTable.tsx
> Fix average settlement price calculations

- centrifuge-app/src/pages/Loan/TransactionTable.tsx
- centrifuge-app/src/pages/Loan/index.tsx
- renames face flow to face value
- adds YTM (yield to maturity?) to transaction table on asset detail page
- adds weighted average YTM to asset detail summary
--> to test look at Anemoy assets
#2111
> YTM in asset details

- centrifuge-app/src/pages/IssuerCreatePool/AdminMultisig.tsx
- centrifuge-app/src/pages/IssuerCreatePool/IssuerInput.tsx
- centrifuge-app/src/pages/IssuerCreatePool/TrancheInput.tsx
- centrifuge-app/src/pages/IssuerCreatePool/index.tsx
- centrifuge-js/src/modules/pools.ts
- Default currency to native USDC on testnets, localUSDC on production
- Default initial max reserve to 1M
- Make legal name of the issuer representative and description non required on testnets
- Make executive summary PDF, website, email all non required on testnets
- Allow empty Token name in Tranches. Disable token name input for 1 tranche (will just be the pool name). If a 2nd tranche is added, default to Senior | Junior. If a 3rd tranche is added, default to Senior | Mezzanine | Junior.
- Don't allow adding more than 3 tranches
-  Default min investment to 1,000.
- Pool Managers => Pool managers
#2231 
- [x ] Dev
- [x ] Product
> Pool creation improvements

- centrifuge-app/src/components/PageSummary.tsx
- centrifuge-app/src/pages/Loan/index.tsx
- centrifuge-app/src/pages/Pool/Overview/index.tsx
Add gray background to fill 100vh in:
- assets overview page
- asset page
#2248 
- [ x ] Dev
- [ x ] Product
_I will highly suggest <if we have the time> that we work on fixing the nav bar on the right side - see screenshot_
> Add gray background to loan pages

- centrifuge-app/src/pages/IssuerPool/Access/ChangeTreshold.tsx
- centrifuge-app/src/pages/IssuerPool/Access/MultisigForm.tsx
- centrifuge-app/src/pages/IssuerPool/Configuration/WriteOffGroups.tsx
- centrifuge-app/src/pages/IssuerPool/Configuration/index.tsx
- centrifuge-app/src/pages/IssuerPool/Pricing/OracleFeeders.tsx
Add improvements to oracle setup
- Change Pricing tab by default
- Oracle feeders => Oracle providers
- Adapt configuration change component from Pool managers setup for Oracle feeders:
Header: Oracle update threshold
Subtitle: `Determine how many oracle providers are required before a pricing update is finalized and will become reflected in the NAV.
- Toast Set oracle prices => Set oracle providers
- Write-off policy
- Move Write-off policy section from Configuration tab to Pricing tab (below oracle providers)
- Remove At least one write-off activity is required subtitle
#2242
> Oracle improvements

- centrifuge-app/src/pages/Loan/MetricsTable.tsx
- centrifuge-app/src/pages/Loan/index.tsx
- Fund Short Description should be fully shown, taking up multiple rows
- Fund Link should automatically become <a> with target="_blank"
#2263 
- [ x ] Dev
- [ x ] Product
> Add fixes to assets fields table

- centrifuge-app/src/components/SupportedBrowserBanner.tsx
- centrifuge-app/src/utils/getSupportedBrowser.tsx
- centrifuge-react/src/components/WalletProvider/WalletDialog.tsx
- centrifuge-react/src/components/WalletProvider/evm/connectors.ts
- Show non-support banner regardless if user wallet is connected. Do not show the banner if browser is chrome/firefox
- Links to firefox store shall be different than the url for chrome store. Unfortunately '@subwallet/wallet-connect/types' only returns walletUrl for chrome only, some hard code links was required to make it work on firefox.
#1838 
- [ x ] Dev
> Links for wallets

- centrifuge-app/src/pages/Pools.tsx
Padding y=5 was removed when the unused component was removed. Add back the padding.
#2290
> Add padding to pools list

- centrifuge-app/src/pages/Pools.tsx
Fix Total value locked (TVL) box to cover only half width of page
#2291
> Fix Total value locked (TVL) box to cover only half width of page

- centrifuge-app/src/components/PoolFees/EditFeesDrawer.tsx
- centrifuge-app/src/pages/IssuerPool/Access/AssetOriginators.tsx
- centrifuge-app/src/pages/IssuerPool/Access/MultisigForm.tsx
- centrifuge-app/src/pages/IssuerPool/Configuration/AddAddressInput.tsx
- centrifuge-app/src/pages/IssuerPool/Investors/InvestorStatus.tsx
- centrifuge-js/src/utils/index.ts
- fabric/src/components/TextInput/index.tsx
Use the address input that we have for CFG transfers, that supports both EVM addresses and Centrifuge addresses
#2221 
- [x ] Dev
- [ x] Product
Pool managers on Create pool page
Investor input for Centrifuge Chain on Investors tab
AO wallets on Access tab
Receiving address on Fees tab
> Use evm inputs for issuers

- centrifuge-app/src/components/Menu/PageLink.tsx
When upgrading react-router, the new `<Link /> `have default style of 16px over the 14px we were using before in our menu. Causing a discrepancy between the components with `<Link />` and the components with `<Text />`
#2007
> Fix links style

- centrifuge-app/src/components/Charts/AssetPerformanceChart.tsx
- centrifuge-app/src/components/Charts/PoolPerformanceChart.tsx
- centrifuge-app/src/components/LiquidityTransactionsSection.tsx
- centrifuge-app/src/components/PoolOverview/PoolPerfomance.tsx
- centrifuge-app/src/components/Portfolio/CardPortfolioValue.tsx
- centrifuge-app/src/components/Portfolio/PortfolioValue.tsx
- centrifuge-app/src/pages/Pool/Liquidity/index.tsx
- centrifuge-app/src/pages/Pool/Overview/index.tsx
- Asset detail page:  Add < no data available > if data is empty to avoid layout emptiness/switching **(picture 1)**
- Liquidity page: Prevent layout switching by reorganizing rendering of component **(picture 2)**
- Prime page: Add box around graph layout to maintain dimensions. **(picture 3)**
#2223 
- [ x ] Dev
**Picture 1**
**Picture 2**
https://github.com/centrifuge/apps/assets/51223655/e0334def-5766-4eac-ba7f-43e4d07faafc
**Picture 3**
> Fix layout on assets detail page

- centrifuge-app/src/components/Dialogs/ShareMultisigDialog.tsx
- centrifuge-app/src/pages/IssuerCreatePool/index.tsx
- centrifuge-app/src/pages/IssuerPool/Access/ChangeTreshold.tsx
- centrifuge-app/src/pages/IssuerPool/Access/MultisigForm.tsx
- centrifuge-app/src/pages/IssuerPool/Access/PoolManagers.tsx
- centrifuge-app/src/pages/MultisigApproval.tsx
- centrifuge-js/src/utils/index.ts
Basically having a multisig with a threshold of 1. In reality it's not a multisig, but just having multiple addresses as the Any proxy on the pool admin proxy. 
[#2234](https://github.com/centrifuge/apps/issues/2234)
> Allow multiple pool managers without a multisig

- centrifuge-app/src/components/PoolOverview/KeyMetrics.tsx
- centrifuge-js/src/modules/pools.ts
> Fix pending order

- centrifuge-app/src/config.ts
- centrifuge-app/src/pages/Loan/FinanceForm.tsx
- fabric/src/components/Select/index.tsx
- Allow selecting the withdraw address in case there's multiple for a domain (or excluding a domain)
- Include Centrifuge chain withdraw addresses for each domain
#2313
> Finance form: Withdraw address select

- centrifuge-app/src/components/LoanList.tsx
- remove the numbers associated with the asset (1,2,3,4).
- Sort the list by descending maturity date.
- Set amount to 0 if the asset is empty
- Make the asset name column wider so we can see the full asset name, or full text of the asset. We will need this for DYF
#2314
> Fixes asset list component

- centrifuge-app/src/utils/date.ts
Settlement date & maturity date format date function causing error when transforming dates from timestamp.
#2325
> Date timezone causing error - convert to UTC

- centrifuge-app/src/components/Report/AssetList.tsx
- centrifuge-app/src/components/Report/ReportContext.tsx
- centrifuge-app/src/components/Report/ReportFilter.tsx
- centrifuge-app/src/components/Report/index.tsx
- centrifuge-app/src/components/RouterLinkButton.tsx
- centrifuge-app/src/pages/Loan/index.tsx
- centrifuge-app/src/utils/getCSVDownloadUrl.ts
- centrifuge-app/src/utils/usePools.ts
- centrifuge-js/src/modules/pools.ts
- centrifuge-js/src/types/subquery.ts
Update asset list report 
- Use subquery instead of onchain for the snapshots
- Add new columns/value pairs
- Add new date filter for asset report 
- Set <ongoing> as default filter value
#2273
> Asset list report update

- centrifuge-app/src/components/PoolOverview/TransactionHistory.tsx
- centrifuge-app/src/components/Portfolio/TransactionTypeChip.tsx
- centrifuge-app/src/components/Report/TokenPrice.tsx
- centrifuge-app/src/components/Report/utils.tsx
- centrifuge-app/src/pages/Loan/TransactionTable.tsx
- centrifuge-js/src/modules/pools.ts
- centrifuge-js/src/types/subquery.ts
> Support corrections (increase/decrease debt)

- centrifuge-app/src/config.ts
- centrifuge-app/src/utils/tinlake/useTinlakePools.ts
> Remove testnet tinlake pools

- centrifuge-app/src/components/Charts/PoolPerformanceChart.tsx
- Utilize on chain data for token price & nav 
- Keep only months on graph regarding data length to maintain consistency 
- Show only one month per internal, do not repeat month or skip months
#2312 
#2310
> Utilize on chain data for token price pool graph

- centrifuge-js/src/modules/pools.ts
- centrifuge-js/src/types/subquery.ts
- centrifuge-js/src/utils/BN.ts
Fixes missing investment/redemption amounts in the cash flow report
[#2406](https://github.com/centrifuge/apps/issues/2406)
> Fix cash flow report investments/redemptions

- centrifuge-js/src/modules/pools.ts
With the new instance of subquery a hard limit has been implemented on the server side and the query does not return more than 100 items at once. This PR implements cursor based pagination just in the SDK so that we don't have to build pagination on the UI.
> Hotfix: Add cursor based pagination for asset transactions

- centrifuge-app/src/pages/NavManagement/NavManagementAssetTable.tsx
> Fix nav management card value in Drawer

- centrifuge-app/src/pages/NavManagement/NavManagementAssetTable.tsx
Just fixing using `pool.reserve.total` instead of `pool.reserve.available`.
Minors: 
* added docs for the future
* removed redundant calculation between pannel and card
> misc: Adapt docs and use correct reserve amount

- centrifuge-app/src/pages/IssuerCreatePool/TrancheInput.tsx
- centrifuge-app/src/pages/IssuerCreatePool/index.tsx
- centrifuge-app/src/pages/IssuerPool/Configuration/Details.tsx
- centrifuge-app/src/pages/IssuerPool/Configuration/Issuer.tsx
- centrifuge-js/src/modules/pools.ts
> Add new fields to metadata and allows editing

- centrifuge-app/src/components/PoolCard/index.tsx
- centrifuge-app/src/components/PoolList.tsx
- centrifuge-app/src/components/PoolOverview/TrancheTokenCards.tsx
- centrifuge-app/src/utils/tinlake/useTinlakePools.ts
- centrifuge-js/src/modules/pools.ts
Getting the latest tranche snapshots for all tranches for all pools was the cause of the large amount of calls to subquery. There was a call for each tranche, and it was done more than once for some reason. With over a hundred pools/tranches on demo that was a lot. Now getting the yields in `getPools` is done with one call for all pools/tranches.
[#2432](https://github.com/centrifuge/apps/issues/2432)
> Reduce calls to subquery

- centrifuge-app/src/components/IssuerSection.tsx
- centrifuge-app/src/pages/IssuerCreatePool/PoolRatingInput.tsx
- centrifuge-app/src/pages/IssuerCreatePool/PoolReportsInput.tsx
- centrifuge-app/src/pages/IssuerCreatePool/TrancheInput.tsx
- centrifuge-app/src/pages/IssuerCreatePool/index.tsx
- centrifuge-app/src/pages/IssuerPool/Configuration/Details.tsx
- centrifuge-app/src/pages/IssuerPool/Configuration/EpochAndTranches.tsx
- centrifuge-app/src/pages/IssuerPool/Configuration/Issuer.tsx
- centrifuge-js/src/modules/pools.ts
#2435
- adds pool structure
- fixes rating URL not saving to IPFS
- fixes editing of target apy
- fixes pool name in tranche name editing
- adds all more values to edit overview (before clicking edit)
> Edit pool fields

- centrifuge-app/src/pages/NavManagement/NavManagementAssetTable.tsx
if currentPrice is undefined, it's showing as NaN causing error to view page
> Fix bug on nav management

- centrifuge-app/src/components/Charts/PoolPerformanceChart.tsx
- centrifuge-app/src/components/Charts/utils.ts
- centrifuge-app/src/components/Portfolio/CardPortfolioValue.tsx
- centrifuge-app/src/components/Portfolio/PortfolioValue.tsx
Y axis values should update accordingly to show an increasing value instead of flat values Ticks should be month only
#2300
> Fix gnosis chart

- centrifuge-app/src/components/Charts/AssetPerformanceChart.tsx
- centrifuge-app/src/components/Charts/PoolPerformanceChart.tsx
- centrifuge-app/src/components/IssuerSection.tsx
- centrifuge-app/src/components/LayoutBase/styles.tsx
- centrifuge-app/src/components/LoanLabel.tsx
- centrifuge-app/src/components/Menu/GovernanceMenu.tsx
- centrifuge-app/src/components/Menu/index.tsx
- centrifuge-app/src/components/PoolCard/index.tsx
- centrifuge-app/src/components/PoolOverview/KeyMetrics.tsx
- centrifuge-app/src/components/PoolOverview/TrancheTokenCards.tsx
- centrifuge-app/src/components/PoolOverview/TransactionHistory.tsx
- centrifuge-app/src/components/Portfolio/Holdings.tsx
- centrifuge-app/src/components/Report/AssetList.tsx
- centrifuge-app/src/components/Report/AssetTransactions.tsx
- centrifuge-app/src/components/Report/DataFilter.tsx
- centrifuge-app/src/components/Report/FeeTransactions.tsx
- centrifuge-app/src/components/Report/InvestorList.tsx
- centrifuge-app/src/components/Report/InvestorTransactions.tsx
- centrifuge-app/src/components/Report/OracleTransactions.tsx
- centrifuge-app/src/components/Report/TokenPrice.tsx
- centrifuge-app/src/components/Tooltips.tsx
- centrifuge-app/src/pages/IssuerCreatePool/IssuerInput.tsx
- centrifuge-app/src/pages/IssuerCreatePool/TrancheInput.tsx
- centrifuge-app/src/pages/IssuerPool/Configuration/EpochAndTranches.tsx
- centrifuge-app/src/pages/Loan/TransactionTable.tsx
- centrifuge-app/src/pages/Loan/index.tsx
- centrifuge-app/src/pages/Pools.tsx
Placeholder ticket for all the product feedback and bug fixes for the redesign work.
#2471
#2474
> Redesign feedback 

- centrifuge-app/src/components/InvestRedeem/InvestRedeemCentrifugeProvider.tsx
- centrifuge-app/src/components/IssuerSection.tsx
- centrifuge-app/src/components/PoolOverview/TrancheTokenCards.tsx
> Redesign: Fix infinite loading of connect/invest button

- centrifuge-app/src/components/Charts/PoolPerformanceChart.tsx
- centrifuge-app/src/components/LayoutBase/styles.tsx
- centrifuge-app/src/components/Menu/PageLink.tsx
- centrifuge-app/src/components/Menu/Toggle.tsx
- centrifuge-app/src/components/PoolCard/index.tsx
- centrifuge-app/src/components/PoolOverview/KeyMetrics.tsx
- centrifuge-app/src/components/PoolOverview/TrancheTokenCards.tsx
- centrifuge-app/src/components/Tooltips.tsx
- fabric/src/theme/tokens/theme.ts
Small fixes I noticed while going through the latest changes plus shadow background to side bar
> Add shadow background to nav bar

- centrifuge-app/src/components/InvestRedeem/InvestRedeemLiquidityPoolsProvider.tsx
- centrifuge-app/src/components/OnboardingAuthProvider.tsx
- centrifuge-js/src/utils/signERC2612Permit.ts
- fixes a bug loading the pool overview page where chainId is incorrectly references from provider
> Bug fetching chain id

- centrifuge-app/src/components/Portfolio/Transactions.tsx
- centrifuge-app/src/pages/Portfolio/index.tsx
> Show graph on portfolio page

- centrifuge-app/package.json
- centrifuge-js/src/CentrifugeBase.ts
- package.json
- yarn.lock
> Isomorphic WebSocket so that cent-js works on server side

- centrifuge-app/src/pages/Loan/FinanceForm.tsx
Remove check that stopped withdraw batch being included. And fix submit button.
> Fix withdraw batch

- centrifuge-app/src/components/PoolCard/index.tsx
- centrifuge-app/src/components/PoolOverview/TrancheTokenCards.tsx
- centrifuge-app/src/components/Tooltips.tsx
- centrifuge-app/src/pages/IssuerCreatePool/IssuerCategories.tsx
- centrifuge-app/src/pages/IssuerCreatePool/PoolDetailsSection.tsx
- centrifuge-app/src/pages/IssuerCreatePool/PoolSetupSection.tsx
- centrifuge-app/src/pages/IssuerCreatePool/PoolStructureSection.tsx
- centrifuge-app/src/pages/IssuerCreatePool/index.tsx
- centrifuge-app/src/pages/IssuerCreatePool/oldindex.tsx
- centrifuge-app/src/pages/IssuerCreatePool/types.ts
- centrifuge-app/src/pages/IssuerPool/Access/AssetOriginators.tsx
- centrifuge-app/src/pages/Pool/Assets/index.tsx
- centrifuge-js/src/modules/pools.ts
Review the pool structure section. There's some typescript and functionality to create a pool that is not implemented yet. 
This review is mainly for UI work on the pool setup section
https://www.figma.com/design/ng7qdNcSCXSDA6ZUdWIs6u/Pool-Overview%2F-Pool-Detail?node-id=3492-508&node-type=canvas&m=dev
> Pool structure - create pool 

- centrifuge-app/src/components/Menu/IssuerMenu.tsx
- centrifuge-app/src/components/Menu/Toggle.tsx
- centrifuge-app/src/components/Menu/index.tsx
- centrifuge-app/src/pages/IssuerCreatePool/AdminMultisig.tsx
- centrifuge-app/src/pages/IssuerCreatePool/IssuerCategories.tsx
- centrifuge-app/src/pages/IssuerCreatePool/PoolDetailsSection.tsx
- centrifuge-app/src/pages/IssuerCreatePool/PoolSetupSection.tsx
- centrifuge-app/src/pages/IssuerCreatePool/PoolStructureSection.tsx
- centrifuge-app/src/pages/IssuerCreatePool/index.tsx
- centrifuge-app/src/pages/IssuerCreatePool/types.ts
- centrifuge-app/src/pages/IssuerCreatePool/utils.ts
- centrifuge-app/src/pages/IssuerCreatePool/validate.ts
- centrifuge-js/src/modules/pools.ts
- fabric/src/components/Dialog/index.tsx
- fabric/src/components/Toast/index.tsx
- fabric/src/icon-svg/icon-chevron-down.svg
Creation of pool redesign 
#2529
> Create pool - functionality

- centrifuge-app/src/components/LoanList.tsx
- centrifuge-app/src/pages/Pool/Assets/index.tsx
Fix assets table quantity and pagination
#2558
> Fix assets table quantity and pagination

- centrifuge-app/src/pages/NavManagement/NavManagementAssetTable.tsx
> Add remark tags, and attestation signature type

- centrifuge-app/src/components/InvestRedeem/Claim.tsx
- centrifuge-app/src/components/InvestRedeem/InvestForm.tsx
- centrifuge-app/src/components/InvestRedeem/InvestRedeemCentrifugeProvider.tsx
- centrifuge-app/src/components/InvestRedeem/InvestRedeemLiquidityPoolsProvider.tsx
- centrifuge-app/src/components/InvestRedeem/InvestRedeemTinlakeProvider.tsx
- centrifuge-app/src/components/InvestRedeem/RedeemForm.tsx
- centrifuge-app/src/components/InvestRedeem/types.ts
- centrifuge-js/src/modules/liquidityPools.ts
Enable the CentrifugeRouter before doing any other LP action, if the router isn't yet enabled for the user, which can happen for investments made before the router was implemented.
[#2577](https://github.com/centrifuge/apps/issues/2577)
> Enable CentrifugeRouter if needed

- centrifuge-app/src/components/Report/DataFilter.tsx
- centrifuge-app/src/components/Report/Orders.tsx
- centrifuge-app/src/components/Report/ReportContext.tsx
- centrifuge-app/src/components/Report/index.tsx
- centrifuge-app/src/utils/date.ts
- centrifuge-app/src/utils/usePools.ts
- centrifuge-js/src/modules/pools.ts
- centrifuge-js/src/types/subquery.ts
- Add new order reports 
#2109
> Add orders report

- centrifuge-app/src/components/PoolOverview/TransactionHistory.tsx
- centrifuge-app/src/components/Report/AssetTransactions.tsx
- centrifuge-app/src/components/Report/DataFilter.tsx
- centrifuge-app/src/components/Report/Orders.tsx
- fabric/src/components/Positioner/index.tsx
- fabric/src/components/Text/index.tsx
Modify asset transactions table to display new values 
Transaction date
Transaction
Amount
Epoch (we keep this from the current asset transactions table)
View transaction
#2526
> 2526 assets transactions table

- centrifuge-app/src/components/Charts/PoolPerformanceChart.tsx
- centrifuge-app/src/components/PoolOverview/TrancheTokenCards.tsx
- centrifuge-js/src/modules/pools.ts
> Fix yields

- centrifuge-app/package.json
- centrifuge-app/src/components/Charts/SimpleBarChart.tsx
- centrifuge-app/src/components/Report/AssetList.tsx
- centrifuge-app/src/components/Report/AssetTransactions.tsx
- centrifuge-app/src/components/Report/BalanceSheet.tsx
- centrifuge-app/src/components/Report/CashflowStatement.tsx
- centrifuge-app/src/components/Report/FeeTransactions.tsx
- centrifuge-app/src/components/Report/InvestorList.tsx
- centrifuge-app/src/components/Report/InvestorTransactions.tsx
- centrifuge-app/src/components/Report/Orders.tsx
- centrifuge-app/src/components/Report/ProfitAndLoss.tsx
- centrifuge-app/src/components/Report/ReportContext.tsx
- centrifuge-app/src/components/Report/ReportFilter.tsx
- centrifuge-app/src/components/Report/TokenPrice.tsx
- centrifuge-app/src/components/Report/index.tsx
- centrifuge-app/src/components/Report/useReportsQuery.tsx
- centrifuge-app/src/components/Report/utils.tsx
- centrifuge-app/src/utils/formatting-sdk.ts
- centrifuge-app/src/utils/formatting.ts
- yarn.lock
Integrate new sdk into out current app (reports and data tabs only)
> add new sdk to current app

- centrifuge-js/src/modules/pools.ts
Jay updated the pool metadata to "listed:false" so we don't need to hide it from the code anymore.
> Show CLO pool back

- centrifuge-app/src/pages/Portfolio/CFGTokenMigration.tsx
- centrifuge-app/src/pages/Portfolio/CFGTokenMigrationCent.tsx
- centrifuge-app/src/pages/Portfolio/useTokenBalance.tsx
- centrifuge-js/src/modules/pools.ts
- The code was missing the reserved property thus causing the bug for some wallets, now the user won't be able to migrate if the wallet has frozen or reserved tokens. 
banner is going to show as a warning
button is going to be disabled
- Add logic so we check for allowance value during WCFG migration
> Fix bug on the disabled button

- centrifuge-app/src/pages/Pool/Overview/HoldingsTable.tsx
- Maturity date in ipfs is display with format DD/MM/YYYY - sorting in JS is most effective when the date is display as timestamp
> Fix sorting for maturity date
